### ISSUE TITLE
`parquet_dataset` does not respect ordering of `_metadata`

### ISSUE THREAD

**Issue by agoose77** [apache/arrow#10580]
Hi all, thanks for the useful library!

I noticed when calling `pyarrow.dataset.parquet_dataset` that the order of the files (`dataset.files`) does not match that of the `_metadata` row group columns. I'm not an Arrow expert by any means, but is this intentional?

I think the unordered map is the culprit, but I have not recompiled to test this theory. https://github.com/apache/arrow/blob/133b1a904bf7fc1d24343c306a2279e27d4ebe6d/cpp/src/arrow/dataset/file_parquet.cc#L870

**Comment by westonpace** [comment]
Can you help me understand a little bit more what you are asking about?  Your first statement mentions the order of the files.  Your second statement (regarding _metadata) seems to be mentioning the order of columns.  Are the columns or the files in the incorrect order?

**Comment by agoose77** [comment]
Hi @westonpace,

That's my mistake for not being clearer! I mean that the order of the *files* does not match the order in which they were written into the metadata. If one loops over the metadata file manually, the file order is correct, but when using `parquet_dataset`, the order does not match.

**Comment by westonpace** [comment]
Ah, I understand now.  I hadn't realized the difference between `_metadata` and `common_metadata` and I didn't realize `_metadata` contained info for each file.  I was thinking it was just another name for `common_metadata`.  Yes, I think your diagnosis is spot on.  As long as the files make it to the `Dataset` constructor in-order they should be returned in that order.  However, because of the unordered_map that you pointed out, those files are not making it to the constructor in the right order.  Please open a JIRA.

**Comment by agoose77** [comment]
Thanks @westonpace !

**Comment by westonpace** [comment]
It appears you opened ARROW-13153.  We can track this in JIRA now.  Can you please close this Github issue.
