### ISSUE TITLE
Does feather file identify with pyarrow.memory_map(file)?

### ISSUE THREAD

**Issue by hengaini2055** [apache/arrow#10899]
I understand the pyarrow can read different file such as csv, parquet and something else.  Does feather file format identify with csv or parquet? According to [Zero memory](https://towardsdatascience.com/apache-arrow-read-dataframe-with-zero-memory-69634092b1a) there is memory map file. Does feather file format identity with memory_map file? [](url)
I want to use arrow development a BI project, and I don't know about the following issues:

1. Zero memory! When I use a larger than Ram dataset， the data in disk must be feather or memory_map file?

**Comment by hengaini2055** [comment]
2. When I analyse the dataset,  I must change pa.table to pandas or dask?

**Comment by lidavidm** [comment]
The Feather (V2) file format, also known as the Arrow IPC file format, is neither CSV nor Parquet, but rather Arrow's format for data on disk. See this [FAQ entry](https://arrow.apache.org/faq/#what-is-the-difference-between-apache-arrow-and-apache-parquet) as well as the one immediately after it. 

The article you link is describing using uncompressed Feather/Arrow IPC files. This is because then the layout of data in memory is the same as the layout on disk, due to the Arrow specification, and you can memory-map the file and use it as-is. Of course, you can still memory-map a Parquet or CSV file - but you will have to decode the data first, which carries overhead. (This may still be manageable, e.g. you could decode and process one row group of a Parquet file at a time, but you won't gain the 'zero copy' benefits.)

For analysis of data, it depends. PyArrow has some [compute functions](https://arrow.apache.org/docs/python/api/compute.html) available and they may be sufficient for your needs. Else you may convert to Pandas or some other format as needed, but of course this increases your memory usage.

**Comment by hengaini2055** [comment]
@lidavidm Thanks! How can I memory-map a Parquet file? I want to gain 'zero copy' from a directory database(pyarrow). In Microsoft Power BI, We must read all dataset to memory and process it. The Memory will be the bottleneck. Should I use  uncompressed feather( memory map, file named *.arrow) file in directory, to gain 'zero copy' benefits?

**Comment by hengaini2055** [comment]
[library datasets](url), use ```pa.memory_map(filename)``` to create a memory mapped pa.table. The file may be a parquet file, a cvs file, or a *.arrow (feather file)? As you said, "Of course, you can still memory-map a Parquet or CSV file", maybe!

**Comment by lidavidm** [comment]
So to be clear: Parquet, CSV, and Feather are all different file formats, and memory-mapping is just one way to read a file. 

In the case of uncompressed Feather files *only*, you can get zero-copy reads. Again, this is because the format on disk is in this case the same as the format in memory. So if memory is your bottleneck, it sounds like this is likely your best choice.

Otherwise, memory-mapping may be faster (or slower!) than just reading the file. You cannot and will not get zero-copy from a Parquet file. However, Parquet files can be read incrementally, so you may still be able to make this work - it will just take more effort.

**Comment by JulesGM** [comment]
@lidavidm is there a reason that we can't read `pa.memory_map` files with feather? Why can't I read Huggingface's .arrow files, which are `pa.memory_map` files, if feather has a `open_table(path, memory_map=True)` setting?

**Comment by lidavidm** [comment]
@JulesGM what is the actual problem you're facing? (e.g. stack trace?)

**Comment by JulesGM** [comment]
<img width="1020" alt="Screenshot 2024-07-06 at 6 06 44 PM" src="https://github.com/apache/arrow/assets/3231217/0d15245f-0ac8-4538-8d13-0c552fee2908">

**Comment by JulesGM** [comment]
Huggingface datasets reads those files with https://github.com/huggingface/datasets/blob/main/src/datasets/table.py#L33
for in memory and with https://github.com/huggingface/datasets/blob/main/src/datasets/table.py#L47 and https://github.com/huggingface/datasets/blob/main/src/datasets/table.py#L62 for memory mapped

**Comment by JulesGM** [comment]
@lidavidm

**Comment by JulesGM** [comment]
Basically you can read one of those with 

```
import pyarrow as pa
mm = pa.memory_map("the path")
stream = pa.ipc.open_stream(mm)
schema = stream.schema
pa_table = stream.read_all()
```

**Comment by JulesGM** [comment]
<img width="989" alt="Screenshot 2024-07-06 at 6 32 12 PM" src="https://github.com/apache/arrow/assets/3231217/9d9b5bd6-e551-4d1d-9875-646c9e33ceb9">

**Comment by JulesGM** [comment]
Easiest way to reproduce with a tiny dataset is this:
```python
import datasets
import subprocess as sp
import pyarrow as pa
from pyarrow import feather

gsm8k = datasets.load_dataset("gsm8k", "socratic", cache_dir="./cache")
paths = sp.check_output(["find", "cache", "-iname", "*.arrow"], text=True).strip().split()

print(paths)
feather.read_feather(paths[0])
```

**Comment by kou** [comment]
It seems that your file uses the Arrow IPC "streaming" format https://arrow.apache.org/docs/format/Columnar.html#ipc-streaming-format not the Arrow IPC "file" format https://arrow.apache.org/docs/format/Columnar.html#ipc-file-format .

**Comment by lidavidm** [comment]
And in addition to what Kou said^, converting to Pandas likely loses some benefits of memory mapping (you probably have a copy of the data in memory now, though maybe not if Pandas is using the new Arrow-backed arrays)

**Comment by JulesGM** [comment]
Thanks for the response. Are you folks thinking of supporting the streaming format in feather?

**Comment by kou** [comment]
We never support it.
BTW, you should use "Arrow IPC file format" instead of "Feather". They refer the same format but "Feather" is a deprecated name. See also: https://lists.apache.org/thread/d2l7179yd41gfdhktrl1h06gh31l8l4l

**Comment by JulesGM** [comment]
I didn't say feather file format, which I think is what they say to not say. I meant in the feather arrow ipc reader defined here https://arrow.apache.org/docs/python/feather.html
I like that that reader is simple to use.

**Comment by JulesGM** [comment]
I would be curious to know the reasoning to not provide a convenient reader like the feather ones for the streaming files. is it just that the streaming files are not meant to be saved to the drive?

**Comment by lidavidm** [comment]
Would you mind opening a new issue for the Python maintainers?

**Comment by JulesGM** [comment]
fyi @kou https://arrow.apache.org/docs/python/feather.html says word for word "feather file format"

**Comment by lidavidm** [comment]
That probably deserves its own issue too (for the Python maintainers) to update the docs following the discussion
