### ISSUE TITLE
How to read nested fields when using read table to read a parquet file in PyArrow?

### ISSUE THREAD

**Issue by vikasmalhotra08** [apache/arrow#11347]
Hello,

Is it possible to read specific nested fields when trying to read a parquet file? I am getting an error that:
```pyarrow.lib.ArrowInvalid: Field named 'a.b' not found or not unique in the schema.```

Here is how the file is written out:
```
# Writing as table
pq.write_table(
    table, 
    where=file_path, 
    version='2.0', 
    compression='snappy'
)
```

Here is the schema that's present in the parquet field:
```
required group field_id=0 schema {
optional group field_id=1 a {
    optional binary field_id=2 abc (String);
    optional group field_id=3 b {
      optional binary field_id=4 c (String);
      optional binary field_id=5 d (String);
      optional binary field_id=6 e (String);
    }
}
}
```

Here is how I am trying to read it:
```
# read the table
columns_needed = ['a.b', 'a.b.c']
data = pq.read_table(
    file_path, 
    columns=columns_needed)
```

**Comment by emkornfield** [comment]
Sorry closed this too soon, something seems off here. 'a.b.c' won't work because of the JIRA issue but the error you are getting seems to indicate something strange is going on with the arrow  schema, not necessary parquet schema.  Is it possible to create minimal repro with an actual table you are trying to write?  What does the Arrow schema look like if you don't filter columns?

**Comment by emkornfield** [comment]
Closing now due to inactivity.  Please reopen if this problem persists with Arrow 6.0
