### ISSUE TITLE
How to append the new data to the existing table which is made before

### ISSUE THREAD

**Issue by wujinghe** [apache/arrow#11648]
Hello, 
My question is like https://stackoverflow.com/questions/61723529/how-to-append-to-existing-apache-arrow-array

Does Arrow support this feature?  After reading the doc and codes, I think Arrow can't support now. Do we have a way to Append a new data to the existing table.

**Comment by westonpace** [comment]
The answer on SO is correct.  Are you also asking about Rust?  Or some other implementation?  Data structures in Arrow are immutable.  You can create a chunked array with multiple arrays.

If you can describe your use case at a higher level we might be able to provide some advice on how to proceed.

**Comment by wujinghe** [comment]
I am using C++ to develop a memory-based data analysis platform. Arrow provides the memory data structure and unified data format, it is convenient to fetch data from local files or remote processes. But Data Analysis Platform can receive messages from some data sources in real time, so I need to dynamically append data to the Table.

After reading the source code, I want to create a chunked array,  then insert and combine to chunked array of the existing table, but I can't find the Api interface to do.

**Comment by edponce** [comment]
I think there are multiple different questions being asked. The SO question is about how to append to an `Array` while @wujinghe  is asking about how to append data to a `Table`. Then, there is also the question on how to combine multiple `ChunkedArrays` and `Tables`.
First of all, as @westonpace mentioned, Arrow containers are considered by design as immutable so `Append` methods are not available for all of them. Nevertheless, there are utilities to join these containers with very low overhead.

**CombineArrays**
Use [`auto new_array = Concatenate(arrays)`](https://github.com/apache/arrow/blob/master/cpp/src/arrow/array/concatenate.h#L34)

**Combine ChunkedArrays**
AFAIK, currently there is no utility function for this operation, but it is basically what `ConcatenateTables()` does internally, refer to [here](https://github.com/apache/arrow/blob/master/cpp/src/arrow/table.cc#L428-L437).

**Combine Tables**
Use [`Table->ConcatenateTables(tables)`](https://github.com/apache/arrow/blob/master/cpp/src/arrow/table.h#L270). [`ConcatenateTableOptions`](https://github.com/apache/arrow/blob/master/cpp/src/arrow/table.h#L255) are use to control the behavior of the concatenate operation.

**Comment by westonpace** [comment]
I didn't realize the question was about tables.  Tables are simply a collection of record batches with the same schema.  So you can append to a table by creating a new table with the new record batch.  For example, in pyarrow:

```
>>> import pyarrow as pa
>>> t1 = pa.Table.from_pydict({'a': [1, 2, 3], 'b': ['x', 'y', 'z']})
>>> t2 = pa.Table.from_pydict({'a': [4, 5, 6], 'b': ['a', 'b', 'c']})
>>> combined = pa.Table.from_batches(t1.to_batches() + t2.to_batches())
>>> combined.to_pydict()
{'a': [1, 2, 3, 4, 5, 6], 'b': ['x', 'y', 'z', 'a', 'b', 'c']}
```

If you truly need each array to be a contiguous region in memory then @edponce 's advice about concatenating is the way to go.

**Comment by wujinghe** [comment]
Thank you very much @westonpace and @edponce 

So I append to a new table and then **ConcatenateTables**.  I will test the performance later.
