### ISSUE TITLE
Is adding Parquet partitions/part files using R's arrow::write_dataset() transactional?

### ISSUE THREAD

**Issue by schelhorn** [apache/arrow#11781]
Dear Support,

thank you for arrow - it's great! I was wondering how the disk storage transaction model for `arrow`'s R interface behaves concerning partial writes of Parquet partitions/parts to disk.

If I have a (new or existing) Parquet dataset managed by `arrow`, and I am adding a partition to that dataset using:
```r
arrow::write_dataset(dataset=my_df,
                     path='my_dataset.parquet',
                     format='parquet',
                     partitioning='my_grouping_var',
                     compression='snappy',
                     use_dictionary=T,
                     write_statistics=T)
```
and the write is _interrupted_ for some reason (for instance, due to no disk space left on device, network connection to shared storage stalls, or main memory issues), will the partial write still remain within the dataset as a broken partition part file? If so, is there any way to recover from that situation?

Secondly, is it safe to have two or more R processes add partitions/parts to the Parquet dataset in parallel, and, if so, how is it ensured that no race conditions occur, i.e., that the part files that are generated are not overwriting each other?

Thanks a bunch!

**Comment by nealrichardson** [comment]
The arrow library is not a database, so it doesn't have transactions. If a function is in the middle of writing to disk and is interrupted, whatever it has already written will be on disk, partial or otherwise. If you wanted to make it atomic, you could `write_dataset()` to a `tempfile()` (directory) and then move that temp dir to your desired location after it finishes writing everything. 

If you wanted to use multiple processes to write to the same directory concurrently, you can provide a unique `basename_template` to each `write_dataset()` process so that they won't collide.

**Comment by schelhorn** [comment]
I see, thank you @nealrichardson. So I guess I would fare safer by indeed having a second dataset to write in the same directory as the main dataset, and then sync all new part files from the temporary dataset to the main dataset after writing has concluded successfully. Since file moves on the OS level are atomic this should safeguard against partial writes. For concurrent writes I'll use the `basename_template` as you proposed.

I know that partial writes may sound like an edge case to many, but once you write to shared storage in an HPC environment these things just happen from time to time.

Please feel free to close this issue (I also suggest you could add your answer to the `arrow` documentation if it's not already captured there).

**Comment by westonpace** [comment]
ARROW-15070
