### ISSUE TITLE
Javascript Filght Support

### ISSUE THREAD

**Issue by josh-voltaiq** [apache/arrow#12225]
Hi,

Is there any plan for supporting Flight in the Javascript packages? As I understand it now there is no support for this currently.

Thanks,
-Josh

**Comment by lidavidm** [comment]
Browser support for Flight has been discussed in a few contexts. Really, it needs someone to step up and do the work.

Some people have found success using one of the gRPC browser proxies. I'm not sure of the details myself, since Flight uses streaming methods heavily and my understanding is that these proxies have limited support for streaming.

There's also discussion on JIRA: https://issues.apache.org/jira/browse/ARROW-9860 would you like to chime in there?

Also see the exchange starting here: https://lists.apache.org/thread/g4lpzfrd2pt9zjoshr9g4lwwqpvp29rq while discussing UCX/HPC, the same groundwork is necessary to directly support something like WebSockets for the browser.

**Comment by josh-voltaiq** [comment]
Thank you very much for your prompt response!
