### ISSUE TITLE
[C++] how to run arrow::StringArray::GetString in parallel?

### ISSUE THREAD

**Issue by rewreu** [apache/arrow#12527]
Hi there, 

What's the good way to run arrow::StringArray::GetString in parallel?
The following code hangs due to running `a->GetString(i)` with multithreads
```c++
std::shared_ptr<arrow::StringArray> a;
std::unordered_set<std::string> UniqueStrings;
#pragma omp parallel for
for(long i = 0; i < lens; i++) {
    UniqueStrings.insert(a->GetString(i));
    doSomethingElse();
}
```

**Comment by westonpace** [comment]
If that code is hanging then I don't think it is due to `a->GetString(i)`.  At a glance it would seem that method call is thread safe.

I do not think it is thread safe to call `UniqueStrings.insert` from multiple threads although I would generally expect a segmentation fault and not a deadlock/hang.

I have no idea what `doSomethingElse` might be doing but it could also be contributing to this deadlock.

Why don't you run this in the debugger and then run `thread apply all bt` when you reach the deadlock?

**Comment by cyb70289** [comment]
I agree with @westonpace. stl containers are not thread safe.
