### ISSUE TITLE
pyarrow.json.read_json with a type inconsistent column possible?

### ISSUE THREAD

**Issue by hugofragata** [apache/arrow#12885]
Hi all.

My current use case for pyarrow is to read json and write the data as parquet.
I'm having issues on a specific json column that contains both integer and string values.

I could use pyarrow.json.ParseOptions and pass it an explicit_schema, however there's several schemas that have this issue and I'd like a single solution to all of them.

Is it possible to still keep the default inference behaviour while also ignoring or casting values that don't conform?
By ignoring I'm mean similar to unexpected_field_behavior:ignore but w/o an explicit_schema. Or, casting I mean casting to higher class of the json data type, for example int casts to str in this case.

Cheers!

**Comment by jorisvandenbossche** [comment]
It might be useful to include a small actual example with some dummy data and explain how you would want to read that.

Now, in general, I don't think we have much support for mixed types in JSON. In theory, those could also be read as "union" types (although for writing to parquet as a next step that's not so useful, since parquet doesn't support this)

> Is it possible to still keep the default inference behaviour while also ignoring or casting values that don't conform?

It's not fully clear to me what you exactly meaning with "ignoring" in this case. Do you mean ignoring certain values in a column, or ignoring a full column? And if ignoring certain values, what should they be replaced with? (null?) 

> Or, casting I mean casting to higher class of the json data type, for example int casts to str in this case.

Maybe we could enable this by letting the user specify an explicit schema (as str in this case), although that currently will also error if then a value doesn't match the specified type. 

From a quick search, someone else reported a similar JIRA about this: https://issues.apache.org/jira/browse/ARROW-11978

**Comment by pitrou** [comment]
> Is it possible to still keep the default inference behaviour while also ignoring or casting values that don't conform?

That doesn't seem to make much sense to me. If ignoring non-conforming values, then inference might choose any type it wants? (including bool or null?)

**Comment by hugofragata** [comment]
Yes, I do agree with your responses that the intended outcome for this issue is not clear. I will close this issue. Thanks!
