### ISSUE TITLE
Fix byte numbering in Layout.md to remove duplicates

### ISSUE THREAD

**Issue by JeffGreen** [apache/arrow#1296]
Hello! 

The binary format of Arrow is a bit confusing.  Layout.md attempts to specifically define the layout of each byte in the format.  Unfortunately, most examples "re-use" numbered bytes.  

Let's take the first and simplest Example Layout in that doc (Int32 Array).  Two buffers are specified, the null bitmap and the value buffer.  Each one refers to bytes 0-63.  I suspect that the null buffer actually occupies 0-63 and that the value buffer occupies 64-127 but the current ambiguous byte numbering means that the reverse could just as well be true.  

This is particularly confusing for more complex examples.  Eg if I have a Person struct with age:uint32 and weight:uint32, are age and weight next to each other in memory (ie 4 bytes age then 4 bytes weight)?  If I have an Array of two Person structs, is it [age, age, weight, weight] or [age, weight, age, weight] in memory?  

In order to broaden the usage of the project, I suggest that we depict the byte layout in a clearer manner.  I would propose something explicit like the byte description for the TCP Header here:

[https://en.wikipedia.org/wiki/Transmission_Control_Protocol#TCP_segment_structure](https://en.wikipedia.org/wiki/Transmission_Control_Protocol#TCP_segment_structure)

Because I don't yet understand the byte format, I can't make this change myself.

**Comment by wesm** [comment]
> Each one refers to bytes 0-63. I suspect that the null buffer actually occupies 0-63 and that the value buffer occupies 64-127 but the current ambiguous byte numbering means that the reverse could just as well be true.

Actually, there's no expectation that these buffers are contiguous in memory. They could both have resulted from independent calls to `posix_memalign` or `malloc` as the case may be

> Eg if I have a Person struct with age:uint32 and weight:uint32, are age and weight next to each other in memory (ie 4 bytes age then 4 bytes weight)? If I have an Array of two Person structs, is it [age, age, weight, weight] or [age, weight, age, weight] in memory?

Perhaps it would help to clarify the "child array" terminology in the document. The struct you describe has 2 child arrays, each of which is independent from the other as far as its memory layout. So the memory layout of "age" is identical to a plain int32 array. See https://github.com/apache/arrow/blob/master/format/Metadata.md#flattening-of-nested-data

The byte format is almost entirely described by the IPC metadata: https://github.com/apache/arrow/blob/master/format/IPC.md#recordbatch-body-structure

I think it would be good to consolidate Layout.md, Metadata.md, and IPC.md into a single specification document.  Since I am probably the "most expert" on the fine details of these documents and the reference C++ implementation, I can take a crack at this sometime in the next 2-3 weeks

**Comment by wesm** [comment]
See https://issues.apache.org/jira/browse/ARROW-1789

**Comment by JeffGreen** [comment]
>Actually, there's no expectation that these buffers are contiguous in memory. They could both have resulted from independent calls to posix_memalign or malloc as the case may be

I understand that bit now, thanks.

Your suggestion of a unified document would be very helpful as would a small but complete "hello world" example (complete meaning both the byte buffer(s) and the requisite header defining types and offsets)

With respect to structs (and perhaps this warrants its own "issue") - C supports the following two access patterns:

Case 1:
`struct Point{ x, y, z}`
`struct myPoints Point[1024]`

Case 2:
`int x[1024]`
`int y[1024]`
`int z[1024]`

In case 1, an array of Points is "row-major" in that X is next to Y is next to Z for a given Point.  In case 2, all X's are next to each other, all Y's are next to each other, and all Z's are next to each other and the equivalent of a Point is now column major.  I think we both understand the trade-offs of row major and column major access patterns depending on use case so I won't get into those here.  

While Arrow is primarily a column-major format, I was hoping that it also supports case 1 by essentially shoe-horning row-major iteration order into Arrow's column-major format using a single column of wide struct elements.  If I'm understanding the format right, a Struct in Arrow is really syntactic sugar for independent arrays of the child fields as opposed to a struct in C which puts struct elements next to each other in memory.  Is that understanding correct?  If so, are we missing out on a major (no pun intended) use case for certain data analysis patterns?  If Arrow instead stored Struct fields contiguously, the Arrow format would support both row and column major analysis.  This allows the user to choose either:

- single column with a mixed contiguous struct data type (row major memory ordering)
- set of independent columns of primitive data types (column major memory ordering)

**Comment by wesm** [comment]
I'd be interested in having a "packed C struct" type that is a logical type represented as `FixedSizeBinary` (the members must all be other fixed-width types). That's how structured arrays work in NumPy, for example. I'll open a JIRA

**Comment by wesm** [comment]
see https://issues.apache.org/jira/browse/ARROW-1790

**Comment by JeffGreen** [comment]
That should to it, thanks!

**Comment by TheNeuralBit** [comment]
@JeffGreen if all of the types in your C "struct" are the same, like in your example, you can use the FixedSizeList type for this purpose right now. I don't think its documented well, but its the same as the List type, except that there's no offset vector and the size of the lists is fixed and specified in the schema: https://github.com/apache/arrow/blob/39243ffaf5eb1d1f2a748ea1ec2b36658ba7f3d7/format/Schema.fbs#L50

We use it to pack lat/lng coordinates together since they're almost always accessed at the same time.

That being said a struct type that allows mixed types would be a welcome addition :)
