### ISSUE TITLE
Get value of any vector for a given row

### ISSUE THREAD

**Issue by iamsmkr** [apache/arrow#13445]
I have a list of vectors
```scala
val vectors = List(a: IntVector, b: BigIntVector, c: BigIntVector)
```

The `int get(int index)` method isn't available in any common vector interface. How do I get the value of all the vectors as shown below instead of having to invoke `int get(int index)` on each vector individually?
```scala
vectors.map(v => v.get(row))
```

Please suggest.

**Comment by lwhite1** [comment]
Hi @iamsmkr, 

I'm not really sure what you're looking to do. The BigIntVector class implements a version of get(int) that returns a long rather than int (since it's a BIG int vector). The only way to map over the three types would be to use long as the return type. 

```
   List<Long> rowData = vectors.map(v -> v.get(row)).boxed().collect(Collectors.toList());
```

I didn't attempt to compile that, as I'm not entirely sure I'm answering the right question. It might need some tweaking.

**Comment by iamsmkr** [comment]
@lwhite1 Thank you so much for your response! I have managed to achieve this using Shapeless instead. I have captured it in a blog post [here](http://shivamkapoor.com/blogs/technology/2022/07/17/tackling-heterogeneity-in-apache-arrow-value-vectors-using-shapeless/). Please see and let me know what you think?

**Comment by lidavidm** [comment]
`getObject` is part of `ValueVector`, though there isn't a `setObject` - would that have worked?

**Comment by lwhite1** [comment]
Looks like an interesting approach, but i'm not a Scala guy so I can't
really comment. Glad you were able to solve your issue.
