### ISSUE TITLE
Why signed integer type is used for array sizes rather than unsigned?

### ISSUE THREAD

**Issue by nvartolomei** [apache/arrow#13927]
Hi. I'm familiarising myself with the Arrow/Parquet ecosystem and though that a good starting point is reading their specs.

The [Array lengths](https://arrow.apache.org/docs/format/Columnar.html#array-lengths) section says "Array lengths are represented in the Arrow metadata as a 64-bit signed integer.". Unsigned seems a more natural choice, why was signed chosen instead?

Thank you.

**Comment by westonpace** [comment]
Mostly because Arrow needs to be compatible with as many languages as possible and some languages (e.g. Java) do not have a good representation for unsigned 64 bit integers.

Partly because really long arrays (e.g. > 2Bi elements) is something of a niche case that can often be worked around with chunked arrays or streaming.
