### ISSUE TITLE
[C++][Compute]Performance of arrow::compute compared to raw operations on `arrow::Array`

### ISSUE THREAD

**Issue by js8544** [apache/arrow#13981]
Hi folks, my team is trying out Arrow in our feature engineering pipeline. We really enjoyed coding with the C++ `arrow::compute` library thanks to its user friendly interfaces and comprehensive functions offered. Before we introduce it to our production code, I wrote a simple benchmark testing the performace of Compute functions vs raw operations on `arrow::Array`. To our surprise, `arrow::compute` is 4 times slower than the corresponding raw operations. 

The benchmark logic is: I have two arrays `keys` and `values` representing a kv map. I have another array `query_keys` representing the keys I want to query in the kv map. I want to get an array `result`, where `result[i]` is the value for `query_keys[i]` if the query key exists in the map and its value is greater than or equal to 100. 

The way I implement this logic is:
1. First create a boolean array `filter` by `GreaterEqual(values, 100)`.
2. Filter both `keys` and `values` using `Filter(keys, filter)` and `Filter(values, filter)`.
3. Call `IndexIn(query_keys, filted_keys)` to check `query_keys` in `filtered_keys` and get an array `index`.
4. Call `Take(filter_values, index)` to get the result.

The benchmark code is attached below.
[benchmark.tar.gz](https://github.com/apache/arrow/files/9433267/benchmark.tar.gz)

Here is the benchmark result:

|               ns/op |                op/s |    err% |     total | Benchmarking simple feature
|--------------------:|--------------------:|--------:|----------:|:----------------------------
|          163,837.00 |            6,103.63 |    0.6% |      0.01 | `arrow_compute`
|           31,675.56 |           31,570.09 |    0.5% |      0.01 | `arrow_raw`

It shows `arrow::compute` is 4 times slower than using raw operations on `arrow::Array`s.

I understand that `arrow::compute` functions need to check the underlying types of passed `arrow::Datum`s and `arrow::Array`s and dynamically dispatch the function. But is such large difference expected, or is my benchmark code wrong? 

update: gist for benchmark code: https://gist.github.com/js8544/8569c0e0bb810f1254904e4584def167

**Comment by drin** [comment]
That amount of overhead is definitely unexpected. For reference, I am working on a compute function for hashing and I see 15-25% overhead ([benchmark results](https://docs.google.com/presentation/d/1cUU_F3jB6LsOLbClhl34YdQiodtbz7l76l3juHTsC5k/edit#slide=id.g13e9d117f47_0_63)). That being said, some improvements are in the pipeline, such as [ARROW-16756](https://issues.apache.org/jira/browse/ARROW-16756) and others, to address some overheads. I also think you'll measure more overhead if your arrays are small and overhead can be amplified with many invocations (many chunks).

Generally speaking, what version of arrow are you on and what is the layout of the data? It sounds like you just have Arrays (contiguous) so maybe some of the overheads I have seen are not affecting you much.

Loosely related, you could consider using a [MapArray](https://arrow.apache.org/docs/cpp/api/array.html#_CPPv4N5arrow8MapArrayE) instead of 2 separate arrays. I think this should reduce steps by a bit because the validity map is shared.

Separately, this seems like a case where an array version of [map_lookup](https://arrow.apache.org/docs/cpp/compute.html#cpp-compute-vector-structural-transforms) would be nice.

Also, for convenience, would you mind putting your code in a repo or a gist, instead of a tarball? I haven't looked at it yet because of the extra steps involved

**Comment by drin** [comment]
Also, it'd be helpful if you broke down the comparisons in steps, rather than benchmarking end to end. I'll try to see if I can get something similar

**Comment by js8544** [comment]
> That amount of overhead is definitely unexpected. For reference, I am working on a compute function for hashing and I see 15-25% overhead ([benchmark results](https://docs.google.com/presentation/d/1cUU_F3jB6LsOLbClhl34YdQiodtbz7l76l3juHTsC5k/edit#slide=id.g13e9d117f47_0_63)). That being said, some improvements are in the pipeline, such as [ARROW-16756](https://issues.apache.org/jira/browse/ARROW-16756) and others, to address some overheads. I also think you'll measure more overhead if your arrays are small and overhead can be amplified with many invocations (many chunks).

@drin Thank you for your reply! Unfortunately increasing array size doesn't help. The data I posted was with key/value size 150 and query size 50. I increased them to 1500 and 500, `arrow::compute` is still 4x slower:

|               ns/op |                op/s |    err% |     total | Benchmarking simple feature
|--------------------:|--------------------:|--------:|----------:|:----------------------------
|          478,698.00 |            2,089.00 |    1.6% |      0.01 | `arrow_compute`
|           93,844.36 |           10,655.94 |    0.3% |      0.01 | `arrow_raw`

> Generally speaking, what version of arrow are you on and what is the layout of the data? It sounds like you just have Arrays (contiguous) so maybe some of the overheads I have seen are not affecting you much.
>

I am using arrow 9.0.0 and yes I'm using only arrays.

> Loosely related, you could consider using a [MapArray](https://arrow.apache.org/docs/cpp/api/array.html#_CPPv4N5arrow8MapArrayE) instead of 2 separate arrays. I think this should reduce steps by a bit because the validity map is shared.
> 
> Separately, this seems like a case where an array version of [map_lookup](https://arrow.apache.org/docs/cpp/compute.html#cpp-compute-vector-structural-transforms) would be nice.
> 

Thanks for the suggestion! Would you mind sharing some examples of using `MapArray` or `Map`? I thought about using them before writing the benchmark. But as far as I can tell, there are no documentation/examples of `MapArray` or `Map` other than api references on the official doc. I also checked the source code, but couldn't infer the idiomatic way of using them. So I sticked with arrays. 

> Also, for convenience, would you mind putting your code in a repo or a gist, instead of a tarball?
>

Here it is:  https://gist.github.com/js8544/8569c0e0bb810f1254904e4584def167

**Comment by drin** [comment]
Thanks! Unfortunately, I won't have time for the rest of today, but if no one else gets around to it I'll have time Sunday or Monday.

Otherwise, here's a quick pointer: https://github.com/apache/arrow/blob/master/cpp/src/arrow/testing/random.h#L351-L362

**Comment by js8544** [comment]
> Also, it'd be helpful if you broke down the comparisons in steps, rather than benchmarking end to end. I'll try to see if I can get something similar

GreaterEqual:
|               ns/op |                op/s |    err% |     total | Benchmarking GreaterEqual
|--------------------:|--------------------:|--------:|----------:|:--------------------------
|           29,365.00 |           34,054.15 |    0.9% |      0.01 | `arrow_compute`
|           17,671.61 |           56,587.94 |    0.7% |      0.01 | `arrow_raw`

Filters:
|               ns/op |                op/s |    err% |     total | Benchmarking Filters
|--------------------:|--------------------:|--------:|----------:|:---------------------
|           58,175.83 |           17,189.27 |    0.7% |      0.01 | `arrow_compute`
|           19,138.19 |           52,251.55 |    0.8% |      0.01 | `arrow_raw`

IndexIn:
|               ns/op |                op/s |    err% |     total | Benchmarking IndexIn
|--------------------:|--------------------:|--------:|----------:|:---------------------
|          362,390.33 |            2,759.46 |    1.0% |      0.01 | `arrow_compute`
|           53,136.05 |           18,819.61 |    0.7% |      0.01 | `arrow_raw`

Take:
|               ns/op |                op/s |    err% |     total | Benchmarking Take
|--------------------:|--------------------:|--------:|----------:|:------------------
|           31,476.71 |           31,769.53 |    0.8% |      0.01 | `arrow_compute`
|            8,796.36 |          113,683.38 |    0.7% |      0.01 | `arrow_raw`

It seems like IndexIn and Take are the culprit here.

**Comment by js8544** [comment]
I noticed that I can pass `skip_nulls=true` to `IndexIn` and `TakeOptions::NoBoundsCheck` to `Take` to optimize them. Here is the update results:

IndexIn:
|               ns/op |                op/s |    err% |     total | Benchmarking IndexIn
|--------------------:|--------------------:|--------:|----------:|:---------------------
|          351,957.33 |            2,841.25 |    1.0% |      0.01 | `arrow_compute`
|           90,050.75 |           11,104.85 |    0.9% |      0.01 | `arrow_raw`

Take:
|               ns/op |                op/s |    err% |     total | Benchmarking Take
|--------------------:|--------------------:|--------:|----------:|:------------------
|           28,328.86 |           35,299.68 |    0.8% |      0.01 | `arrow_compute`
|            8,873.48 |          112,695.35 |    0.5% |      0.01 | `arrow_raw`

End to end:
 |               ns/op |                op/s |    err% |     total | Benchmarking simple feature
|--------------------:|--------------------:|--------:|----------:|:----------------------------
|          477,005.00 |            2,096.41 |    2.4% |      0.01 | `arrow_compute`
|           94,738.54 |           10,555.37 |    0.9% |      0.01 | `arrow_raw`

A bit better but only tiny difference overall.

**Comment by save-buffer** [comment]
Hi @js8544, the current kernels subsystem in Arrow currently struggles from having too many random small memory allocations, so this isn't very surprising at all. 
Profiling your benchmark seems to provide more support for this - there's a lot more allocation/freeing going on besides just allocating the output (such as allocating std::vectors, incrementing/decrementing the refcount on the Scalar, etc.). I wrote a document about fixing this system a while back, and I hope to get to implementing it soon.

**Comment by drin** [comment]
@js8544 , did you compile in release mode? I finished writing versions that use the benchmarking library in Arrow, but I see very different results for `GreaterEqual`. I am wondering if it's a system difference or a build difference, before I check out the other benchmarks.

I am not sure if I am just missing something obvious, so I posted my code and results in a gist:
https://gist.github.com/drin/8dfa8ee631ef17b63dca5c2348f20d3c#file-bench_results-txt

oh, I just remembered this is off of master branch, so I guess I should double check with 9.0.0 too (I would think there would be minimal difference, but let's see).

Once we figure out this discrepancy, I can follow up. From what @save-buffer said, it may be a matter of following the appropriate JIRAs or creating a new one if necessary.

**Comment by drin** [comment]
I modified my version of `ArrayGreaterThan` (which is very very similar to your version of `GreaterEqual`) to create a `FastArrayGreaterThan` benchmark (I just realized that they should all be "GreaterEqual" instead of "GreaterThan", sorry).

In this version of the benchmark (https://gist.github.com/drin/8dfa8ee631ef17b63dca5c2348f20d3c#file-fast_compute_greater_equal_benchmark-cc), I looked at the implementation of the "greater_equal" function, and I compute the values in batches. It's just an approximation due to effort, but as you can see from the benchmark results the time gets much closer to `ComputeGreaterThan`. I did this to validate that I should be seeing such a fast time compared to the raw versions, and I think this validates it.

For reference, this is the implementation I was referencing to understand how "greater_equal" is implemented:
* where the function is constructed: [scalar_compare.cc#L894](https://github.com/apache/arrow/blob/master/cpp/src/arrow/compute/kernels/scalar_compare.cc#L894)
* where the kernel is registered for numeric inputs: [scalar_compare.cc#L396](https://github.com/apache/arrow/blob/master/cpp/src/arrow/compute/kernels/scalar_compare.cc#L396)
* where the kernel is being constructed (for <array, scalar> inputs), I think: [scalar_compare.cc#L322](https://github.com/apache/arrow/blob/master/cpp/src/arrow/compute/kernels/scalar_compare.cc#L322)
* The actual kernel implementation: [scalar_compare.cc#L190](https://github.com/apache/arrow/blob/master/cpp/src/arrow/compute/kernels/scalar_compare.cc#L190)

I would be interested to see if this type of implementation is faster for you or not. I am vaguely wondering if there's some SIMD things happening, as my SIMD level is configured as follows (according to the CMake output when I first build):
```bash
--   ARROW_SIMD_LEVEL=NEON [default=NONE|SSE4_2|AVX2|AVX512|NEON|DEFAULT]
--       Compile-time SIMD optimization level
--   ARROW_RUNTIME_SIMD_LEVEL=MAX [default=NONE|SSE4_2|AVX2|AVX512|MAX]
--       Max runtime SIMD optimization level
```

Let me know if this is helpful for you at all!

**Comment by drin** [comment]
also, I did verify that the numbers are very similar for 9.0.0 and my performance for `FastArrayGreaterThan` is using 9.0.0

**Comment by js8544** [comment]
@drin Thanks for your reply. I checked my compilation setup and discovered that I somehow compiled arrow without any optimization.

**Comment by js8544** [comment]
@drin Thanks for your reply. I checked my compilation setup and discovered that I somehow compiled arrow with no optimization at all, i.e. O0.  I changed the following options and rerun my benchmark:

**Comment by js8544** [comment]
@drin Thanks for your reply! I checked my compilation setup and discovered that I somehow compiled arrow with no optimization, i.e. "O0". I made some changes to my build process and rerun the benchmarks.

1. Add "O2" optimization flag
2. Add ARROW_SIMD_LEVEL=AVX2 and ARROW_RUNTIME_SIMD_LEVEL=MAX (AVX2 is the best our machines support)
3. According to @save-buffer, memory allocation cost is high for arrow::compute. So I switch to `jemalloc` for memory allocation.

The new result is satisfying. `compute` is basically the same as `raw` with a small batch size, and performs much better as the batch size increases.

Batch size 25:
|               ns/op |                op/s |    err% |     total | Benchmarking simple feature 25
|--------------------:|--------------------:|--------:|----------:|:-------------------------------
|           11,712.29 |           85,380.39 |    0.4% |      0.02 | `arrow_compute`
|            9,616.53 |          103,987.66 |    0.9% |      0.01 | `arrow_raw`

Batch size 50:
|               ns/op |                op/s |    err% |     total | Benchmarking simple feature 50
|--------------------:|--------------------:|--------:|----------:|:-------------------------------
|           11,755.04 |           85,069.87 |    0.5% |      0.02 | `arrow_compute`
|           11,417.35 |           87,586.02 |    0.3% |      0.01 | `arrow_raw`

Batch size 100:
|               ns/op |                op/s |    err% |     total | Benchmarking simple feature 100
|--------------------:|--------------------:|--------:|----------:|:--------------------------------
|           11,930.63 |           83,817.85 |    1.1% |      0.02 | `arrow_compute`
|           15,189.21 |           65,836.21 |    0.7% |      0.02 | `arrow_raw`

Batch size 1000:
|               ns/op |                op/s |    err% |     total | Benchmarking simple feature 1000
|--------------------:|--------------------:|--------:|----------:|:---------------------------------
|           27,932.44 |           35,800.67 |    0.5% |      0.04 | `arrow_compute`
|           73,840.01 |           13,542.79 |    0.2% |      0.09 | `arrow_raw`

Since the result now is expected. I will close this issue. Thanks @drin @save-buffer for your help!

**Comment by drin** [comment]
awesome! thanks for the extra info, too 🥇
