### ISSUE TITLE
From Spark-Scala it is not possile to read a parquet file created with pyarrow 

### ISSUE THREAD

**Issue by romulogoncalves** [apache/arrow#1470]
I was able to create a Parquet file like this:
``
import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

table = pa.Table.from_pandas(dataset)
fs  = pa.hdfs.connect(host, port, username, driver='libhdfs')
with fs.open('test.parquet', "wb") as fw:
    pq.write_table(table, fw)
```

The table has the following schema:
```
table.schema
intensity: uint16
raw_classification: uint8
x: int32
y: int32
z: int32
__index_level_0__: int64
...
```

When we try to read the Parquet file in Spark-Scala we get the following issue:
org.apache.spark.sql.AnalysisException: Parquet type not supported: INT32 (UINT_16);

Should this Parquet file be readable from different languages? Or do I need to take care its serialization from Python to Scala?

**Comment by xhochy** [comment]
This table is readable with other Parquet readers. The problem here is that Spark does not support these integer columns in their schema conversion:

https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetSchemaConverter.scala#L139

Thus if you want to open this data in Spark, you need to convert the columns that currently have an unsigned integer as type to being an INT32 column.

**Comment by wesm** [comment]
This is quite annoying. This seems like something we would want to handle in the `flavor='spark'` compatibility mode

**Comment by xhochy** [comment]
Opened https://issues.apache.org/jira/browse/ARROW-1988

**Comment by wesm** [comment]
Closing in favor of the JIRA
