### ISSUE TITLE
[C++] Remove internal GroupBy implementation

### ISSUE THREAD

**Issue by westonpace** [apache/arrow#14866]
### Describe the enhancement requested

Currently there are two ways to compute a group by.  The supported way is to use an aggregate node in an exec plan.  The second (internal) way is to use the internal function `arrow::internal::GroupBy`.  This internal function simulates, but does not actually use, an aggregate node.

The internal implementation has caused issues in the past where we did not notice an error in the aggregate node's invocation of aggregate kernels since we use the internal function for testing aggregates and it behaves slightly differently.  The internal implementation also requires maintenance and significantly complicated #14352 .

I would like to remove the internal implementation.  Unfortunately, the internal implementation is used by tests, benchmarks, and pyarrow.  However, we should be able to update those bindings to a friendly wrapper around exec plans.

### Component(s)

C++

**Comment by coady** [comment]
I think the [current `_group_by` interface](https://github.com/apache/arrow/blob/b056e07b8aefe73a26239da481d92a8562c41833/python/pyarrow/_compute.pyx#L2249) is awkward, because it requires target "names", which are only used for function arity. But it looks like #14867 will replace that anyway.

Also, I've been using `_group_by` for aggregating batches, with out-of-core data. Whereas #14867 looks like it will require a table. Just something to consider, but I guess I could always wrap a single record batch into a table.

Thanks.

**Comment by westonpace** [comment]
Yes, wrapping a single batch in a table should be effective.
