### ISSUE TITLE
Rename arrow table column name in Arrow javascript

### ISSUE THREAD

**Issue by royassis** [apache/arrow#15039]
### Describe the usage question you have. Please include as many useful details as  possible.

Hey there

I'm trying to rename a column name in an Arrow table using JS. is this possible ?

Best,
Roy A

### Component(s)

JavaScript

**Comment by bmschmidt** [comment]
I don't think so. In general Arrow libraries generally support not mutating an existing table, but instead creating a new one with alterations that reuse the existing memory. When I need to do things like this in Arrow JS I just iterate through the values at `table.schema.fields`, and then populate an object with the values. That loses potential things like schema metadata, though.

**Comment by royassis** [comment]
Hey @bmschmidt thanks for the response. 

Can you add a code snippet for what you mentioned ? 
+
So what about adding a feature for renaming columns and returning a new object, and not mutating the old one?

Best,
Roy

**Comment by bmschmidt** [comment]
Yeah here's a snippet for how I do it--there may be a slightly faster way.

In terms of feature adds--my sense is that goal of the ArrowJS committers (there are just three) is to make sure the library is highly performant and let outside libraries handle both computation and API simplification. For instance, you can manage an arrow table using [arquero](https://uwdata.github.io/arquero/) and use [its `rename` verb](https://uwdata.github.io/arquero/api/verbs#rename) without incurring a significant performance hit aside from loading the arquero code itself, since arquero will do the same vector-copying as below.

```js
  const tb = arrow.tableFromJSON([
    { foo: 1, bar: "fizz" },
    { foo: 2, bar: "wuzz" },
    { foo: 3, bar: "nozz" }
  ]);

  const newtb = {};
  for (let field of tb.schema.fields) {
    newtb[field.name] = tb.getChild(field.name);
  }
  newtb["newname"] = newtb["foo"];
  delete newtb["foo"];
  return new arrow.Table(newtb);
```

**Comment by royassis** [comment]
Thanks @bmschmidt appreciate it.
