### ISSUE TITLE
Cannot coerce_timestamps when writing parquet with pyarrow

### ISSUE THREAD

**Issue by smuhit** [apache/arrow#1920]
When trying to take a pandas dataframe and save a parquet file, forcing a timestamp coercion throws an error:

```python
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
from io import BytesIO
... # Creating a pandas dataframe with timestamps
b = BytesIO() 
table = pa.Table.from_pandas(df)  # df is the dataframe in question
pq.write_table(table, b, coerce_timestamps='ms') 
...
```

That throws the following error message and the script errors out:
```
pyarrow.lib.ArrowInvalid: Casting from timestamp[ns] to timestamp[ms] would lose data: 1455310458115534000
```

Is there a way to suppress this error message as a warning instead of failing out?

Using pyarrow version 0.9.0.post1, python version 3.6.2 and pandas version 0.22.0.

**Comment by xhochy** [comment]
Parquet has a nanosecond timestamp type that is discouraged to use for future projects which you can also enable to use when writing Parquet files using `pyarrow`, see https://arrow.apache.org/docs/python/generated/pyarrow.parquet.write_table.html. 

```python
pq.write_table(table, b, use_deprecated_int96_timestamps=True) 
```

Alternatively, if you're happy with millisecond precision, just round your Pandas column so that the timestamp is a multiple of a million (1million ns = 1ms ;) ).

**Comment by xhochy** [comment]
I have created a ticket in JIRA to track this https://issues.apache.org/jira/browse/ARROW-2555 Closing this issue here, please subscribe on JIRA if you want to have updates or implement it.

**Comment by PMende** [comment]
I am encountering this issue without ever explicitly creating a pandas `DataFrame` myself. It seems that when trying to use `pyarrow.parquet.write_to_dataset`, if one specifies an argument for `partition_cols`, pyarrow (for whatever reason) creates a `pandas.DataFrame` object for each partition, then converts that `DataFrame` back to a `pyarrow.Table` (see [source code](https://github.com/apache/arrow/blob/master/python/pyarrow/parquet.py#L1137)). Why it does this, I have no idea.

One consequence of this design decision, however, is that trying to write tables that have columns of type `date32[day]` not part of the partition columns, writing will often fail. I presume that the reason it fails is because of floating-point precision issues going back and forth between pandas and pyarrow (i.e., from `date32[day]` -> `datetime64[ns]` when creating each partition of the table in pandas, then from `datetime64[ns]` -> `date32[day]` when going back to pyarrow).

**Comment by wesm** [comment]
Can you please post your comment on JIRA? Thanks

**Comment by davidboles** [comment]
I'm adding this because the cumulative online discussion is misleading. Parquet has deprecated support for nanoseconds with the INT96 encoding (32-bit Julian day, 64-bit nanoseconds since midnight). Parquet 2.x now has support for nanosecond annotated INT64 timestamps, and Arrow supports this as well (at least mostly). However, Pyarrow does not yet support Parquet 2.x format files fully.

Net of net - 64-bit nanosecond support is coming, probably in a quarter or three (just a guess).

**Comment by fdegier** [comment]
> There is now `allow_truncated_timestamps=True` to suppress that error

Thanks this solved it for me.

**Comment by sharpe5** [comment]
See: https://stackoverflow.com/questions/59682833/pyarrow-lib-arrowinvalid-casting-from-timestampns-to-timestampms-would-los/72111737#72111737

**Comment by sdebruyn** [comment]
What about the same issue when reading? I have a source that provides parquet files with INT96 timestamps with ms precision. I can read this in arrow by adding `coerce_int96_timestamp_unit="ms"`. But then it goes wrong when converting to pandas. I get the same exception as above.
