### ISSUE TITLE
[C++] Bump version of bundled AWS SDK

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#20272]
The latest version on the 1.8 line is 1.8.186.
We could also try to switch to the 1.9 line, but there were blocking issues last time we tried.

Note we should bump the dependent AWS library versions at the same time.

**Reporter**: [Antoine Pitrou](https://issues.apache.org/jira/browse/ARROW-16727) / @pitrou

<sub>**Note**: *This issue was originally created as [ARROW-16727](https://issues.apache.org/jira/browse/ARROW-16727). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by raulcd** [comment]
@pitrou should the 1.9 AWS SDK version be possible now? From my understanding our conda forge recipes use:
```
aws_sdk_cpp:
- 1.9.379
```

**Comment by pitrou** [comment]
Yes, it should be. Unfortunately, it might require bumping all AWS-related dependencies, or perhaps even adding some of them. cc @kou

**Comment by kou** [comment]
I can't work on this right now but I can help a person who wants to work on this.

**Comment by pitrou** [comment]
@js8544 Certainly not. It's more a matter of finding out (or discovering) what has or has not changed in the AWS SDK build procedures between 1.8.x and 1.9.x.

@h-vetinari Might know a bit about that?

**Comment by js8544** [comment]
> Certainly not. It's more a matter of finding out (or discovering) what has or has not changed in the AWS SDK build procedures between 1.8.x and 1.9.x.

Okay. I'll try to work on this. I noticed that aws sdk cpp has published version 1.10(https://github.com/aws/aws-sdk-cpp#version-110-is-now-available). Do we want to update to 1.10 or 1.9?

**Comment by pitrou** [comment]
If 1.10 works then let's go for it.

**Comment by js8544** [comment]
take

**Comment by h-vetinari** [comment]
> Yes, it should be. Unfortunately, it might require bumping all AWS-related dependencies, or perhaps even adding some of them. cc @kou

AFAIU, the aws-sdk-cpp bundles everything you need (for AWS), I don't think anything else depends on it.



> @js8544 Certainly not. It's more a matter of finding out (or discovering) what has or has not changed in the AWS SDK build procedures between 1.8.x and 1.9.x.

Biggest (only?) issue that blocked upgrading to 1.9 was https://issues.apache.org/jira/browse/ARROW-15141 due to https://github.com/aws/aws-sdk-cpp/issues/1809. That has been fixed through https://github.com/awslabs/aws-c-io/pull/515, and once we had a 1.9 build with that (conda-forge unbundles the sdk into separate parts, so it's a bit of a different situation), we were able to [bump](https://github.com/conda-forge/arrow-cpp-feedstock/issues/918) to 1.9.

I have been [thinking](https://github.com/conda-forge/aws-sdk-cpp-feedstock/issues/662) about bumping the conda-forge feedstock to 1.10, but we haven't actually done that yet, and there's been a couple [changes](https://github.com/aws/aws-sdk-cpp#version-110-is-now-available) being advertised in the upstream readme. I think we'd have to test whether this works.

The good thing is that the arrow CI also contains a working simile of the conda-feedstock CI, and it would be easy to test this for whatever PR is in the works by replacing the version pins in the CI yaml files [here](https://github.com/apache/arrow/tree/master/dev/tasks/conda-recipes/.ci_support).
