### ISSUE TITLE
[C++] Allow FieldPath to work with ListElement

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#20489]
`FieldRef::FromDotPath` can parse a single list element field. ie. `{}'path.to.list[0]`{`}but does not work in practice. Failing with:

_struct_field: cannot subscript field of type list<....>_

Being able to add a slice or multiple list elements is not within the scope of this issue. 

**Reporter**: [Miles Granger](https://issues.apache.org/jira/browse/ARROW-18265) / @milesgranger
**Assignee**: [Miles Granger](https://issues.apache.org/jira/browse/ARROW-18265) / @milesgranger
#### PRs and other links:
- [GitHub Pull Request #14697](https://github.com/apache/arrow/pull/14697)

<sub>**Note**: *This issue was originally created as [ARROW-18265](https://issues.apache.org/jira/browse/ARROW-18265). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by bkietz** [comment]
`FieldPath::Get(list_array)` would return the child data for the list array, IE the undelimited list values. This is disallowed in scalar expressions because it results in a column whose length is entirely unrelated to the lengths of sibling columns. Consider projecting `.s, .l[0]` from `Table.from_pydict({"s": ["a", "b"], "l": [[1,2,3], [4,5,6]]})`; we can't do that just as we can't do `Table.from_pydict({".s": ["a", "b"], ".l[0]": [1,2,3,4,5,6]})`. It might be desirable to let pyarrow's field reference mechanism be more flexible (as in substrait) and implicitly replace a path like `.l[0:1]` with a call to `list_slice` or similar. However that should be a python API decision and should not propagate to the C++ library, where it's important that using FieldPath::Get be consistently performant
