### ISSUE TITLE
[pyarrow] additional pickling types only present in mac distribution

### ISSUE THREAD

**Issue by tat2133** [apache/arrow#2260]
On 3/22, [this commit](https://github.com/apache/arrow/commit/29268ec5a0a10da639d0dd5684bc57fcd1c8f7e3) was merged as a fix for [this issue](https://issues.apache.org/jira/browse/ARROW-2342) to be included in 0.10.0. However, it's present in the 0.9.0.post1 mac-only distribution from April 6th (potentially along with all of the other commits to master between when 0.9.0 got tagged on 3/16 and when 0.9.0.post1 got released on 4/6), so code written on a mac might not be portable to other environments.

Will this discrepancy be resolved any time soon or do we just have to wait until all of the commits that were accidentally included in 0.9.0.post1 are formally released in 0.10.0?

**Comment by wesm** [comment]
Sorry about this. We're about ~3 weeks away from the 0.10.0 release I would estimate, so waiting for that is probably best. Could you tell us more about how you're using pickle (we haven't invested much energy in the pickle code paths since many applications use Arrow's native serialization)?

**Comment by tat2133** [comment]
Sure. My team uses parquet files stored in S3 for archival purposes and as an intermediate storage format for loading data into our data warehouse. I was trying to parallelize a function that converts a chunk of data from our db into a pyarrow table (given the raw data, a pyarrow schema, and an s3 path as parameters) and then uploads it to S3. I wanted to use the multiprocessing library (specifically pool.imap) to do this, which is when I ran into the above issue b/c of the ForkingPickler.

We just started using parquet files/pyarrow fairly recently, so definitely let me know if there's a smarter way to go about doing this.

**Comment by wesm** [comment]
@tat2133 I see. I don't think there's anything we can really do for you to fix this. 

If you build your own Linux wheels https://github.com/apache/arrow/tree/master/python/manylinux1 then I think the pickles produced by those wheels should be readable by the latest macOS version that's in PyPI.

I hope we can get the pickle protocol improved and reasonably stabilized (using the binary IPC protocol instead of whatever it's doing now) so these issues will be less common in the future.
