### ISSUE TITLE
[JS] decimal toString does not support negative values

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#22932]
The main description is here: <https://github.com/apache/arrow/issues/5397>

Also, I have a simple test case (slightly changed generate-test-data.js and generated-data-validators):
```java

export const decimal = (length = 2, nullCount = length * 0.2 | 0, scale = 0, precision = 38) => vectorGenerator.visit(new Decimal(scale, precision), length, nullCount);

function fillDecimal(length: number) {
    // const BPE = Uint32Array.BYTES_PER_ELEMENT; // 4
    const array = new Uint32Array(length);
    // const max = (2 ** (8 * BPE)) - 1;
    // for (let i = -1; ++i < length; array[i] = rand() * max * (rand() > 0.5 ? -1 : 1));
    array[0] = 0;
    array[1] = 1286889712;
    array[2] = 2218195178;
    array[3] = 4282345521;
    array[4] = 0;
    array[5] = 16004768;
    array[6] = 3587851993;
    array[7] = 126217744;
    return array;
}
```
and the expected value should be
```java

expect(vector.get(0).toString()).toBe('-1000000000000000000000000000000000000');
expect(vector.get(1).toString()).toBe('1000000000000000000000000000000000000');
```
However, the actual first value is 339282366920938463463374607431768211456 which is wrong! The second value is correct by the way.

I believe the bug is in the function called 

function decimalToString<T extends BN<BigNumArray>>(a: T) because it cannot return a negative value at all.

[arrow/js/src/util/bn.ts](https://github.com/apache/arrow/blob/d54425de19b7dbb2764a40355d76d1c785cf64ec/js/src/util/bn.ts#L99)

Line 99 

**Reporter**: [Andong Zhan](https://issues.apache.org/jira/browse/ARROW-6575)
#### Related issues:
- [[JS] decimalToString function in bn.ts does not handle negative decimals](https://github.com/apache/arrow/issues/22980) (is duplicated by)

<sub>**Note**: *This issue was originally created as [ARROW-6575](https://issues.apache.org/jira/browse/ARROW-6575). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jonathanswenson** [comment]
I'm interested in helping integrate a correct decimal -> string implementation. 

I'm using the current bignum -> string implementation here from bn.ts 

https://github.com/apache/arrow/blob/a2881a124339d7d50088c5b9778c725316a7003e/js/src/util/bn.ts#L106-L123

But wrapping the implementation with some extra steps. 
+ detect if the bigint is negative 
+ flip the decimal
+ render the flipped decimal as a bigint (using [this implementation](https://github.com/apache/arrow/blob/a2881a124339d7d50088c5b9778c725316a7003e/js/src/util/bn.ts#L106-L123))
+ add scale (place the decimal point in the correct location)
+ add a `-` if we flipped the decimal. 

Implementation of the negative check (I haven't verified it works with decimal 256)
based on [c++ implementation](https://github.com/apache/arrow/blob/39bad544/cpp/src/arrow/util/basic_decimal.h#L125)
```
// check if the stored bigint is negative.
// based on implementation here from arrow:
// https://github.com/apache/arrow/blob/39bad544/cpp/src/arrow/util/basic_decimal.h#L125
// TODO will just using array.length - 1 work for 128 and  256bit decimals?
const highOrderWord = new Int32Array([array[array.length - 1]])[0]
return highOrderWord >= 0
```

Implementation to flip the bigint to the equivalent "negative" value
based on [c++ implementation](https://github.com/apache/arrow/blob/39bad544/cpp/src/arrow/util/basic_decimal.cc#L1144)
```
// based on implementation here from arrow:
// https://github.com/apache/arrow/blob/39bad544/cpp/src/arrow/util/basic_decimal.cc#L1144
// idea is to flip the bits to take the 2's complement of the number to get the negative representation of the
// 128 (or theoretically 256) bit integer.
let carry = 1
for (let i = 0; i < array.length; i++) {
  const elem = array[i]
  const updated = ~elem + carry
  array.set([updated], i)
  carry &= elem === 0 ? 1 : 0
}
```

I don't quite have an efficient, strictly correct implementation of the decimal placement, but I think it shouldn't be too difficult to do correctly.

I'm currently stripping off additional trailing zeros (just the way that we want to render these decimals) so `0.0001000` with scale of 7 => `0.0001` technically a scale of 4

It likely requires some changes to the the way that types are being dealt with (because a decimal is really just a bignum with a scale) but we'll need that scale to correctly do the render. Haven't spent too much time studying the decimalToString implementation, but I bet that with the scale the rendering of the value with the decimal point could be done in a single pass without needing to compose / concat / join extra string values.

**Comment by aljazerzen** [comment]
@jonathanswenson Nice writeup. Are you working on this, or should I pick it up where you left of?

**Comment by jonathanswenson** [comment]
I haven’t started implementing yet, feel free to grab it.
