### ISSUE TITLE
[Python] Array.to_numpy() with type fixed_size_list(int64(), 1) doesn't roundtrip for large integer values

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#26199]
Reproducer:

```python

data = [None, [9007199254740993]]
arr = pa.array(data, type=pa.list_(pa.uint64(), 1))
ndarray = arr.to_numpy(zero_copy_only=False)
restored = pa.array(ndarray, type=arr.type)
assert restored.equals(arr)
```

Error:

```Java

E       assert False
E        +  where False = <built-in method equals of pyarrow.lib.FixedSizeListArray object at 0x7fbdb0239e20>(<pyarrow.lib.FixedSizeListArray object at 0x7fbdb0262220>\n[\n  null,\n  [\n    9007199254740993\n  ]\n])
E        +    where <built-in method equals of pyarrow.lib.FixedSizeListArray object at 0x7fbdb0239e20> = <pyarrow.lib.FixedSizeListArray object at 0x7fbdb0239e20>\n[\n  null,\n  [\n    9007199254740992\n  ]\n].equals
```

The inner numpy array (`ndarray[1]`) has float64 dtype where the integer gets truncated because of the precision.

**Reporter**: [Krisztian Szucs](https://issues.apache.org/jira/browse/ARROW-10194) / @kszucs

<sub>**Note**: *This issue was originally created as [ARROW-10194](https://issues.apache.org/jira/browse/ARROW-10194). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
I am not sure we can do anything about this, since this is an inherent limitation of numpy not having missing value support for integers, and so that we have to use float64 to represent those. The same happens for primitive, non-nested arrays as well:

```python
data = [None, 9007199254740993]
arr = pa.array(data, type=pa.uint64())
ndarray = arr.to_numpy(zero_copy_only=False)

>>> arr
<pyarrow.lib.UInt64Array object at 0x7fa6efe29400>
[
  null,
  9007199254740993
]
>>> ndarray
array([           nan, 9.00719925e+15])
```

One difference, though, is that when trying to recreate, we raise an error instead of silently roundtripping a different value:

```python
>>> restored = pa.array(ndarray, type=arr.type)
...
ArrowInvalid: Float value nan was truncated converting to uint64
```

That's related to the fact that we don't do safe casting when converting nested data, which is discussed in https://github.com/apache/arrow/issues/31857. 

Will add this issue as an extra example there, and then we can close this.
