### ISSUE TITLE
[MATLAB] Create arrow.Array class

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#27758]
Create arrow.Array, an abstract MATLAB class which represents arrow memory. Users can create an arrow.Array from MATLAB arrays. Concrete subclasses, such as arrow.UInt64Array or arrow.Float64Array, will allow the user to create specific array types. The design mirrors APIs of other language bindings in the Arrow project. 

More details about the MATLAB Interface for Apache Arrow can be found here: https://github.com/mathworks/arrow/blob/ARROW-11795/matlab/doc/matlab_interface_for_apache_arrow_design.md

**Reporter**: [Fiona La](https://issues.apache.org/jira/browse/ARROW-11919) / @lafiona
#### Subtasks:
- [x] #37205
- [x] #37206
- [x] [Add abstract function for null information](https://github.com/apache/arrow/issues/28145)
- [x] [Add subclass: arrow.UInt64Array m-code](https://github.com/apache/arrow/issues/28146)

<sub>**Note**: *This issue was originally created as [ARROW-11919](https://issues.apache.org/jira/browse/ARROW-11919). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by kevingurney** [comment]
Marking this as resolved.

An abstract `arrow.array.Array` base class was added in #35491.

Adding an architecture diagram (#28147) was initially included as a "sub-task" for this issue in Jira. We should still add architecture diagrams for the MATLAB Interface, but we can track that separately so that we can close out this old issue (which is effectively complete because the base `arrow.array.Array` class has been added).

I've removed #28147 from the list of sub-tasks in the description of this issue.
