### ISSUE TITLE
[MATLAB] Implement LifetimeManager for managing arrow memory lifetime

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#28494]
When we create an arrow object in MATLAB (e.g. arrow.Array) we need to ensure the underlying arrow C++ data structures stay alive for the duration of the wrapping MATLAB object's lifetime.

**Reporter**: [Sarah Gilmore](https://issues.apache.org/jira/browse/ARROW-12752) / @sgilmore10
#### Subtasks:
- [ ] [[MATLAB] Create a templated ObjectMap for storing arrow C++ data structures with IDs](https://github.com/apache/arrow/issues/28495)
- [ ] [[MATLAB] Create the LifetimeManager C++ class](https://github.com/apache/arrow/issues/28496)

<sub>**Note**: *This issue was originally created as [ARROW-12752](https://issues.apache.org/jira/browse/ARROW-12752). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by kevingurney** [comment]
Marking this as resolved.

Functionality that is related to what is described in this issue was implemented in [mathworks/libmexclass](https://github.com/mathworks/libmexclass), which is now being used under the hood by the MATLAB Interface.

Specifically the [`ProxyManager` class](https://github.com/mathworks/libmexclass/blob/d04f88d2a6f6dcf65d595183eda03c4b66b2961f/libmexclass/cpp/source/include/libmexclass/proxy/ProxyManager.h#L22) in `libmexclass` manages the lifetime of underlying Arrow C++ data structures indirectly by managing `Proxy` instances.
