### ISSUE TITLE
[MATLAB] Reduce MATLAB CI Build Time by Building Arrow C++ Libraries separately and using Packaged GoogleTest

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#29285]
As part of ARROW-13202, we investigated approaches for reducing the build time of MATLAB Interface CI jobs. Right now we build and run the the Arrow C++ tests as part of the MATLAB Interface build in order to make use of the bundled GoogleTest binaries.

It may help to reduce overall build times if we instead build just the minimal Arrow C++ libraries (without the C++ tests) and install GoogleTest on the GitHub Actions Runner using apt-get.

**Reporter**: [Kevin Gurney](https://issues.apache.org/jira/browse/ARROW-13647) / @kevingurney

<sub>**Note**: *This issue was originally created as [ARROW-13647](https://issues.apache.org/jira/browse/ARROW-13647). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by kevingurney** [comment]
`GoogleTest` support was removed from the CMake build system for the MATLAB interface in #37784. We are now no longer building the Arrow C++ tests in order to access the bundled `GoogleTest` binaries.

This appears to have reduced the time for the MATLAB CI workflows. So, I think this issue is no longer relevant.

Closing.
