### ISSUE TITLE
[C++][FlightRPC] Fix linking of Flight/gRPC example on MacOS

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32584]
`flight_grpc_example` uses `--no-as-needed` but this doesn't work on MacOS.

**Reporter**: [David Li](https://issues.apache.org/jira/browse/ARROW-17307) / @lidavidm

<sub>**Note**: *This issue was originally created as [ARROW-17307](https://issues.apache.org/jira/browse/ARROW-17307). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by amoeba** [comment]
Hi @lidavidm, I think this is no longer an issue since https://github.com/apache/arrow/pull/14077 was merged. This example builds and runs successfully on my macOS laptop and the relevant section in the examples CMakeLists.txt looks correct. Can you close if so or let me know if there's more work to be done?

**Comment by lidavidm** [comment]
I'm not sure since I wasn't the original reporter. If it's fixed for you, let's close it.
