### ISSUE TITLE
[C++] Move rank implementation into separate module

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#33560]
The rank kernel implementations are currently in `vector_sort.cc`, amongst other things.
To make the code more readable and faster to compiler, we should move them into their own file.

**Reporter**: [Antoine Pitrou](https://issues.apache.org/jira/browse/ARROW-18396) / @pitrou

<sub>**Note**: *This issue was originally created as [ARROW-18396](https://issues.apache.org/jira/browse/ARROW-18396). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by chrisjordansquire** [comment]
@pitrou / @benibus  -- It looks like this issue was taken care of as part of https://github.com/apache/arrow/pull/14753, which also resolved #33559. Is that correct? If so can this be closed, and if not can more information be added? As of right now it appears to me that the ranking kernel is in the vector_rank.cc file, but I'm very new to this codebase.

**Comment by pitrou** [comment]
@chrisjordansquire Oh, yes, you're right. Thanks for noticing!
