### ISSUE TITLE
[Python] support quantile for temporal dtypes

### ISSUE THREAD

**Issue by jbrockmendel** [apache/arrow#33769]
### Describe the bug, including details regarding any error messages, version, and platform.

cc @jorisvandenbossche 

For some methods (e.g., dictionary_encode xref #15226, mode, min_max) it is straightforward to cast to integer, compute, then cast back.  For quantile I've found doing this breaks a bunch of pandas tests (or more accurately, fails to fix existing xfails).  I speculate that this has to do with lossiness in int->float->int conversions.

### Component(s)

Python

**Comment by jorisvandenbossche** [comment]
I think also for that reason (quantile by default always returns floats), we might not want to add support for quantile to temporal types (not sure if we actually ever considered this). 

There are interpolation methods (lowest, highest, nearest) that do preserve the input type, though. So maybe we could only allow those?

But on your point of not matching pandas behaviour if you do the casting manually. I am not sure having this kernel in pyarrow would make any difference for that, since arrow would basically do the same under the hood and calculate the interpolated value based on the underlying integers.

**Comment by jbrockmendel** [comment]
confirmed that the numpy-backed versions have identical floating point errors.  closing.
