### ISSUE TITLE
[C++] Bump version of bundled boost to 1.81.0

### ISSUE THREAD

**Issue by nealrichardson** [apache/arrow#33851]
### Describe the enhancement requested

In addition to bumping the version in versions.txt, we need to update our trimmed version that we host (90% smaller than the full boost). See `cpp/build-support/trim-boost.sh`. Edit `BOOST_VERSION` and/or provide on the command line. Then upload the bundle to artifactory (see https://issues.apache.org/jira/browse/ARROW-14336). 

While you're in there, you should edit the comment about uploading to https://github.com/ursa-labs/thirdparty/releases/edit/latest, which we've switched off of. (It also appears in versions.txt but isn't used anywhere else anymore.) 

May also need to edit `Boost_ADDITIONAL_VERSIONS` in ThirdpartyToolchain.cmake. Check for other places in that file too.

### Component(s)

C++

**Comment by kou** [comment]
Could you use https://apache.jfrog.io/artifactory/arrow/thirdparty/ instead of  https://github.com/ursa-labs/thirdparty/releases/edit/latest ?
We're using https://apache.jfrog.io/artifactory/arrow/thirdparty/ for mirror URL: https://github.com/apache/arrow/blob/master/cpp/cmake_modules/ThirdpartyToolchain.cmake#L424

All Apache Arrow committers/PMC members can upload a file to https://apache.jfrog.io/artifactory/arrow/thirdparty/ from https://apache.jfrog.io/ui/repos/tree/General/arrow/thirdparty with their ASF account.

**Comment by nealrichardson** [comment]
Agree @kou, part of this task should be to remove any vestigial references to the old ursalabs repo
