### ISSUE TITLE
[Packaging] Installation of "libarrow-flight-dev" package fails on Debian/Ubuntu arm64 platform

### ISSUE THREAD

**Issue by prmoore77** [apache/arrow#33934]
### Describe the bug, including details regarding any error messages, version, and platform.

When attempting to install package: libarrow-flight-dev in a container running Docker image: ubuntu:latest on the **linux/arm64** platform - it fails with error:

```
The following packages have unmet dependencies:
 libarrow-flight-dev : Depends: libarrow-dev (= 9.0.0-1) but 11.0.0-1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

To reproduce the issue - I run these commands on my M1 (arm64) MacBook Pro from a terminal:
```
docker run -it --entrypoint /bin/bash --platform linux/arm64 ubuntu:latest

# Then in the container - run:
apt update && \
apt install -y -V ca-certificates sudo wget lsb-release && \
wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb && \
apt install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb && \
apt update && \
apt install -y -V libarrow-flight-dev
```

If I run with the **linux/amd64** platform - however - the script above works just fine.

I hit this issue when attempting to build an arm64 Docker container (trying to follow instructions here: https://arrow.apache.org/install/)

Thank you!

### Component(s)

Packaging

**Comment by kou** [comment]
`libarrow-flight-dev` isn't available for arm64 because we don't have enough CI resource (Travis CI) to build `libarrow-flight-dev` for arm64.

**Comment by raulcd** [comment]
I missed the original PR where we removed that, posting for reference: https://github.com/apache/arrow/pull/14300

@kou we have now self-hosted arm64 runners on crossbow using the same kubernetes solution as what @assignUser suggested to implement to have self-hosted arm64 runners on the main arrow repo to remove Travis. We could try and migrate those jobs to the self-hosted runners instead of Travis and re-enable `libarrow-flight` for arm64 in the future.
I already plan to work on the migration of the Travis jobs on the Arrow repo when I have some time.

**Comment by kou** [comment]
Wow! OK. Let's do it!

**Comment by raulcd** [comment]
> @raulcd @assignUser Do you know what `runs-on` should be used for self-hosted arm64 Ubuntu runners?

These are all the tags:
`self-hosted`, `arm64`, `devops-managed`, `Linux`, `arm`
I think we should use:
`runs-on: ["self-hosted", "Linux", "arm64"]`
