### ISSUE TITLE
[Release] Do not commit directly to master on post-11-bump-versions.sh

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#33931]
### Describe the enhancement requested

During the post release tasks when we bump the versions using `dev/release/post-11-bump-versions.sh` we commit and push directly to the default branch on the `apache/arrow` repository.

This is the only step in the process where one of our scripts commits and pushes directly to the main's repo default branch.

That felt strange to me, I think we could add a temporary branch on the fork and do a PR so we could at least do a quick review to validate if there's anything missing or wrong from our automated script.

Those are the commits for the 11.0.0 release where I noticed:
https://github.com/apache/arrow/compare/4acf7c17689c...d422137d8a4d

### Component(s)

Release

**Comment by raulcd** [comment]
@kou do you think this is worth it or overkill and not necessary?

**Comment by kou** [comment]
I think that the current behavior is better than creating a PR but I don't object this proposal. :-)

Here are reasons:

* We MUST not use `dev/merge_arrow_pr.py` nor the merge button to merge the PR
  * Because they use squash merge.
  * We need to merge the PR manually from command line. It may bother a release manager.
* We need to tag too
  * We can't use a PR to tag

**Comment by raulcd** [comment]
Closing this issue as the alternative seems worst.
