### ISSUE TITLE
[Format][Docs] Document primitive types in the Arrow format docs

### ISSUE THREAD

**Issue by ianmcook** [apache/arrow#33958]
### Describe the enhancement requested

It would be nice if the [Arrow columnar format docs page](https://arrow.apache.org/docs/format/Columnar.html) documented what primitive types Arrow supports. It is not great that readers need to go to [format/Schema.fbs](https://github.com/apache/arrow/blob/master/format/Schema.fbs) for that information today.

### Component(s)

Documentation, Format

**Comment by Amishakumari544** [comment]
can somebody tell me where I should add this [Schema](https://github.com/apache/arrow/blob/main/format/Schema.fbs)  in Arrow columnar page?

**Comment by westonpace** [comment]
I'll let @ianmcook answer this as I'm not actually sure what "primitive types" is referring to.  I think, when I marked this, I assumed he was talking about logical types.  Perhaps https://github.com/apache/arrow/issues/14752 would actually be a better starting point.  That issue is about replacing [this paragraph](https://arrow.apache.org/docs/format/Columnar.html#logical-types) with a brief listing of [these types](https://github.com/apache/arrow/blob/main/format/Schema.fbs#L407-L430).  For example, it is not clear in the document that Arrow supports a "boolean" type.  One must refer to the schema to figure this out.  (the document describes the physical layout, "fixed-size primitive", and the schema defines the type "Bool")

Another place we have a listing of logical types is at https://arrow.apache.org/docs/status.html#data-types .  So I think the idea is to just have a listing of data types in the "arrow columnar format" page.

**Comment by jorisvandenbossche** [comment]
I think in this context the "primitive types" and "logical types" are meaning the same (confusingly), as we currently only have a section ["Fixed-size Primitive Layout](https://arrow.apache.org/docs/format/Columnar.html#fixed-size-primitive-layout) explaining the layout of primitive types, but not which actual "logical" primitive types we have (whether the term "logical" is correct here is another question).

So essentially I think this issue is about exactly the same as https://github.com/apache/arrow/issues/14752, I think we can close this one as duplicate of https://github.com/apache/arrow/issues/14752? 
Unless we would like to list just the primitive types that follow the fixed-size primitive layout in that section, instead of listing all types (including those primitive types) in the ["Logical types" section](https://arrow.apache.org/docs/format/Columnar.html#logical-types)?

**Comment by ianmcook** [comment]
Closed as dup of #4752

**Comment by ianmcook** [comment]
Duplicate of #4752

**Comment by ianmcook** [comment]
Duplicate of 14752
