### ISSUE TITLE
[Java] JDBC driver does not send custom headers on DoGet

### ISSUE THREAD

**Issue by lidavidm** [apache/arrow#33953]
### Describe the bug, including details regarding any error messages, version, and platform.

Follow-up of #33874, specifically https://github.com/apache/arrow/issues/33874#issuecomment-1405501350

### Component(s)

Java

**Comment by aiguofer** [comment]
Ok so this one is a little bit beyond me as I'm not very familiar with gRPC but I believe the problem lies in `FlightClient.interceptedChannel`. 

The handshake and sql info methods both use `CallOptions.wrapStub(blockingStub, options).get<method>`, which internally uses the `Channel` on the stub. `getStream` however, uses the `interceptedChannel`. If I replace it with `CallOptions.wrapStub(asyncStub, options).getChannel()` it seems to send the headers along, see: [this commit](https://github.com/apache/arrow/commit/3684280b8c844242b44894cd84e670ae0cd71df1)

There's a few other methods in the `FlightClient` that use the `interceptedChannel` so those might also be worth a look. 

BTW, https://github.com/apache/arrow/issues/33839 might be the same issue based on these findings.

**Comment by aiguofer** [comment]
After looking at it, it looks like all the stubs are generated from the `interceptedChannel` so there shouldn't be any issues with doing this everywhere. Submitted a PR.
