### ISSUE TITLE
[R] Provide extra output for failed builds

### ISSUE THREAD

**Issue by thisisnic** [apache/arrow#34105]
### Describe the enhancement requested

When building the R package and the Arrow C++ library build fails, there's very little output unless the user has set `ARROW_R_DEV` to `TRUE`.  We could instead output the last N lines of the output in the case of build failures, to provide more context.

### Component(s)

R

**Comment by assignUser** [comment]
with cmake it is very possible that the error is not in the last lines due to multithreading so it might be better to grep for the actual "CMake Error:" or something? Or are we saving the log somewhere? In that case it might also be good to direct the user to the full log file. (in addition to output what ever part of the log we choose)
