### ISSUE TITLE
[Python] Control file size writing Parquet files

### ISSUE THREAD

**Issue by StuartHadfield** [apache/arrow#34264]
### Describe the usage question you have. Please include as many useful details as  possible.

Hello!

I was wondering if it was possible to control the filesize of a resultant file when writing a parquet dataset? This is naturally quite important - controlling file size of individual files is a real key part of optimising a parquet dataset.

In Dask you can use https://docs.dask.org/en/stable/generated/dask.dataframe.DataFrame.repartition.html to repartition a dataframe easily - I don't think we have anything similar in PyArrow, but I know I can get somewhere by doing:

```py
bytes_written = 0
index = 0
writer = pq.ParquetWriter(f'output_{index:03}.parquet', table.schema)

for i in range(300000):
  writer.write_table(table)
  bytes_written = bytes_written + table.nbytes
  if bytes_written >= 500000000: # 500MB, start a new file
    writer.close()
    index = index + 1
    writer = pq.ParquetWriter(f'output_{index:03}.parquet', table.schema)
    bytes_written = 0

writer.close()
```

This limits the bytes fed to the writer, which is cool - I would have to establish the compression ratio I expect - but I don't know how to achieve something similar for writing a **dataset** beyond partitioning on some column? If there's a recommended strategy for this, I'd be really appreciative if you could share!

### Component(s)

Python

**Comment by jorisvandenbossche** [comment]
Yes, the `ParquetWriter` interface is the low-level interface for writing _single_ files (and so using that you need to handle this logic manually), but the generic dataset writing functionality allows you to control file size in _some_ way and thus automatically split your dataset in multiple files. But, this is based on the number of rows written and not the resulting file size. You could still use that if you can make a rough estimate of rows for a given size.

How this would look like:

```
>>> table = pa.table({"col": range(10000)})
>>> import pyarrow.dataset as ds
>>> ds.write_dataset(table, "test_split", format="parquet", max_rows_per_file=3000, max_rows_per_group=3000)
```

```
$ ls test_split/
part-0.parquet	part-1.parquet	part-2.parquet	part-3.parquet
```

(I needed to specify `max_rows_per_group` as well, but that's just because I used a tiny example and that keyword has a default that is larger than 3000)

**Comment by StuartHadfield** [comment]
Ah, yeah, so I get that you can control rows - I was wondering if there was some way I could tell the writer "Okay once you have written `n` bytes, flush" or something.

I guess I could still make a rough inference on bytes-per-row if I know the total filesize, and the number of rows in the dataset as a whole.

**Comment by jorisvandenbossche** [comment]
Currently it's only row based indeed. See also https://github.com/apache/arrow/issues/26417 for some discussion about having a file-size based limit.

(BTW, note that the repartition by size in dask is also based on in-memory size, not written-size, AFAIK)
