### ISSUE TITLE
[Python] High RAM usage when reading parquet.

### ISSUE THREAD

**Issue by Kesanov** [apache/arrow#34274]
My parquet file is `40GB` in size. When loaded in memory, it is only `10GB` in size.

However, when reading from disk with `pyarrow.parquet.read_table`, the memory usage temporarily grows to `150GB`.
When reading from disk with `pandas.read_parquet(.., engine='pyarrow')`, the memory usage temporarily grows to `300GB`.

### Component(s)

Parquet, Python, PyArrow (11.0.0), Linux

**Comment by jorisvandenbossche** [comment]
@Kesanov it sounds unlikely that the actual size in memory is only 10GB, since typically parquet files are very well compressed and tend to be much smaller on disk (but this depends on the exact way the file was written). So the 150GB doesn't sound unexpected to me for a file of 40GB.

How did you measure the size in memory? Can you show some example code?

**Comment by Kesanov** [comment]
Yeah, I think you are right. I used `dataframe.info()`, which said the memory usage is `10G+`, which I interpreted as 10G exactly.

**Comment by westonpace** [comment]
If you have a `pyarrow.Table` (e.g. from a call to `pyarrow.parquet.read_table`) you can get a pretty precise data size with [`pyarrow.Table.nbytes`](https://arrow.apache.org/docs/python/generated/pyarrow.Table.html#pyarrow.Table.nbytes)

**Comment by jorisvandenbossche** [comment]
> I used `dataframe.info()`, which said the memory usage is `10G+`

If you have object dtype columns (for example string columns), this can be a large under-estimation. You can pass `dataframe.info(memory_usage="deep")` to get the full memory usage for the pandas.DataFrame.

This can also be more than the memory usage you see for the pyarrow.Table (using `table.nbytes` as Weston mentioned above), since for some data types (such as strings), pandas is less efficient compared to pyarrow.
