### ISSUE TITLE
[Python] PyArrow pa.array fails intermittently with custom iterable object

### ISSUE THREAD

**Issue by bdice** [apache/arrow#34944]
### Describe the bug, including details regarding any error messages, version, and platform.

- Arrow versions tested: 10.0.1 and 11.0.0, installed via conda
- Platform: Linux

I worked with @shwina recently on a problem we saw in cudf, and we identified a bug in PyArrow. The bug can be reproduced (but only intermittently) with the following snippet:

```python
import pyarrow as pa

class A:
    def __getitem__(self, key):
        return 3

pa.array(A())
```

I can run this snippet under `pdb` by inserting `breakpoint()` before `pa.array(A())` and then continuing from the breakpoint by pressing `c`. With `pdb`, I consistently get errors like:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
F20230406 15:12:07.595571 153661 inference.cc:348]  Check failed: _s.ok() Operation failed: internal::ImportDecimalType(&decimal_type_)
Bad status: Unknown error: <built-in function __import__> returned a result with an exception set. Detail: Python exception: SystemError
*** Check failure stack trace: ***
```

Without `pdb`, the error is _sometimes_ this one (which I expect) and _sometimes_ the crash shown above.
```python
Traceback (most recent call last):
  File "/home/bdice/issue.py", line 16, in <module>
    pa.array(A())
  File "pyarrow/array.pxi", line 320, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 39, in pyarrow.lib._sequence_to_array
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
TypeError: object of type 'A' has no len()
```

We want a `TypeError` to be raised rather than getting the crash above under `pdb`. The crash is reproducible without `pdb` if the snippet is run repeatedly. This might suggest some kind of memory corruption is happening behind the scenes.

### Component(s)

C++, Python

**Comment by jorisvandenbossche** [comment]
@bdice thanks for the report! I can reproduce this (I actually seem to get the crash consistently)

It might also be an upstream Python issue? Because if I replace `pa.array(A())` with `list(A())`, this hangs / blows up memory. 
You call it an "iterable" object, but since it doesn't have a length, it will iterate indefinitly?

In the C++ code handling generic input, we first try to convert any python object to an actual sequence:

https://github.com/apache/arrow/blob/7526df9ad97219cc44f9b460887405f2b0e86fd4/python/pyarrow/src/arrow/python/python_to_arrow.cc#L1098-L1101

It seems that this object is passing the `if (PySequence_Check(obj))` check, which I find a bit surprising (in pure python, it's not considered a Sequence when using collections.abc)

**Comment by jorisvandenbossche** [comment]
Ah, it's failing in the last line that I showed in the snippet above (calling `PySequence_Size`), but we fail to check for a python error afterwards (I suppose because the code assumed that would always work because of the sequence check before that). 
Checking for a python error and raising this one, correctly gives the "TypeError: object of type 'A' has no len()" error.

Looking at the python C API docs, it indeed mentions that `PySequence_Check` always passes for objects with `__getitem__`: https://docs.python.org/3/c-api/sequence.html#c.PySequence_Check

**Comment by jorisvandenbossche** [comment]
PR at https://github.com/apache/arrow/pull/34958
