### ISSUE TITLE
[C++] How to make Scanner read parquet files faster?

### ISSUE THREAD

**Issue by YoungRX** [apache/arrow#35000]
### Describe the usage question you have. Please include as many useful details as  possible.

I used `ParquetFileReader` in `/parquet/file_reader.h` to read parquet file before. And I implemented the predicate push-down myself. 

Now I am using 8.0.0. And I update the code to use `AsyncScanner::ToRecordBatchReader()` and `ScannerRecordBatchReader::ReadNext()` to read the parquet files. So I can use the predicate pushdown implemented internally by arrow. 

However, my code environment does not support multithreading, so I set up the following in `ScanOptions`:
> use_threads = false;
> batch_readahead = 0;
> batch_size = 1000;
> Other settings such as filter, projection, dataset_schema are set as required

As a result, when scanning the same parquet file with the same sql statement, the new code takes 1.5 to 2.0 times longer to execute than the old code. I think it is unreasonable. 

Is there an option I have that is not set correctly?
Or is it because multithreading and readahead are not enabled?
Do you have a way to make `Scanner` faster for reading parquet files?

### Component(s)

C++

**Comment by westonpace** [comment]
That is a rather small batch size.  I don't know how much profiling or focus we've had on sizes that small.  You might try something larger, like 32k.  I would expect the scanner to be slightly slower than ParquetFileReader directly but not 2x.  If you don't support any multithreading, not even I/O readahead, then what advantages are you hoping to gain by using the scanner instead of ParquetFileReader?

**Comment by YoungRX** [comment]
Thanks. I see.
