### ISSUE TITLE
[C#] Exception on basic usage

### ISSUE THREAD

**Issue by trunklegs911** [apache/arrow#35019]
### Describe the usage question you have. Please include as many useful details as  possible.

My code is as follows:
`using var stream = File.OpenRead(_readFilePath);
using (var reader = new ArrowFileReader(stream))
{
  var recordBatch = await reader.ReadNextRecordBatchAsync();
  Console.WriteLine(recordBatch.ColumnCount);
}`
At this point I am just trying to log the column count of the parquet file. The filestream does have data in it, and the parquet file is valid, and when I use the `await reader.ReadNextRecordBatchAsync()` an exception is thrown 
"System.IO.InvalidDataException: 'Invalid magic at offset <6>'"

Is my usage the problem? Or is this a bug? 

Thank you

### Component(s)

C#

**Comment by westonpace** [comment]
The C# Arrow implementation does not provide a parquet reader (this is different than most other implementations).  The `ArrowFileReader` that you are using is for reading Arrow IPC files, not parquet files.  These are two different formats (the parquet format is more focused on compression and minimizing I/O while the Arrow IPC format aims to be a mirror of the in-memory format to allow for things like memory-mapped zero-copy reads)

The exception you are getting is because the arrow file reader is not finding the expected magic number at the end of the file (all Arrow IPC files end with ARROW1).

I believe there are other C# projects you can use which provide parquet readers/writers.

**Comment by CurtHagenlocher** [comment]
@trunklegs911 I'm going to mark this as closed because the code is working as intended. I've been using [ParquetSharp](https://github.com/G-Research/ParquetSharp) with great success for reading Parquet files from C#. It looks like the next release will have the ability to produce and consume Arrow record batches in addition to the previously-supported APIs. There's also [Parquet.Net](https://github.com/aloneguid/parquet-dotnet) which has some advantages and disadvantages over ParquetSharp.
