### ISSUE TITLE
[C#] Add Arrow.Parquet File Reader/Writer

### ISSUE THREAD

**Issue by Platob** [apache/arrow#35037]
### Describe the enhancement requested

Hello,

It would be really nice to have Parquet Reader/Writer to Iterate over RowGroups converted in Arrow.RecordBatch

Is it planned ?

Would it be a wrapper around C++ implementation ?
Project alike: [ParquetSharp](https://github.com/G-Research/ParquetSharp)

Br

### Component(s)

C#

**Comment by Platob** [comment]
Found a workaround reading/writing in C++ IPC files, and handling in cpp convertions

**Comment by alikleit** [comment]
I see that ParquetSharp might not fit the needs of Writing from Arrow.RecordBatch where we have to compose a List of Columns and each column has a logicalSystemType rather than an ArrowType. Therefor an extra Mapping Layer that will be present. While apache arrow parquet (python) implement's a writer that writes directly record batches into the table. 

I find that quite important to have if you are working with multiple languages and the communication is via arrow, and parquet is the file format used by each.

Is there or would be there an option to do that in C#?
