### ISSUE TITLE
[Python] The parse_options parameter newlines_in_values doesn't work when reading JSON

### ISSUE THREAD

**Issue by R-JunmingChen** [apache/arrow#35096]
### Describe the bug, including details regarding any error messages, version, and platform.

I use the following code to read json file with parrow released version 11.0 from Anaconda

```
import pyarrow.json as pj
json_f=pj.read_json("test.json",parse_options=pj.ParseOptions(newlines_in_values=False))
json_t=pj.read_json("test.json",parse_options=pj.ParseOptions(newlines_in_values=True))
```
Here is the file content of test.json
```


{
    "name"

    :
    12312
    ,
    "b"
    :
    "test\\n"
}

{"name":123

,

"b":
"\n89\n"}

{"name":123123

}



```
However, the value of json_f and json_t are the same.

```
pyarrow.Table
name: int64
b: string
----
name: [[12312,123,123123]]
b: [["test\n","
89
",null]]
```
It seems that the `newlines_in_values` fails to work.

### Component(s)

Python

**Comment by westonpace** [comment]
CC @benibus

**Comment by benibus** [comment]
Sorry for the delay. `newlines_in_values` shouldn't actually affect the resulting table. It mostly serves as a warning to the reader that the source's JSON objects can't be reliably delimited by raw newlines - so a more expensive chunking path is taken prior to each chunk being parsed individually. Otherwise, parsing errors are very likely.

In your case, when `newlines_in_values=false`, you would get an error if you set `ReadOptions::block_size` to 64 (where the file size is 120). However, it would work just fine with `newlines_in_values=true`. 

That being said, I'm not entirely sure why `newlines_in_values` isn't in `ReadOptions` instead. Looking at the C++ implementation, the option doesn't appear to be used by the parser at all.

**Comment by R-JunmingChen** [comment]
> Sorry for the delay. `newlines_in_values` shouldn't actually affect the resulting table. It mostly serves as a warning to the reader that the source's JSON objects can't be reliably delimited by raw newlines - so a more expensive chunking path is taken prior to each chunk being parsed individually. Otherwise, parsing errors are very likely.
> 
> In your case, when `newlines_in_values=false`, you would get an error if you set `ReadOptions::block_size` to 64 (where the file size is 120). However, it would work just fine with `newlines_in_values=true`.
> 
> That being said, I'm not entirely sure why `newlines_in_values` isn't in `ReadOptions` instead. Looking at the C++ implementation, the option doesn't appear to be used by the parser at all.

It resolves my confusion.
May be we should refine the doc of parse_options？ Since it hard to get the point of  the function of `newlines_in_values` .
