### ISSUE TITLE
[Go] parquet: is there a way to differentiate null groups and groups containing null?

### ISSUE THREAD

**Issue by jayshrivastava** [apache/arrow#35619]
### Describe the usage question you have. Please include as many useful details as  possible.

Using the following schema to represent a nullable integer tuple type, how does one write the tuple `NULL` and differentiate it from `(NULL, NULL)`? I know the latter can be written by writing integers with def level 0, but I'm not sure about the former.
```
message schema {       
    optional group a (LIST) { 
        optional int f1;
        optional int f2;
    }
}
```
If it's not possible, are there any methods (ex. recommended schemas, columns, metadata) which are commonly used in this situation? I was thinking about adding an additional bool field `isNull` to deal with the problem, but I'm not sure if it's the best way. 

### Component(s)

Go, Parquet

**Comment by mapleFU** [comment]
@jayshrivastava Hi jay, this could handle by parquet internal. Parquet format has rep-level and def-level. `null` and `(null, null)` would have different rep-level and def-levels. So, Parquet reader and writer can distinct them.

**Comment by jayshrivastava** [comment]
@mapleFU What def levels and rep levels should I use in each case? My understanding is that rep levels are not relevant since there are no repeated fields. Can you please clarify what you mean by parquet internal?

**Comment by zeroshade** [comment]
@jayshrivastava in addition to what @mapleFU stated, this is also why the standard way for creating a list of tuples uses a 3-level schema that looks like this:

```
required group schema {
        optional group a (LIST) {
                 repeated group tuples {
                         optional int f1;
                         optional int f2;
                 }
        }
}
```

rather than the 2-level version in your issue. This can be seen via the description on the parquet format document: https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#lists

The fact that readers can interpret your original version is because the spec states that it should be supported for backwards compatibility.

**Comment by jayshrivastava** [comment]
@zeroshade @mapleFU Thanks for the help. I appreciate it a lot!
