### ISSUE TITLE
[Go][Parquet] panic for listof(types) if null

### ISSUE THREAD

**Issue by yevgenypats** [apache/arrow#35684]
### Describe the bug, including details regarding any error messages, version, and platform.

parquet writer will panic on any of the following types if the value null:

```
		{Name: "f1", Type: arrow.ListOf(arrow.FixedWidthTypes.Date32)},
		{Name: "f2", Type: arrow.ListOf(arrow.FixedWidthTypes.Date64)},
		{Name: "f3", Type: arrow.ListOf(arrow.FixedWidthTypes.Timestamp_us)},
		{Name: "f4", Type: arrow.ListOf(arrow.FixedWidthTypes.Timestamp_ms)},
		{Name: "f5", Type: arrow.ListOf(arrow.FixedWidthTypes.Time32ms)},
		{Name: "f6", Type: arrow.ListOf(arrow.FixedWidthTypes.Time64ns)},
		{Name: "f7", Type: arrow.ListOf(arrow.FixedWidthTypes.Time64us)},
```

### Component(s)

Go

Reproduction is here - https://github.com/apache/arrow/pull/35685

Im not sure though how to fix it as the parquet code is quite complex. cc @zeroshade

**Comment by zeroshade** [comment]
@yevgenypats So, looking at your example, the panic is coming because you only add a null to *one* of the fields in the record builder. Which means the builders are unbalanced for the record. One column has a length of 1 and the rest all have length 0, and a record must have the same number of rows in every column. So that's where your panic is coming from.

That said, after changing your example so that it appends a null to *every* column, I still got an error from a nil pointer dereference so I'm looking into that to fix it.
