### ISSUE TITLE
Writing dataset twice duplicate records

### ISSUE THREAD

**Issue by ratson** [apache/arrow#3605]
I am not sure if this is a "feature" or a bug.
When writing dataset twice in same `root_path` is resulting duplicate records.

I have wrote [a test to demo this](https://github.com/ratson/bug-report/blob/parquet-dataset-rw/parquet_test.py#L27), where the last assertion should be passed but instead failed with 6 == 3.

The versions of dependencies are described in [Pipfile](https://github.com/ratson/bug-report/blob/parquet-dataset-rw/Pipfile).

**Comment by xhochy** [comment]
Yes, this is expected behaviour. When writing to a dataset, we write into files that have a freshly generated UUID as part of their filename. As UUID collisions are extremely unlikely, we always duplicate this data. When you want to update/delete/extend existing datasets, you need to write your own custom logic to deal with this. This logic could be as simple as deleting the existing dataset before writing it out again.

**Comment by ratson** [comment]
If it is by design, then seems avoiding writing to the same path is simpler.
Is there any way to update part of the dataset (e.g. a single partition file) without writing all to new files? I would like to know if partial / incremental update to a dataset a bad idea.

**Comment by xhochy** [comment]
`partial / incremental update` is not a bad idea, it's just that you need some logic to know what's already in the dataset. This is the hard part.

**Comment by ratson** [comment]
@xhochy, thank you for the prompt reply.
Since I don't find any partial update example in the docs, I tried
https://github.com/ratson/bug-report/blob/parquet-dataset-partial-update/parquet_test.py#L20-L25
And it seems work, is using `pq.write_table` to update a dataset file directly won't cause problems?

**Comment by xhochy** [comment]
@ratson This will work. It might cause problems when your code/usecase gets more complicated, so as always, it's good to have a broad test suite ;)

**Comment by ratson** [comment]
Thanks, no more confusion.
