### ISSUE TITLE
Arrow Flight 2GB limit

### ISSUE THREAD

**Issue by marsupialtail** [apache/arrow#36254]
### Describe the usage question you have. Please include as many useful details as  possible.

I recall there was a 2GB limit for batches sent to flight server.

Is this still a thing?

### Component(s)

FlightRPC

**Comment by lidavidm** [comment]
Yes: https://github.com/apache/arrow/blob/2ce4a38fcf1fbd0d759b6c2cdf657f27ee6f02a9/cpp/src/arrow/flight/transport/grpc/serialization_internal.cc#L186

IIRC this is due to gRPC/Protobuf; because messages are technically Protobuf (even if we bypass the Protobuf implementation) and because Protobuf itself is limited to 2 GiB we inherit that
