### ISSUE TITLE
[FlightRPC] Dynamically setting endpoint in FlightInfo requests

### ISSUE THREAD

**Issue by aiguofer** [apache/arrow#36339]
### Describe the usage question you have. Please include as many useful details as  possible.

We're currently running our AFS server in Kubernetes and so far we've only been listening to public traffic, so we hardcode the Flight endpoint to our known public URL. We're currently building inter service communication in our Kubernetes cluster but we're running into an issue since we don't know what endpoint to send back since we don't know whether the request is coming from an external source or from another kubernetes service.

Is there a way to determine where a request is coming from to determine which endpoint to send back?

### Component(s)

FlightRPC

**Comment by lidavidm** [comment]
Is knowing the peer IP enough? https://github.com/apache/arrow/blob/0344a2cdf6219708a25f39e580406e0ce692b61e/cpp/src/arrow/flight/server.h#L131-L132

**Comment by aiguofer** [comment]
Hmm I'm honestly not very familiar with what a peer IP is... but I imagine we might be able to differentiate traffic coming through ELB and other internal services. Our server is in Java, but I can't find a way to get the IP from any of the `getFlightInfo` params

**Comment by lidavidm** [comment]
Ah! Whoops.

In Java, you can attach a gRPC interceptor to do it...it's not quite so convenient.

By peer IP, I just mean the IP of the client, as seen by your server. So if you know that public/private traffic comes from a particular IP or range of IPs, you can differentiate that way. Otherwise, depending on how exactly you set up networking, maybe you could configure public-facing load balancers (or private clients) to attach a header (that public-facing load balancers strip from incoming requests)?

**Comment by lidavidm** [comment]
If you follow the chain of links starting here, you can see how to do it in Java: https://github.com/apache/arrow/issues/31924

**Comment by aiguofer** [comment]
Cool thanks! I'll take a look tomorrow. We already have a few interceptors and ways to easily add headers to pass into requests so this should hopefully not be too difficult.

**Comment by aiguofer** [comment]
After talking to infra about this, we can't rely on IPs unfortunately. Instead we went with adding an extra parameter for inter-service communication since it's easy enough to ensure our other teams pass that in.

Closing this as resolved, but will add some thoughts on exposing the IP!
