### ISSUE TITLE
[C++][FlightRPC] Use gRPC version macros if possible

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#36479]
### Describe the enhancement requested

Currently, we have a suite of compilation-based configuration tests to find out the approximate gRPC version, for feature selection.

Starting with 1.51.0 however, the gRPC C++ API exposes version macros:
https://github.com/grpc/grpc/pull/31033

We could start using those and fallback on the older method if the macros are not available.

### Component(s)

C++, FlightRPC

**Comment by lidavidm** [comment]
Should we just drop support for older gRPC entirely? At this point 1.27 is from 3 years ago

**Comment by pitrou** [comment]
I have no idea. How hard is it to maintain support? @kou 

In any case, we have feature tests for many versions between 1.27 and 1.51 anyway.

**Comment by lidavidm** [comment]
Sure, but using the version macros doesn't really help us there.

**Comment by kou** [comment]
We can require gRPC 1.30 or later (drop support for 1.27) because:

* Ubuntu 20.04 doesn't provide usable gRPC (1.16 and we require 1.17 or later now)
* Ubuntu 22.04 provides gRPC 1.30
* Debian stable (bookworm) provides gRPC 1.51

Ubuntu versions: https://packages.ubuntu.com/search?keywords=libgrpc++-dev
Debian versions: https://packages.debian.org/search?keywords=libgrpc++-dev

BTW, we can use gRPC version detected by `find_package(gRPCAlt)` as macros in our C++ source codes. So we can use gRPC version information as macro without requiring gRPC 1.51 or later.

**Comment by pitrou** [comment]
What about RHEL and similar?

**Comment by kou** [comment]
* RHEL 7: NA
* RHEL 8: NA
* RHEL 9: gRPC 1.46.7 by EPEL

**Comment by pitrou** [comment]
Then I agree we  can require gRPC 1.30 or later. It won't simplify much, though ;-)
