### ISSUE TITLE
Go example using minio

### ISSUE THREAD

**Issue by gedw99** [apache/arrow#36567]
### Describe the enhancement requested

There are a few examples in go where SQLite is used and a simple parquet reader , but it would be great if there was an example using minio with flight sql.

I also got the feeling that it’s not possible to do mutations via flight sql . It’s because I keep reading everywhere that it’s only for OLAP. Which does not make sense because the data has to get put in somehow via ETL of Flight SQL. So maybe this can be answered as I am a little confused about this.

thanks in advance .

### Component(s)

Go

**Comment by zeroshade** [comment]
Flight SQL leverages using the `DoPut` method of Arrow Flight in order to allow bulk ingestion of Arrow data into a FlightSQL server. For Go, a server can implement this by implementing the `DoPutPreparedStatementUpdate` method of the FlightSQL server (which includes a `flight.MessageReader` to read in the stream of record batches). For the client, this is handled by using `Prepare` to prepare a statement and then using `SetParameters` (for a single record batch) or `SetRecordReader` (for an input stream of record batches). 

It is up to the server implementation to handle the incoming stream of record batches as input for getting data in.

I hope this helps answer the question!

**Comment by zeroshade** [comment]
@gedw99 Any other questions here or can I close this?

**Comment by gedw99** [comment]
Thanks so much . That really help !!
