### ISSUE TITLE
[R] Add forced type casting via `scheme`

### ISSUE THREAD

**Issue by vkhodygo** [apache/arrow#36847]
### Describe the enhancement requested

I have certain columns in my CSV files that are integers but stored as floats , i.e.,  years etc. 

```bash
$ cat test.csv
a,b
1.0,2.1
2.0,2
3,3.33
```
I'd like to read them as integers explicitly, and I do the following:

```R
t <- open_csv_dataset("./test.csv",
                      skip = 1,
                      schema = schema(
                                      field("a", uint16(), nullable = FALSE),
                                      field("b", float32(), nullable = FALSE)
                                      )
)

t |> collect()

Error in `compute.Dataset()`:
! Invalid: Could not open CSV input source '/home/usr/test.csv': Invalid: In CSV column #0: Row #2: CSV conversion error to uint16: invalid value '1.0'
ℹ If you have supplied a schema and your data contains a header row, you should supply the argument `skip = 1` to prevent the header being read in as data.
Run `rlang::last_trace()` to see where the error occurred.
```

Obviously, I could follow https://github.com/apache/arrow/issues/12469#issuecomment-1046246626 and just cast, but this approach clutters the code. 

@thisisnic What are your thoughts regarding this?

### Component(s)

R

**Comment by thisisnic** [comment]
I'm not sure this is possible without casting; although the values in column `a` are _intended_ to be integers, in the underlying data, they are not stored as integers.  Can you explain a bit more about why casting isn't a good solution for you?

**Comment by vkhodygo** [comment]
>  Can you explain a bit more about why casting isn't a good solution for you?

Because I have little to no control over the source of data.  It's generated by another software package and also in the 10TB - 100TB range meaning everything that can be compressed must be compressed for further storing and processing. In the case some changes the code to represent counts as floats or something equivalently odd the whole pipeline breaks, and I want it to as robust as possible.

**Comment by thisisnic** [comment]
I imagine it's tricky without control over the data source.  From what you've said though, it sounds like if you're expecting someone to have sent you float data when they should have sent integers, you could specify that column as a float in the schema and then cast to an integer.  

I'm going to close this ticket as the way that `schema()` works here is intentional and we're unlikely to change it, but if there's another reason why casting doesn't work for you, I'm happy to discuss it some more here and see if we can find you a better workaround.
