### ISSUE TITLE
[Java] Flight SQL JDBC driver stops receiving RecordBatches when it encounters one empty RecordBatch.

### ISSUE THREAD

**Issue by joao-p-pereira** [apache/arrow#36912]
### Describe the bug, including details regarding any error messages, version, and platform.

When reading the result of a query that returns more than one RecordBatch, if it encounters an empty one, it appears to stop the reading process. However, in reality, there is still data present in the subsequent record batches. We tested this behavior using the driver with SQuirreL SQL Client and a Java program, and the result was the same.

We have an internal Flight SQL command-line client built in Rust, which allows us to validate this observation. When we run the example query below, we can see that there are empty RecordBatches, but there are subsequent RecordBatches that contain data.

```
> query "select city from csv1 union select city from csv3"
+------+
| city |
+------+
+------+
+------+
| city |
+------+
+------+
+------+
| city |
+------+
+------+
+------+
| city |
+------+
+------+
+------+
| city |
+------+
+------+
+-------+
| city  |
+-------+
| Porto |
+-------+
+--------+
| city   |
+--------+
| Lisboa |
+--------+
+------+
| city |
+------+
+------+

```
Version:
flight-sql-jdbc-driver version 11.0.0

### Component(s)

Java

**Comment by jduo** [comment]
While working on another issue, it looks as though the driver evaluates FlightStream#getRoot()#getRowCount() > 0 as a stopping condition rather than evaluating FlightStream#next() or FlightStream#hasRoot().

https://github.com/apache/arrow/blob/66844e9f16e9cf26bd5d260de9150973f94f4d5a/java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/utils/FlightStreamQueue.java#L106

**Comment by jduo** [comment]
take
