### ISSUE TITLE
[C++] Using std::from_chars instead of std::atoi?

### ISSUE THREAD

**Issue by mapleFU** [apache/arrow#37263]
### Describe the enhancement requested

Now, arrow has shift to C++17.

I've seen code like:

```c++
  try {
    return std::max(0, std::stoi(str));
  } catch (...) {
    return 0;
  }
```

Can we use std::from_chars to do the conversion?

### Component(s)

C++

**Comment by js8544** [comment]
One concern is that the compiler support for `std::from_chars` was later than most c++17 features [1]. So you may also want to update [2] as well since it is not supported by gcc 7.

[1] https://en.cppreference.com/w/cpp/compiler_support/17 Search "Elementary string conversions"
[2] https://arrow.apache.org/docs/developers/cpp/building.html "On Linux, gcc 7.1 and higher should be sufficient"

**Comment by pitrou** [comment]
Given the limitations we've had to work around in `std::to_chars`, we'd probably like to avoid this indeed.

**Comment by mapleFU** [comment]
@js8544 @pitrou I notice that [1] is partial support, "FP" is not support now. Could we just use this for integer first?

**Comment by mapleFU** [comment]
I've submit a tiny patch in https://github.com/apache/arrow/pull/37265 , would you mind trigger the CI and have a try?

**Comment by mapleFU** [comment]
Oh I found gcc libstdc++ support it in 8, so I cannot try this, what a pity. I'll reopen this until we don't support gcc7
