### ISSUE TITLE
[Packaging][Release] Missing amazon-linux/2/x86_64/repodata/repomd.xml repo metadata file

### ISSUE THREAD

**Issue by dejlek** [apache/arrow#37334]
### Describe the enhancement requested

We re heavily relying on this file being available on JFrog's server.

```
[dejan@server ~]$ curl https://apache.jfrog.io/artifactory/arrow/amazon-linux/2/x86_64/repodata/repomd.xml
{
  "errors" : [ {
    "status" : 404,
    "message" : "File not found."
  } ]
}
```
Is there an alternative place we can try?

### Component(s)

Packaging

**Comment by raulcd** [comment]
Hi @dejlek I am not familiar enough with this area, do you know if this file was previously there?

I just released Apache Arrow 13.0.0 and from what I can see we dropped support for Amazon Linux 2 on that relase as seen here: https://github.com/apache/arrow/issues/36241
The file is available for Amazon Linux 2023:
https://apache.jfrog.io/ui/native/arrow/amazon-linux/2023/x86_64/repodata/

I wouldn't expect the file to be removed if it was previously there by our release scripts, that's why I am asking.

CC @kou

**Comment by dejlek** [comment]
Yes, files were definitely there for months...

**Comment by kou** [comment]
Oh, sorry. I've restored the `repodata` for Amazon Linux 2. We should have not removed the existing `repodata` for Amazon Linux 2 even if we dropped support for Amazon Linux 2.

**Comment by kou** [comment]
I'll update our release script to prevent this in future releases.

**Comment by raulcd** [comment]
@kou just for my personal interest, how did you regenerated the repodata for Amazon Linux 2? Did you downloaded it from the previous release and uploaded it manually?

**Comment by kou** [comment]
Artifactory has the "Trash Can" feature: https://apache.jfrog.io/ui/repos/tree/General/auto-trashcan/arrow

We can restore removed files from here. :-)

**Comment by raulcd** [comment]
> Artifactory has the "Trash Can" feature: https://apache.jfrog.io/ui/repos/tree/General/auto-trashcan/arrow
> 
> We can restore removed files from here. :-)

Nice, thanks @kou this is good to know.
