### ISSUE TITLE
 `py.array` on a `dict` does not raise an error and instead return the keys as an array

### ISSUE THREAD

**Issue by haixuanTao** [apache/arrow#37496]
### Describe the bug, including details regarding any error messages, version, and platform.

When using pyarrow, calling `py.array` on a `dict` creates a array of the dict keys. In case the dict keys are string it's going to be converted into a list of string, same things if the keys are int it's going to be a list of ints. 

In my opinion, it would be better to map it into a StructArray. In the same way that when it's called encapsulated in a `list`. See the following example:
```python
>>> import pyarrow as pa
>>> pa.array({"a":1, "b":2})
<pyarrow.lib.StringArray object at 0x7f4bacb8e500>
[
  "a",
  "b"
]
>>> pa.array([{"a":1, "b":2}])
<pyarrow.lib.StructArray object at 0x7f4bacb8e560>
-- is_valid: all not null
-- child 0 type: int64
  [
    1
  ]
-- child 1 type: int64
  [
    2
  ]
```

### Expected behaviour

Raise an error and direct the user to use `pa.scalar`

See: https://github.com/dora-rs/dora/pull/346

### Component(s)

Python

**Comment by wjones127** [comment]
> And so you could potentially do the same thing in arrow and map it to a StructArray format.

That's a whole different thing, since it implies the values are arrays. That would be:

```python
>>> pa.array({'x': [1, 2], 'y': ['a', 'b']})
struct array
  child x: int64 [1, 2]
  child y: utf8  ["a", "b"]
```

FWIW the `Table` constructor function `pa.table()` supports dictionaries like that, and they can be converted to struct array if that's what's needed.

> Ok, just found out you can use:
> pa.scalar(dict)
> for scalar type.

Yes, for singular values, use `pa.scalar()`.

> So, I guess, raising an error for pa.array(dict) avoiding silent conversion should be the way to go.

Still not sure we need to error. The same "silent" conversion will happen for anything that is iterable, and I don't think we want to carve out a whole bunch of data structures just because we think users didn't intentionally pass them. It's well understood that a dictionary is iterable over its keys, so I don't think it's that unexpected that it would produce an array consisting of its keys when passed to `pa.array()`.

**Comment by haixuanTao** [comment]
I see. My use case was with array values in the dict indeed. 

Make sense. I guess it's in the python philosophy of duct typing.

I guess the confusion comes from the naming of [StructArray](https://arrow.apache.org/docs/python/generated/pyarrow.StructArray.html) that I naively associated with the `array` constructor (as they share the same name). 

Thanks for helping.
