### ISSUE TITLE
Using FlightSQL with Grafana FlightSQL plugin

### ISSUE THREAD

**Issue by marsupialtail** [apache/arrow#37708]
### Describe the bug, including details regarding any error messages, version, and platform.

I tried to use FlightSQL example Docker here: https://voltrondata.com/resources/running-arrow-flight-server-querying-data-jdbc-adbc

I can query the service from Python no problem.

However when I am trying to set up connection with Grafana FLightSQL plugin, it doesn't work. It complains: 
flightsql: rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: EOF"

Have you guys seen this problem before?

### Component(s)

FlightRPC

**Comment by marsupialtail** [comment]
seems like some SSL version issue on the server: E0913 20:22:38.153841801      51 ssl_transport_security.cc:1501]       Handshake failed with fatal error SSL_ERROR_SSL: error:0A00010B:SSL routines::wrong version number.
Is there a way to run the server on http instead of https?

**Comment by kou** [comment]
It seems that you can't use non TLS connection:
https://github.com/voltrondata/flight-sql-server-example/blob/44e855558da76eefad2d75c133c9676cd3102ad0/src/flight_sql.cpp#L112

Could you open an issue on https://github.com/voltrondata/flight-sql-server-example/issues not here because the source code is managed on the repository?
