### ISSUE TITLE
[Java] Improve type coverage of DefaultVectorComparators 

### ISSUE THREAD

**Issue by lidavidm** [apache/arrow#37701]
### Describe the enhancement requested

It appears booleans and the various date/time/timestamp types are missing: https://github.com/apache/arrow/blob/main/java/algorithm/src/main/java/org/apache/arrow/algorithm/sort/DefaultVectorComparators.java

Ideally we would support all Arrow types.

### Component(s)

Java

**Comment by jduo** [comment]
take

**Comment by jduo** [comment]
On VectorValueComparator, there is a field for tracking the width of a value that applies to fixed-width vectors. For BitVectors this is a bit problematic since the width is an integer and BitVectors store use a single bit for values. It looks like this can be used for sorting algorithms.

What should be the behavior here? It seems that for variable-width types this gets ignored.

**Comment by lidavidm** [comment]
Right, I only see it used when sorting. 

I think for now, it can have a default nonsensical value (-1, or something), and we can have the sorter explicitly error if it gets a BitVector. A follow-up task could be to refactor `getValueWidth` to return `Optional` or similar, and then specialize FixedWidthOutOfPlaceVectorSorter on BitVector.

**Comment by jduo** [comment]
IntervalMonthDayNanoVector has its values represented externally (when calling getObject()) as PeriodDurations, which are a composition of Period and Duration objects. However Periods are not comparable by design (since months are units of periods but have variable numbers of days). 

So this type seems like it is not really comparable.

**Comment by lidavidm** [comment]
That's fair. C++ only sorts these types:

https://github.com/apache/arrow/blob/670cf3b820ade8f553a81ba5b3346b74734cf972/cpp/src/arrow/compute/kernels/vector_sort_internal.h#L36-L53

I think some types (like timestamps, dates) map onto those types, though (as that lists 'physical' types) but I agree intervals probably aren't (easily) sortable, then.
