### ISSUE TITLE
save col datatypes in the feather artifact

### ISSUE THREAD

**Issue by EdmundsEcho** [apache/arrow#37755]
### Describe the enhancement requested

Feather is a great format.  I recently migrated to using the format for purposes of short-term (weeks to months) archiving of various pandas and polars artifacts.

I noticed that despite casting my columns to a specific datatype (e.g., int -> str), witnessing the change prior to saving the dataframe to feather, that when I *reopen* the feather file, the typing information is gone.  It could be something else at my end... that said:

Is the typing information saved with the feather artifact? If not, the enhancement request: include the column type in the feather archive.

### Component(s)

Format

**Comment by zeroshade** [comment]
@EdmundsEcho The type information should exist in the feather format. The feather format itself is essentially identical to the Arrow IPC file format as described [here](https://arrow.apache.org/docs/python/feather.html). The only thing I can think of is if you're using an *extremely* old version of Arrow and it's writing Feather V1 files instead of V2? 

What version of pyarrow are you using?

**Comment by EdmundsEcho** [comment]
Knowing that the type is in fact embedded is helpful. Based on your answer I suspect something else is going on; for instance using fillna on a df, without aligning the types (the df hosts a mixed set of types, but only one type has possible NaN values).
