### ISSUE TITLE
[Python] Numpy 1.23.1 dependency issue with pyarrow 6.0.1 installation

### ISSUE THREAD

**Issue by AvisP** [apache/arrow#38221]
### Describe the bug, including details regarding any error messages, version, and platform.

`Version` : 6.0.1
`os` : Windows

The popular Ray library has a dependency on this particular version of pyarrow as mentioned [here](https://github.com/ray-project/ray/blob/master/python/setup.py#L245-L246). However installation of this version of pyarrow is causing some issues because it cannot find a numpy dependency and gives the following error

```
Collecting pyarrow==6.0.1
  Using cached pyarrow-6.0.1.tar.gz (770 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Ignoring numpy: markers 'python_version < "3.8"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.8"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.9"' don't match your environment
      Collecting cython>=0.29
        Obtaining dependency information for cython>=0.29 from https://files.pythonhosted.org/packages/39/5d/5ae976df4e368327864917a24f9dee7c8176de1b5b7044ee9903b8adb07a/Cython-3.0.3-cp311-cp311-win_amd64.whl.metadata
        Using cached Cython-3.0.3-cp311-cp311-win_amd64.whl.metadata (3.2 kB)
      ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
      ERROR: Could not find a version that satisfies the requirement numpy==1.21.3 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.3, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0, 1.21.1, 1.22.0, 1.22.1, 1.22.2, 1.22.3, 1.22.4, 1.23.0rc1, 1.23.0rc2, 1.23.0rc3, 1.23.0, 1.23.1, 1.23.2, 1.23.3, 1.23.4, 1.23.5, 1.24.0rc1, 1.24.0rc2, 1.24.0, 1.24.1, 1.24.2, 1.24.3, 1.24.4, 1.25.0rc1, 1.25.0, 1.25.1, 1.25.2, 1.26.0b1, 1.26.0rc1, 1.26.0)
      ERROR: No matching distribution found for numpy==1.21.3
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

There has been no updates on this in the `ray` github [issues](https://github.com/ray-project/ray/issues/39727). If this dependency issue can be fixed in pyarrow, depsite being an older version, it would be helpful to a lot of people. Thanks!

### Component(s)

Python

**Comment by jorisvandenbossche** [comment]
I don't fully understand the error exactly (why doesn't it find numpy 1.21.3, while this version definitely exists (https://pypi.org/project/numpy/1.21.3), and in the list of numpy versions it found, there are also more recent versions ..). 
But in the end, the reason it tries to download that specific version of numpy is because it is trying to build pyarrow from source (it downloaded the .tar.gz source distribution, and not a wheel), which is likely going to fail anyway even if numpy could be installed (building pyarrow from source requires non-python dependencies to be built first, which isn't handled by pip: https://arrow.apache.org/docs/dev/developers/python.html#building-on-windows

And the reason it is not using a binary wheel is because you have a too recent Python version. If you want to install a pyarrow version that is two years old, it's best to also use a Python version from that time. Looking at our 6.0.1 release (https://pypi.org/project/pyarrow/6.0.1/#files), we have wheels for up to Python 3.10, but so not Python 3.11.

This is not something we can solve on the pyarrow side (in theory we could maintain multiple versions at the same time and update them for newer python versions and other dependencies and continue to make releases for them, but we currently don't do that).

In the end it is Ray that simply needs to remove that pyarrow version upper pin for Windows.

**Comment by jorisvandenbossche** [comment]
Another option is to install Ray from conda-forge, where they patch Ray to remove this upper pin on pyarrow.
