### ISSUE TITLE
[Pyarrow] hdfs read file line by line not implemented

### ISSUE THREAD

**Issue by chenfj068** [apache/arrow#3838]
pyarrow hdfs api, readline  and readlines are not IMPLEMENTED,but i need them,  would  this feature be implemented in new release version?
`
    def readline(self, size=None):
        """NOT IMPLEMENTED. Read and return a line of bytes from the file.

        If size is specified, read at most size bytes.

        Line terminator is always b"\\n".
        """

        raise UnsupportedOperation()

    def readlines(self, hint=None):
        """NOT IMPLEMENTED. Read lines of the file

        Parameters
        -----------

        hint: int maximum number of bytes read until we stop
        """

        raise UnsupportedOperation()
`

**Comment by emkornfield** [comment]
Hi @chenfj068,
I don't recall seeing anyone working on these.  The most recent work I could find was https://github.com/apache/arrow/pull/2253/files which mentions keeping them out because they were sub-optimal.  Depending on your use-case you might be able to use  [the csv reader](https://arrow.apache.org/docs/python/csv.html?highlight=read_csv) to get the lines you need.

**Comment by wesm** [comment]
@chenfj068 if you would like to implement these, can you please open a JIRA issue? Closing the GitHub issue for now
