### ISSUE TITLE
[Go] ValueOffset of array.Binary panics on last index

### ISSUE THREAD

**Issue by frbvianna** [apache/arrow#38458]
### Describe the bug, including details regarding any error messages, version, and platform.

As detailed in https://github.com/apache/arrow/issues/37976#issuecomment-1778312704, we are using ValueOffset64 method of binary-like variable width types (string, binary) to calculate the offset differences and determine all individual value byte widths.

For an Arrow Record of e.g. 10 rows with an `array.Binary` field, a panic will occur on `ValueOffset(10)` (last index, matching the data slice length):
https://github.com/apache/arrow/blob/f0c8229f5a09fe53186df171d518430243ddf112/go/arrow/array/binary.go#L76-L78 

This seems to be due to use of `>=` instead of `>`. Apparently the same applies for `array.LargeBinary` fields.

For comparison, `array.String` fields do not panic when the index input matches the data length:
https://github.com/apache/arrow/blob/f0c8229f5a09fe53186df171d518430243ddf112/go/arrow/array/string.go#L66-L68
 

### Component(s)

Go

**Comment by polestar1988** [comment]
@frbvianna did you get answer regards to this issue? I have the same error.

**Comment by frbvianna** [comment]
@polestar1988 No answers yet, but validated in local code that the solution is indeed to change `>=` for `>`.

**Comment by polestar1988** [comment]
I also handled it in my code instead of using func (a *Binary) ValueOffset(i int) :
```
if recordNumber < 0 || recordNumber > colBinary.Data().Len() {
	slog.Error("index out of range", "calculateSize", "Error")
	return 0
}
end := int(colBinary.ValueOffsets()[colBinary.Data().Offset()+recordNumber+1])
start := int(colBinary.ValueOffsets()[colBinary.Data().Offset()+recordNumber])
elementSize = end - start
....
```

**Comment by frbvianna** [comment]
Thanks @polestar1988, that is one alternative.

In my case (https://github.com/apache/arrow/issues/37976#issuecomment-1778312704), I was trying to make use of `array.BinaryLike` interface to simplify this handling, but that interface is constrained to `ValueOffset64(int) int64` so I would not be able to access the raw `ValueOffsets` from it.
I also find it unsettling that `ValueOffset`/`ValueOffset64` take in `int` row index parameters whereas slicing methods take in `int64`.
@zeroshade can you please confirm if these are intended?

**Comment by zeroshade** [comment]
So, at minimum this should be fixed to be consistent between the `Binary` and `String` types, it was not intended to be inconsistent.

That all said: I believe the intent of the `ValueOffset` method is to provide the starting offset of the value at index `i`, which means that the `Binary` type is correct in having the `>=` there, because there's no value at an index equal to the length of the slice/array to get the *starting* offset for. Instead you'd use `ValueLen`, or `ValueOffsets` and grab the last value or something like that. 

If you're trying to get the element size, there's already a `ValueLen` method which does that for you. If you're trying to get the actual value, the `Value` method returns a slice with the value without copying. 

So, I believe the optimal solution here would be to expose the `ValueLen` method in the `BinaryLike` interface so that you do not need to try to calculate these byte widths yourself manually and can instead just call that method.

What do you both think?

> I also find it unsettling that ValueOffset/ValueOffset64 take in int row index parameters whereas slicing methods take in int64

This was done for consistency as most of the existing row index params in the array types use `int` rather than an explicit `int64` (likely for convenience). In theory this would only affect someone if they were running on a 32-bit machine but had enough rows that it would not fit in an int32.

**Comment by frbvianna** [comment]
> So, I believe the optimal solution here would be to expose the ValueLen method in the BinaryLike interface so that you do not need to try to calculate these byte widths yourself manually and can instead just call that method.

This seems like a reasonable solution to me. It would simplify things for us as well.

**Comment by frbvianna** [comment]
> If you're trying to get the element size, there's already a ValueLen method which does that for you. If you're trying to get the actual value, the Value method returns a slice with the value without copying.

Just to note here, using `ValueLen` directly on the `array.Binary` also panics on the last row index, it also checks for `>=` on data slice. So exposing the `ValueLen` in the `BinaryLike` interface alone does not seem to be a solution, the boundaries need to be fixed in addition to that as well, what was suggested in https://github.com/apache/arrow/issues/38458#issuecomment-1785271119 seems to be the only way to get the value length for the last element in a binary column right now.
