### ISSUE TITLE
[R][Docs] pkgdown site docs report version 14.0.1

### ISSUE THREAD

**Issue by thisisnic** [apache/arrow#38689]
### Describe the bug, including details regarding any error messages, version, and platform.

https://arrow.apache.org/docs/r/ shows version 14.0.1 but should say 14.0.0

### Component(s)

R

**Comment by amoeba** [comment]
Hey @thisisnic, I can take a look at this today.

**Comment by amoeba** [comment]
I made an attempt at fixing this in https://github.com/apache/arrow-site/pull/445 which I think is how it's done.

**Comment by kou** [comment]
We're bumping the version in our `dev/release/01-prepare.sh` script that is used in our release process https://arrow.apache.org/docs/developers/release.html#create-the-release-candidate-branch-from-the-updated-maintenance-branch :

https://github.com/apache/arrow/blob/2abb3fb7095241300e2bb2aadd953b0f23970237/dev/release/01-prepare.sh#L96

https://github.com/apache/arrow/blob/2abb3fb7095241300e2bb2aadd953b0f23970237/dev/release/utils-prepare.sh#L125-L129

BTW, do we have a plan to release 14.0.2 R arrow package? It seems that there are some R fixes in 14.0.2: https://arrow.apache.org/release/14.0.2.html#changelog

**Comment by amoeba** [comment]
Thanks @kou, I don't think there's any plan to release a 14.0.2 (there wasn't a 14.0.1 either). There was a 14.0.0 and a 14.0.0.1. The 14.0.2 changes are in 14.0.0.2 AFAIK. I think the R package really needs to be able to determine its own version and it would be nice if that was built into the release automation.

**Comment by kou** [comment]
Hmm. Why does the R package use 14.0.0.2 instead of 14.0.2? I feel that 14.0.2 is a natural version if 14.0.0.2 includes the 14.0.2 changes.
Is there any versioning rule? We want to automate detecting the correct version like the current release script does.

**Comment by amoeba** [comment]
There's one reason I can remember and one I can't, others will have to chime in like @thisisnic and @assignUser.

The R package needs to be able version control the often numerous re-submissions the team makes to CRAN as part of their submission review process so bumping patch version on each re-submission would mean the R package could get ahead of Arrow itself. So bumping the revision instead of patch number is a way to avoid this.

Now I'm not sure why we don't bump the patch version if an Arrow patch release happens during the CRAN re-submission phase like is the case right now. I wonder if our 14.0.0.X re-submissions are all based off the maint-14.0.0 branch and whether cherry-picking things from the Arrow patch release branches or not. I think there was a thread on Zulip but I can't find it. Maybe documenting this would be helpful.

**Comment by assignUser** [comment]
We are going to release a 14.0.2 version which will include all changes previously released as 14.0.0.2 + some additional fixxes like #38869 but during the vote a new cran we have to fix poped up and we are currently waiting on #39250 to be merged to do that. If not for this issue we would have already submitted the 14.0.2 version of the package as part of the post release tasks.

@amoeba's explanation of the 4th version component is correct otherwise :)

**Comment by assignUser** [comment]
CRAN submissions are closed for the  holidays and will reopen on the 8th. Submission is [prepared](https://github.com/apache/arrow/tree/maint-14.0.2-cran) and will happen as soon as they are back.

**Comment by amoeba** [comment]
I'm closing this as it was fixed through other means.
