### ISSUE TITLE
[C++][FS][Azure] Implement `DeleteFile()`

### ISSUE THREAD

**Issue by kou** [apache/arrow#38703]
### Describe the enhancement requested

It's not implemented yet.

This is a child of GH-18014.

### Component(s)

C++

**Comment by av8or1** [comment]
Tom, I have an initial implementation completed.  However, I have concerns surrounding testing.  Specifically:
1) How have other contributors been testing similar functionality?
2) Is there a scripted process that I can follow to replicate that testing?
3) I took a look at the azurefs_test.cc file and noted the modifications made to provide regression for similar functionality.  However I am wondering what all use cases I would need to support for DeleteFile?  I am not as familiar with this type of testing, as we do our own in-house stuff, but this seems straightforward enough.

Finally, I implemented this using DeleteIfExists() rather than Delete(), for I saw that the former method was used elsewhere in the Azure work.  Any feedback regarding that choice?

**Comment by kou** [comment]
> Tom, I have an initial implementation completed. However, I have concerns surrounding testing. Specifically:

Great! Could you open a draft PR for it?

>     1. How have other contributors been testing similar functionality?

I'm using `ninja -C cpp.build debug/arrow-azurefs-test && LD_LIBRARY_PATH=$PWD/cpp.build/debug cpp.build/debug/arrow-azurefs-test`. Here are some notes for the command line:

* I'm on Debian GNU/Linux
* I use `cpp.build` as my build directory for `cpp/`
* The current directory is the top directory of cloned apache/arrow

>     2. Is there a scripted process that I can follow to replicate that testing?

https://arrow.apache.org/docs/developers/cpp/development.html#running-unit-tests is the standard process but it runs all tests.

>     3. I took a look at the azurefs_test.cc file and noted the modifications made to provide regression for similar functionality.  However I am wondering what all use cases I would need to support for DeleteFile?  I am not as familiar with this type of testing, as we do our own in-house stuff, but this seems straightforward enough.

We can borrow test patterns from GCS's one for now: https://github.com/apache/arrow/blob/main/cpp/src/arrow/filesystem/gcsfs_test.cc

We'll use generic tests eventually after we implement all features: https://github.com/apache/arrow/issues/39069

> Finally, I implemented this using DeleteIfExists() rather than Delete(), for I saw that the former method was used elsewhere in the Azure work. Any feedback regarding that choice?

Let's discuss this on a draft PR.

**Comment by av8or1** [comment]
Thanks.  I have opened a PR:
[https://github.com/apache/arrow/pull/39648](url)
