### ISSUE TITLE
[CI][Docs] Docs preview jobs failing

### ISSUE THREAD

**Issue by AlenkaF** [apache/arrow#38711]
### Describe the bug, including details regarding any error messages, version, and platform.

The crossbow docs preview jobs have started failing with message:

```
Run aws s3 cp build/docs/ $BUCKET/pr_docs/38693/ --recursive
/home/runner/work/_temp/70d5ef2e-28c6-49e6-8af5-fca87c77e[1](https://github.com/ursacomputing/crossbow/actions/runs/6860473195/job/18654366354#step:10:1)39.sh: line 1: aws: command not found
Error: Process completed with exit code 127.
```
on the Upload preview to S3 step.

Examples:
- https://github.com/ursacomputing/crossbow/actions/runs/6860473195/job/18654366354
- https://github.com/ursacomputing/crossbow/actions/runs/6857464984/job/18646604692

cc @assignUser 

### Component(s)

Continuous Integration

**Comment by llama90** [comment]
Hello,

It seems that the workflow file you're referring to, possibly [`github.linux.yml`](https://github.com/apache/arrow/blob/main/dev/tasks/docs/github.linux.yml), does not include a step for installing the AWS CLI. Here's a script that might work for adding such a step:

```
- name: Install AWS CLI
  run: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
```

I'm curious if creating a PR and then leaving a comment like `@github-actions crossbow submit preview-docs` would execute the workflow based on the files in the PR.

**Comment by AlenkaF** [comment]
> I'm curious if creating a PR and then leaving a comment like `@github-actions crossbow submit preview-docs` would execute the workflow based on the files in the PR.

Yes, that is exactly the workflow that is failing: https://github.com/apache/arrow/pull/38693#issuecomment-1809668151.

**Comment by llama90** [comment]
Thank you for the response.

Interestingly, the current runner image seems to be deployed with `AWS CLI 2.13.30` as part of the CLI Tools, according to the [Ubuntu2204-Readme.md](https://github.com/actions/runner-images/blob/388d55d0d741619a8718061d401166ebdc1f01f5/images/linux/Ubuntu2204-Readme.md).

Until about a month ago, `preview-docs` was working fine, but there have been two image updates since then: on `Oct 19` and `Oct 26`, as seen in the [commit history of Ubuntu2204-Readme.md](https://github.com/actions/runner-images/commits/388d55d0d741619a8718061d401166ebdc1f01f5/images/linux/Ubuntu2204-Readme.md). 

* https://github.com/apache/arrow/pull/38241#issuecomment-1759375128

Umm… It seems like someone with expertise in this area should take a look at this issue… While explicitly installing AWS CLI might work, it feels like a simplistic approach. I apologize for any confusion caused.

**Comment by kou** [comment]
Oh, sorry.
I should have not removed `aws-cli` related files in GH-38233.
Could you remove `aws-cli` related `rm -rf` from `ci/scripts/util_free_space.sh`?

**Comment by AlenkaF** [comment]
Thank you @llama90 for the help!

**Comment by AlenkaF** [comment]
@kou I am not sure why the docs are still failing to build on this PR:
https://github.com/apache/arrow/pull/38693
https://github.com/ursacomputing/crossbow/actions/runs/6888918318/job/18738847448

The preview build should take changes from main and not from the PR right?

**Comment by kou** [comment]
Could you rebase on main? The PR branch (not main) needs to have this fix.
