### ISSUE TITLE
[Python] Partitioned Datasets are not correctly written if partitions differ by case

### ISSUE THREAD

**Issue by lgaborini** [apache/arrow#39121]
### Describe the bug, including details regarding any error messages, version, and platform.

R and Python Dataset writers share the same issue #38804:
partitions are case-sensitive, this conflicts with case-insensitive filesystems.

```python
import pyarrow as pa
import pyarrow.dataset as ds

tbl = pa.table({
    'var_1': ("arrow", "arrow", "arrow"),
    'var_2': ("arrow", "arrow", "arroW")
})

part = ds.partitioning(
    pa.schema([("var_2", pa.string())]), 
    flavor="hive"
)

ds.write_dataset(tbl, "dataset_output", format="parquet", partitioning=part)

ds_out = ds.dataset("dataset_output")

```

Only one partition is written:

```python
ds_out.files
# ['dataset_output/var_2=arroW/part-0.parquet']
```

```python
ds_out.to_table()
# pyarrow.Table     
# var_1: string     
# ----
# var_1: [["arrow"]]
```

_Originally posted by @lgaborini in https://github.com/apache/arrow/issues/38804#issuecomment-1844899886_

(Opening a new issue to add more labels)

### Component(s)

Parquet, Python

**Comment by amoeba** [comment]
Hi @lgaborini, thanks for the report. Since you can reproduce this with R and Python, it's probable C++ is affected too and may even be the place to put a patch. Could you close this issue and edit the tile and body of https://github.com/apache/arrow/issues/38804 just to have one issue for us to work from? I can go add the labels now.

**Comment by lgaborini** [comment]
Done, thanks!
