### ISSUE TITLE
[C++][Parquet] Timestamp conversion from Parquet to Arrow does not follow compatibility guidelines for convertedType

### ISSUE THREAD

**Issue by joellubi** [apache/arrow#39489]
### Describe the bug, including details regarding any error messages, version, and platform.

The Parquet format [document](https://github.com/apache/parquet-format/blob/eb4b31c1d64a01088d02a2f9aefc6c17c54cc6fc/LogicalTypes.md?plain=1#L480-L485) indicates that converted types should have `isAdjustedToUtc=true` for backward compatibility, but the current C++ [implementation](https://github.com/apache/arrow/blob/37a8bf04bc713858a5b247d4424c1e8505e61947/cpp/src/parquet/arrow/schema_internal.cc#L92-L93) sets this to `false` for converted types.

The [Rust implementation](https://github.com/apache/arrow-rs/blob/a61e824abdd7b38ea214828480430ff2a13f2ead/parquet/src/arrow/schema/primitive.rs#L211-L239) already follows the spec as described and the Go implementation has #39467 open to correct this.

### Component(s)

C++, Parquet

**Comment by mapleFU** [comment]
Thanks for point this out!

**Comment by mapleFU** [comment]
@joellubi I found this is only called in the code path below:

```
FromInt64Statistics/GetArrowType
- FromInt64
-- MakeArrowTimestamp
```

I guess this will not frequently call in code path, because:
1. `FromInt64Statistics` is used for filtering, and this might making filtering invalid
2. `GetArrowType` is harmful, but if the type is annotated, it might not use this?

**Comment by jorisvandenbossche** [comment]
Some related discussions:

* https://github.com/apache/arrow/pull/4825
* https://github.com/apache/arrow/issues/22303
* https://github.com/apache/arrow/pull/4856

Now I suppose that because of those mentioned issues, when converting a TimestampLogicalType to an Arrow timestamp type, we do ignore the `isAdjustedToUtc` flag if the logical type has been annotated to come from a converted type. So then changing `isAdjustedToUtc` in those cases shouldn't actually impact any behaviour in the Arrow API layer of the Parquet library?

**Comment by mapleFU** [comment]
> Now I suppose that because of those mentioned issues, when converting a TimestampLogicalType to an Arrow timestamp type, we do ignore the isAdjustedToUtc flag if the logical type has been annotated to come from a converted type. So then changing isAdjustedToUtc in those cases shouldn't actually impact any behaviour in the Arrow API layer of the Parquet library?

@jorisvandenbossche Yes. As I mentioned, this might only happens when:
1. Filtering ( Statistics might got the wrong time )
2. Read a legacy file in parquet-mr

**Comment by jorisvandenbossche** [comment]
Actually, my comment above was wrong: 

> when converting a TimestampLogicalType to an Arrow timestamp type, we do ignore the `isAdjustedToUtc` flag if the logical type has been annotated to come from a converted type. So then changing `isAdjustedToUtc` in those cases shouldn't actually impact any behaviour in the Arrow API layer of the Parquet library?

This is exactly what your PR changed, i.e. it's the conversion from a Parquet type to Arrow type (`MakeArrowTimestamp`) that now _no longer_ ignores `isAdjustedToUtc` for converted types. 
So of course this does change behaviour, also for the Arrow APIs. 

And so the consequence of this is that reading an older file written by Arrow, will now be read differently (and this was a compatibility that was explicitly added in https://github.com/apache/arrow/pull/4856). 

It's maybe OK to change this behaviour, so we give up faithful roundtrip for those older files written by Arrow (in the end, it are old files), in favor of better compatibility with the Parquet spec and other producers, but we need to be explicit about that this is actually a behaviour change for users.

**Comment by mapleFU** [comment]
Yes, we can document it before we releasing 16.0

**Comment by mapleFU** [comment]
Yeah.

```
<pyarrow._parquet.ParquetSchema object at 0x7ff21be310c0>
required group field_id=-1 schema {
  optional int64 field_id=-1 col (Timestamp(isAdjustedToUTC=true, timeUnit=microseconds, is_from_converted_type=true, force_set_converted_type=false));
}
```

Hmmm this regard `isAdjustedToUTC=true`, however, the col is `col: timestamp[us]`.

Do you think we need an extra config, or just changing this?

**Comment by mapleFU** [comment]
Ah I got your meaning, however, does this means the legacy file cannot have any timezone?

**Comment by mapleFU** [comment]
I'll draft another patch which adding these in doc, and revert the change there `docs/source/cpp/parquet.rst`

**Comment by joellubi** [comment]
Thank you for adding those details @jorisvandenbossche, it really helped clarify the context of the previous decision. In thinking about this, it seems there may actually be two separate but related goals for the conversion:

1. Preservation of the original Parquet semantics when converting to Arrow
2. Preservation of the original Arrow type when a roundtrip occurs through Parquet and back to Arrow

Since the legacy Parquet types cannot distinguish between instant and local semantics, consumers have had to make an arbitrary choice between the two as you described. It does seem, at least now, that the Parquet spec has an explicit position that the deprecated convertedType timestamps always had instant semantics, and that local semantics were unsupported ([source](https://github.com/apache/parquet-format/blob/eb4b31c1d64a01088d02a2f9aefc6c17c54cc6fc/LogicalTypes.md#deprecated-timestamp-convertedtype)). This helps make the current position clear but doesn't change the reality of real-world Parquet usage that has not followed these semantics.

In the case that a Parquet file is being read and we don't know (or care) how it was produced, I do think it makes sense to follow compatibility guidelines (as the recently-merged PR has). This does break roundtrip behavior (thank you for pointing this out), but I do think Arrow already has an independent solution to this case. The metadata associated with the `ARROW:schema` key _should_ be able to preserve this information on roundtrip, and I was actually surprised that it didn't in your example. I found [this](https://github.com/apache/arrow/blob/72ed58449ea71aab1343d9adce19f177f20705cf/cpp/src/parquet/arrow/schema.cc#L922-L933) relevant code for how we currently handle the restoration of the original type. It seems that we will restore a particular timezone if it was present in the original schema, but _do not_ remove the timezone if one was not present. Perhaps by independently updating this logic we can get the desired behavior for both scenarios.

Desired behavior IMO:
```python
>>> pq.read_metadata("test_timestamp_convertedtype_writer_unknown.parquet").schema.to_arrow_schema()
col: timestamp[us, tz=UTC]

>>> pq.read_metadata("test_timestamp_convertedtype_written_by_arrow_no_tz.parquet").schema.to_arrow_schema()
col: timestamp[us]

>>> pq.read_metadata("test_timestamp_convertedtype_written_by_arrow_with_tz.parquet").schema.to_arrow_schema()
col: timestamp[us, tz=UTC]
```

**Comment by jorisvandenbossche** [comment]
> I do think Arrow already has an independent solution to this case. The metadata associated with the `ARROW:schema` key _should_ be able to preserve this information on roundtrip, and I was actually surprised that it didn't in your example.

This additional `ARROW:schema` metadata was only added around the same time that we started to support LogicalType (around Arrow 0.14.0), so unfortunately it doesn't help for this use case. When it is present, it indeed allows to preserve the actual timezone (also for logical types, which otherwise only knows if it is UTC or not). 
But so when `ARROW:schema` is present, the file thus also has LogicalType annotations, and this whole discussion of course only applies to older files that only have ConvertedTypes.

So while I certainly agree with your "desired behaviour" being desired, it's not possible to distinguish with or without tz (even for files written by Arrow), because the only information there is in the file is the ConvertedType.

**Comment by joellubi** [comment]
> This additional ARROW:schema metadata was only added around the same time that we started to support LogicalType (around Arrow 0.14.0), so unfortunately it doesn't help for this use case.

I see, indeed unfortunate. Would you be in favor of adding a field to `ArrowReaderProperties` to control this behavior?

**Comment by jorisvandenbossche** [comment]
Comment from @pitrou on the PR at https://github.com/apache/arrow/pull/39491#issuecomment-1884825697:

> > Nowadays it is maybe OK to make a different trade-off, and to prioritize the Parquet spec / non-Arrow legacy files above compatibility of reading Arrow legacy files, given that it is about files written by an Arrow version of several years old (Arrow < 0.15).
> 
> If we really care about this, we should perhaps detect the offending Arrow version, since the Parquet file records the producer name and version.

We could indeed infer if the file was written by Arrow (the version shouldn't matter, I think, because in the end we care about whether the LogicalType is present or not, which is always the case starting from a certain version). 
I don't know if that wouldn't make things more complex / confusing for users though, that a similar file (just by a different producer) would give different results.

> But we would also need an actual file to test with.

Above (https://github.com/apache/arrow/issues/39489#issuecomment-1884416205) I posted a small example, and updated that comment to attach the generated file that I used. 
We do actually have a file in the pyarrow tests that covers this ([python/pyarrow/tests/data/parquet/v0.7.1.column-metadata-handling.parquet](https://github.com/apache/arrow/blob/main/python/pyarrow/tests/data/parquet/v0.7.1.column-metadata-handling.parquet)), but the test didn't catch that, because it only tested roundtrip to/from pandas, and for pandas it was using additional _pandas_ metadata we did already store in the schema at the time, and so that still correctly roundtrips. 

But, yes, in general we have a lack of testing for Parquet on this front: https://github.com/apache/arrow/issues/22325

---

> Would you be in favor of adding a field to `ArrowReaderProperties` to control this behavior?

To be honest, I am not sure what would be the best option. Add a way to control the behaviour of course make this more flexible for the user/library using arrow, but 1) is it still needed to add this given it is for legacy files? (I don't know how many producers still generate them), and 2) we still need to make a choice of a default in the Arrow libraries. 

Assume we would keep the default in Arrow as it was before, do you have applications that would set it differently? (maybe yes, as that might have triggered this discussion?)

And again: this whole change is maybe fine nowadays. I mostly wanted to point out this was _not_ a bug, but a deliberate design decision in the past, and if we change this, we should do it deliberately and flag it as a breaking change.

**Comment by joellubi** [comment]
> I don't know if that wouldn't make things more complex / confusing for users though, that a similar file (just by a different producer) would give different results.

I agree this could be confusing. For example datalakes are often written to by many potentially different producers so inconsistencies when reading could surface in this scenario.

> To be honest, I am not sure what would be the best option. Add a way to control the behaviour of course make this more flexible for the user/library using arrow, but 1) is it still needed to add this given it is for legacy files? (I don't know how many producers still generate them), and 2) we still need to make a choice of a default in the Arrow libraries.

I think that an option to control the behavior would be valuable, but a default that doesn't prompt users to update their files or application logic probably isn't helpful. Do we use warnings or any other ways deprecating certain usage in other parts of Arrow?

> Assume we would keep the default in Arrow as it was before, do you have applications that would set it differently? (maybe yes, as that might have triggered this discussion?)

For what it's worth, I do not. I was having issues in an application using the Go Parquet implementation which had a bug different from the logic here. As part of updating the Go implementation, I referred to the Parquet format document as well as a few other existing implementations which is when I noticed this inconsistency here.

**Comment by mapleFU** [comment]
> 
For what it's worth, I do not. I was having issues in an application using the Go Parquet implementation which had a bug different from the logic here. As part of updating the Go implementation, I referred to the Parquet format document as well as a few other existing implementations which is when I noticed this inconsistency here.

Anyway, I think I can document the behavior here.

**Comment by mapleFU** [comment]
Re-close this
