### ISSUE TITLE
[Java] Serializing ArrowArrayStream with ArrowStreamWriter

### ISSUE THREAD

**Issue by tom-s-powell** [apache/arrow#39687]
### Describe the usage question you have. Please include as many useful details as  possible.

In Java I have access to an `ArrowArrayStream` (via `ArrowArrayStreamReader`). I was wondering the most efficient way to serialize that in the IPC streaming format. I know I can use `ArrowStreamWriter` and together that requires various loading/unloading of `VectorSchemaRoot` or `ArrowRecordBatch`. I didn't know if there was an alternative way of serializing the stream to a `WriteChannel` that avoided any overhead of going to/from `VectorSchemaRoot`.

### Component(s)

C, Java

**Comment by vibhatha** [comment]
Thanks for the question. 

As far as I understand, I am not sure if we can avoid `VectorSchemaRoot` in this case, because this is the standard in-memory representation of Arrow data in the Java library. So if things are done in Java, I am not exactly sure how to avoid this. 

cc @lidavidm @danepitkin @davisusanibar 

But maybe if Java is just a passing through layer and the real deserialization needs to happen somewhere else (non Java), it could be possible to rewrite or extend `ArrowArrayStreamReader` interface and just pass the buffer and use the C Data interface in the non Java program.

**Comment by tom-s-powell** [comment]
So I did actually manage to avoid fully going to `VectorSchemaRoot`, by copying some of the code in `Data#importIntoVectorSchemaRoot` so I just work with `ArrowRecordBatch`. 

My use-case is actually Java -> Java, but transferring data over the network. It's not a Flight server, but you could imagine if you have Java server and Java client, if the Java server gets an `ArrowArrayStream`, if we could serialize as-is over the wire, the client would be able to handle that and convert to `VectorSchemaRoot` at that point.

Maybe this isn't a valid concern, perhaps the overhead isn't significant enough. My assumption was there was a bunch of memory/object allocation happening when going to `VectorSchemaRoot` or `ArrowRecordBatch` that was maybe unnecessary. I don't know `ArrowArrayStream` looks though compared to the IPC stream format.

**Comment by lidavidm** [comment]
Importing/exporting from a VectorSchemaRoot doesn't copy data, it just traverses the buffers and constructs Vector objects to wrap the buffers/traverses the Vector objects to get the buffers.

**Comment by vibhatha** [comment]
@tom-s-powell I understand your use case, as @lidavidm pointed out, the cost would be very minimum since it doesn't copy things. Is there a performance difference between your new approach and by just using the approach in the cookbook? 

I doubt there would be a significant performance difference, but would be good to check it. 

> So I did actually manage to avoid fully going to `VectorSchemaRoot`, by copying some of the code in `Data#importIntoVectorSchemaRoot` so I just work with `ArrowRecordBatch`.

Sounds like an extended functionality, that's nice. Maybe there is a slight performance improvement because of GC? (not sure, better to check).

**Comment by vibhatha** [comment]
@tom-s-powell need further help with this issue?

**Comment by tom-s-powell** [comment]
No all good for now. I'll do some benchmarking and can circle back with findings if there seem to be a noticeable performance difference.
