### ISSUE TITLE
Flight Returned : C-ares status is not ARES_SUCCESS qtype=A

### ISSUE THREAD

**Issue by Arunodaya-Das-Maersk** [apache/arrow#40016]
### Describe the bug, including details regarding any error messages, version, and platform.

We are using Arrow flight driver to connect excel to Dremio. It used to work fine till approx Oct'23 but started throwing error since then and its getting widespread in our organization. 

Error we are getting is : 
//
Flight Returned unavailable error, with message DNS resolution failed for enterprisedremio-flight.xxxxxxxxxxxxxxxx.net:443: C-ares status is not ARES_SUCCESS qtype=A name=enterprisedremio-flight.xxxxxxxxxxxxxxxx.net is_balancer=0: Domain name not found. PLease ensure your encryption settings match the server
//

This is blocking a huge number of users in the org to establish connections to Dremio Platform.

Verion of arrow flight ODBC driver : arrow-flight-sql-odbc-0.9.1.194-win64.

Have not tested on Mac.

Please help to overcome this issue. let me know what all details would be needed.

Thanks and Regards
Arun

### Component(s)

FlightRPC

**Comment by lidavidm** [comment]
Properly speaking, this is a bug in gRPC and not something that Arrow Flight can do anything 
about. I would recommend asking the developers at https://github.com/grpc/grpc/, and if you search, this sort of problem is quite common. (Additionally, the ODBC driver is supported by Dremio, it is not part of the Arrow project.)

You can try setting the environment variable GRPC_DNS_RESOLVER to "native". See https://github.com/grpc/grpc/blob/master/doc/environment_variables.md

I would like to make this the default for Flight, but gRPC explicitly does not let you configure this in code (presumably because they prefer you use their homegrown DNS resolver instead of the system libraries, for whatever reason).

**Comment by Arunodaya-Das-Maersk** [comment]
Hello David,

Thank you so much for the guidance! I have been able to resolve by setting a new variable as GRPC_DNS_RESOLVER to "native" and it worked.
