### ISSUE TITLE
[Go] List offsets isn't adjusted by offset. Is that intentional?

### ISSUE THREAD

**Issue by thorfour** [apache/arrow#40204]
### Describe the usage question you have. Please include as many useful details as  possible.

I was slicing a list, and needed to access the new list view offsets. However I discovered that the `Offsets` function does not adjust the offsets by the underlying data offset. Whereas the `ValueOffsets` function does correctly adjust the offsets array. 

Is it intentional that `Offsets` returns the parent array's offsets?

https://github.com/apache/arrow/blob/280bc112b23976d2f17c07c638bb62702ac89e8a/go/arrow/array/list.go#L155

https://github.com/apache/arrow/blob/280bc112b23976d2f17c07c638bb62702ac89e8a/go/arrow/array/list.go#L167-L172

### Component(s)

Go

**Comment by zeroshade** [comment]
I don't think it was necessarily intentional, but there are likely areas throughout the codebase which operate under the assumption of the current behavior, along with anyone else who is currently using that function. So i'm not sure if I would be comfortable with changing the behavior rather than simply improving the documentation on it.

**Comment by thorfour** [comment]
Understood, I just wanted to understand if it was intentional and what if anything I was missing regarding that. Thanks for the answer!
