### ISSUE TITLE
[C#] Parquet to Arrow conversion

### ISSUE THREAD

**Issue by piyushdubey** [apache/arrow#40258]
Hello,

I am trying to convert a Delta Table to an Arrow Stream.

The table can have any number of parquet files and may or may not be partitioned. I am using Parquet.Net to read Parquet Files. 

How should I think about parity between parquet files and RecordBatch. Should I create one RecordBatch per parquet file? What should the overall parquet to arrow conversion logic look like? Any pointers?

Here's a tentative algorithm I have in mind. 

1. Iterate over the list parquet files
2. Read `ParquetRowGroupReader reader = parquetReader.OpenRowGroupReader(rowGroupIndex);`
3. Extract Columns and Add them to a record batch one by one
4. Read RecordBatch into ArrowStreamWriter().

Appreciate any help with this.

### Component(s)

C#

**Comment by adamreeve** [comment]
As an alternative to Parquet.Net, you could use ParquetSharp, which wraps the Arrow C++ Parquet library and has built-in support for reading Parquet files as Arrow record batches: https://github.com/G-Research/ParquetSharp/blob/master/docs/Arrow.md

Disclaimer: I'm a maintainer of ParquetSharp

But otherwise your algorithm seems sensible. I'd only suggest you might want one RecordBatch per row group rather than per file, in case your files contain many row groups and could be large.

**Comment by CurtHagenlocher** [comment]
Marking this as closed. In the absence of an "official" Apache C# implementation of a Parquet reader, I think there isn't much to add here. Interestingly, early versions of Parquet.Net also had an Arrow API but it was removed because the maintainer didn't see any advantage to it. (Utilization of Arrow was much less widespread in those days.)

**Comment by piyushdubey** [comment]
Got it. Thanks @CurtHagenlocher

**Comment by piyushdubey** [comment]
> As an alternative to Parquet.Net, you could use ParquetSharp, which wraps the Arrow C++ Parquet library and has built-in support for reading Parquet files as Arrow record batches: https://github.com/G-Research/ParquetSharp/blob/master/docs/Arrow.md
> 
> Disclaimer: I'm a maintainer of ParquetSharp
> 
> But otherwise your algorithm seems sensible. I'd only suggest you might want one RecordBatch per row group rather than per file, in case your files contain many row groups and could be large.

Thanks @adamreeve - Looks like eventually I will need to move to ParquetSharp only. Arrow conversion with other Parquet parsers is pretty tedious to work with.
