### ISSUE TITLE
`df.to_parquet('s3://...', partition_cols=...)` fails with `'NoneType' object has no attribute '_isfilestore'`

### ISSUE THREAD

**Issue by vshih** [apache/arrow#4030]
According to https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#partitioning-parquet-files, writing a parquet to S3 with `partition_cols` should work, but it fails for me.  Example script:

```python
import pandas as pd
import sys

print(sys.version)
print(pd.__version__)
df = pd.DataFrame([{'a': 1, 'b': 2}])

df.to_parquet('s3://my_s3_bucket/x.parquet', engine='pyarrow')
print('OK 1')

df.to_parquet('s3://my_s3_bucket/x2.parquet', partition_cols=['a'], engine='pyarrow')
print('OK 2')
```

Output:
```
3.5.2 (default, Feb 14 2019, 01:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]
0.24.2
OK 1
Traceback (most recent call last):
  File "./t.py", line 14, in <module>
    df.to_parquet('s3://my_s3_bucket/x2.parquet', partition_cols=['a'], engine='pyarrow')
  File "/Users/vshih/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/core/frame.py", line 2203, in to_parquet
    partition_cols=partition_cols, **kwargs)
  File "/Users/vshih/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/io/parquet.py", line 252, in to_parquet
    partition_cols=partition_cols, **kwargs)
  File "/Users/vshih/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pandas/io/parquet.py", line 118, in write
    partition_cols=partition_cols, **kwargs)
  File "/Users/vshih/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pyarrow/parquet.py", line 1227, in write_to_dataset
    _mkdir_if_not_exists(fs, root_path)
  File "/Users/vshih/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pyarrow/parquet.py", line 1182, in _mkdir_if_not_exists
    if fs._isfilestore() and not fs.exists(path):
AttributeError: 'NoneType' object has no attribute '_isfilestore'
```

**Comment by emkornfield** [comment]
Hi @vshih would you mind filing an JIRA issue at https://issues.apache.org on the bug?

**Comment by vshih** [comment]
Created - https://issues.apache.org/jira/browse/ARROW-5156

**Comment by emkornfield** [comment]
Thanks.

**Comment by getsanjeevdubey** [comment]
@vshih Is this fixed?

**Comment by getsanjeevdubey** [comment]
@emkornfield Any fixes for that?

**Comment by emkornfield** [comment]
@getsanjeevdubey please track the JIRA instead of this issue.

**Comment by mykvvv** [comment]
Hi Guys,

issue is with s3fs library. because same code if you will use in your local env. it will work fine. but when you give AWS s3 path and use s3fs library with pandas then you will see such issue.

work around is below:

import pyarrow.parquet as pq
import pyarrow as pa
from s3fs import S3FileSystem
import pandas as pd

df = pd.DataFrame({"a": [0, 0, 1, 1], "b": [0, 1, 0, 1]})
s3 = S3FileSystem(key=ACCESS_KEY_ID, secret=SECRET_ACCESS_KEY)
table = pa.Table.from_pandas(df)

pq.write_to_dataset(table=table,root_path='s3://bucket-name/key-path',filesystem=s3,compression='snappy',partition_cols = ['a']) 

may be this can help others arriving here.
