### ISSUE TITLE
[Ruby] Create simple example of Ruby HTTP GET Arrow client

### ISSUE THREAD

**Issue by ianmcook** [apache/arrow#40478]
### Describe the enhancement requested

Contribute a Ruby client example to the [set of minimal HTTP GET examples in the `arrow-experiments` repo](https://github.com/apache/arrow-experiments/tree/main/http/get_simple).

### Component(s)

Ruby

**Comment by amoeba** [comment]
Thanks for adding https://github.com/apache/arrow-experiments/pull/17 @kou. Were you planning on sending a PR for a client too? I haven't started yet.

**Comment by kou** [comment]
I was planing on helping you for a client because you mentioned it on the mailing list: https://lists.apache.org/thread/6xs7l0tx6wrsxv19j1vv9o79fb5lqv3d
I worked on this because a server example is a bit difficult.

If you're interested in writing Ruby code, I help you as a Ruby committer and Arrow committer. :-)
If not, I can send a PR for a client too.

**Comment by amoeba** [comment]
I'll put a PR for you to look at, I'd love the feedback.

**Comment by kou** [comment]
OK!
