### ISSUE TITLE
R version 15.0.1 won't install from source

### ISSUE THREAD

**Issue by BorgeJorge** [apache/arrow#40513]
### Describe the bug, including details regarding any error messages, version, and platform.

Here are the messages I get in RStudio:

![image](https://github.com/apache/arrow/assets/47008223/c0c1cd14-2b5b-4d3d-8293-5fb1326b4026)

### Component(s)

R

**Comment by assignUser** [comment]
A bit more info would be nice, I assume you are on windows? There is no source build on windows, we download pre-build libarrow binaries and to make sure that we fail gracefully we check if we can download "https://apache.jfrog.io/artifactory/arrow/r/". Can you check that this domain is not blocked on your system? Otherwise you could try again and it might have been a temporary issue on jfrogs site.

**Comment by BorgeJorge** [comment]
Sorry, yes, I'm on Windows, and I have access to jfrogs from another machine and IP address, so it looks like I was blocked. Sorry to have troubled you, thanks for responding so quickly!

**Comment by assignUser** [comment]
No worries, happy to help. If you need to install on an air gapped system you can build the binary on another system or we also support giving the path to a predownloaded binaries. (but it doesn't sound like you need that atm so I will close this for now :) )
