### ISSUE TITLE
[Go] Unable to JSON marshal float64 arrays which contain a NaN value

### ISSUE THREAD

**Issue by xxgreg** [apache/arrow#40563]
`array.Float64.MarshallJSON()` returns the following error for the example code below:

```
json: unsupported value: NaN
```

```go
package main

import (
	"fmt"
	"math"

	"github.com/apache/arrow/go/v16/arrow/array"
	"github.com/apache/arrow/go/v16/arrow/memory"
)

func main() {

	builder := array.NewFloat64Builder(memory.DefaultAllocator)
	builder.Append(math.NaN())

	array_ := builder.NewArray()

	bs, err := array_.MarshalJSON()
	if err != nil {
		fmt.Println("error:", err)
	}

	fmt.Println(string(bs))
}
```

Consider updating the marshalling code for Float64 and other floating point array types with something like:

```
func (a *array.Float64) MarshalJSON() ([]byte, error) {
	vals := make([]any, a.Len())
	for i := 0; i < a.Len(); i++ {
		if !a.IsValid(i) {
			vals[i] = nil
			continue
		}

		f := a.Value(i)
		switch {
		case math.IsNaN(f):
			vals[i] = "NaN"
		case math.IsInf(f, 1):
			vals[i] = "+Inf"
		case math.IsInf(f, -1):
			vals[i] = "-Inf"
		default:
			vals[i] = f
		}
	}

	return json.Marshal(vals)
}
```

### Component(s)

Go

**Comment by zeroshade** [comment]
Hmm, if we do this we'd probably need to also update the corresponding `UnmarshalJSON` code to properly handle NaN so that we're still symmetrical. I'll mark this as a "good first issue" for someone to pick up

**Comment by verma-kartik** [comment]
@zeroshade @xxgreg I would like to make the above changes. I can assign myself via `take` right? 
Also, I tried the changes on local, and the change is working as expected. I observed that: 
1. I did not find any unit test for `MarshalJSON()` and `UnmarshalJSON`, shall I also add them to for this issue?
2. /go/arrow/array has separate files for handling Float16 data type, but Float32, Float64, and others are together in numeric.gen.go. Is there an explicit reason to do so or just technical debt to break numeric.gen.go in multiple files?

**Comment by zeroshade** [comment]
Hey @verma-kartik, using `take` would indeed assign yourself to this issue. It would also assign you automatically if you file a PR containing `GH-30563` in it's title.

As for your observations:

> There are not any unit tests for MarshalJSON() and UnmarshalJSON, shall I also add them to for this issue?

While there aren't tests that `explicitly` call `MarshalJSON` and `UnmarshalJSON` they are both indirectly tested via https://github.com/apache/arrow/blob/main/go/arrow/array/util_test.go and https://github.com/apache/arrow/blob/main/go/arrow/array/json_reader_test.go which call `FromJSON`, use `json.Marshal` and use a `json.Reader` respectively. So you should be able to add the relevant tests for this into one of those files.

> 2. /go/arrow/array has separate files for handling Float16 data type, but Float32, Float64, and others are together in numeric.gen.go. Is there an explicit reason to do so or just technical debt to break numeric.gen.go in multiple files?

The reason why Float16 is separate from those is due to the fact that the code gen has to handle `float16.Num` as opposed to just using `float16` like it can do with the other data types which are native. Ideally, the technical debt here would be to replace the `numeric.gen.go` file to utilize Go generics instead.

**Comment by verma-kartik** [comment]
take

**Comment by verma-kartik** [comment]
@zeroshade Thanks for pointing me in the right direction for tests.

**Comment by verma-kartik** [comment]
@zeroshade  @xxgreg  `math.inf()` is of type `float64`. I have two approaches on how to handle these for `float32`:
Either, typecast the value to float64 before checking for `math.IsInf()`,
```go
...
case math.IsInf(float64(f), 1):
      vals[i] = "+Inf"
...
``` 
Or, use the `math.Float32frombits()` to interpret the uint32 value of IEEE-752 of +Inf as float32,
```go
...
case math.Float32frombits(0x7F800000) == f:
      vals[i] = "+Inf"
...
``` 
Similarly for handling NaN and -Inf.

**Comment by zeroshade** [comment]
Personally, I would just use `strconf.FormatFloat` which will properly handle the `+Inf`, `-Inf` and `NaN` cases for 32 or 64 bit floats....

**Comment by zeroshade** [comment]
Issue resolved by pull request 41109
https://github.com/apache/arrow/pull/41109

**Comment by xxgreg** [comment]
🎉  Thanks team! @verma-kartik @zeroshade
