### ISSUE TITLE
[Python] Issue to install pyarrow and pandas together in a conda environment

### ISSUE THREAD

**Issue by Mathias5** [apache/arrow#41067]
### Describe the bug, including details regarding any error messages, version, and platform.

Hi,
since a few days when I create a conda environment with pyarrow and pandas, I get a segmentation fault when loading pandas.
To replicate:
conda create -n test python pyarrow pandas
conda activate test
python
import pandas

This leads to a segmentation fault.

### Component(s)

Python

**Comment by jorisvandenbossche** [comment]
Can you show the output of `conda list`? Do you see any traceback or error message besides "segmentation fault"?

This is _probably_ a conda packaging issue.

**Comment by xshirax** [comment]
Hi. I believe the issue is related to new release of snappy 1.2.0
This issue is solved with snappy 1.1
I get same bug (segmentation fault). specifically:

File "/homes/.../.conda/envs/.../lib/python3.10/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
ImportError: /homes/.../.conda/envs/.../lib/python3.10/site-packages/pyarrow/../../.././liborc.so: undefined symbol: _ZN6snappy11RawCompressEPKcmPcPm

**Comment by jorisvandenbossche** [comment]
If that was the issue, that should be solved now when recreating a fresh environment, see https://github.com/apache/arrow/issues/41058

But, that issue should only have occurred since yesterday, and not for a "few days" (and it's also not a segmentation fault)

**Comment by Mathias5** [comment]
Hi,
Indeed I think it started to happen yesterday and not "a few days ago" as I initially said.
And it did cause segmentation fault in my python env.
It seems like it has been resolved now, thanks for the update.

**Comment by Mathias5** [comment]
The issue has been resolved, see https://github.com/apache/arrow/issues/41058
