### ISSUE TITLE
[R][CI] CRAN-style openssl not being picked up

### ISSUE THREAD

**Issue by assignUser** [apache/arrow#41426]
### Describe the bug, including details regarding any error messages, version, and platform.

We noticed in #41403 that the binary package build doesn't pick up the CRAN mac-recepies openssl. https://github.com/ursacomputing/crossbow/actions/runs/8872579257/job/24357521438#step:16:561

Likely because we switched to gh hosted runners that don't have it installed. See https://mac.r-project.org/bin/

### Component(s)

Continuous Integration, R

**Comment by jonkeane** [comment]
I believe this is also causing the builds we are hosting to be slightly busted. I just tried installing a nightly on arm64 and found that gzip wasn't enabled.

Which makes sense since we create these binaries after failing to find openssl, but with a minimal build: https://github.com/ursacomputing/crossbow/actions/runs/8891743595/job/24415201349#step:16:72

**Comment by jonkeane** [comment]
@assignUser Have you had a chance to figure out what's going wrong here?

**Comment by assignUser** [comment]
Not yet sorry but I think the fix _should be easy_(tm) I'll have a look overt the weekend.

**Comment by assignUser** [comment]
Issue resolved by pull request 41629
https://github.com/apache/arrow/pull/41629
