### ISSUE TITLE
[R] {arrow} 15.0.1 fails R CMD check on macOS (both arm64 and x86_64) & R4.4.0

### ISSUE THREAD

**Issue by dragosmg** [apache/arrow#41465]
### Describe the bug, including details regarding any error messages, version, and platform.

With the recent R [vulnerability](https://hiddenlayer.com/research/r-bitrary-code-execution/) I imagine many folks would want to upgrade to R4.4.0 (or whatever release included the patch) -> they will have to re-install arrow. Currently the latest binary version users can get is 14.0.0.2. They'd have to install from source if they wanted 15.0.1, but that fails. 

https://cran.r-project.org/web/checks/check_results_arrow.html
https://www.r-project.org/nosvn/R.check/r-release-macos-arm64/arrow-00check.html
https://www.r-project.org/nosvn/R.check/r-release-macos-x86_64/arrow-00check.html

### Component(s)

R

**Comment by assignUser** [comment]
Hey! 

16.1 will be released soon before that there is nothing we can do. The error is due to having gnulibtool on the path (which brew explicitly advises against to prevent situations such as this).

Until then I'd recommend using the r-universe version of arrow as the Mac binaries on cran have (unintentionally) only minimal features.

**Comment by thisisnic** [comment]
Hey @dragosmg, good to see you again, and thanks for reporting this!  I'm closing this issue now as 16.1.0 is out.
