### ISSUE TITLE
pyarrow.lib.BooleanArray.true_count causing kernel to die in Jupyter

### ISSUE THREAD

**Issue by kyle-hex** [apache/arrow#41642]
### Describe the bug, including details regarding any error messages, version, and platform.

Hi,

python version = 3.9.12
pyarrow version = 15.0.1

Was attempting to test a relatively simple piece of code in Jupyter using pyarrow and came across a very strange error after attempting to return the "true_count" attribute of a BooleanArray:

![image](https://github.com/apache/arrow/assets/109384837/aacf7bcf-8a66-4389-9cea-d95f4487919f)
![image](https://github.com/apache/arrow/assets/109384837/ada3f05e-19b7-4a7f-ab21-2e9eeccee7c1)
![image](https://github.com/apache/arrow/assets/109384837/a83f0ea6-3486-4bb3-8b11-29634b3566c9)

As you can see, this causes the kernel to die in Jupyter.  I tried returning the "false_count" attribute and had no problem:

![image](https://github.com/apache/arrow/assets/109384837/e4144fb3-636b-4ed6-921d-d9e55553a05b)

I recreated this error in multiple different environments and versions as well.

Any help would be appreciated. 

Thanks

### Component(s)

Python

**Comment by amoeba** [comment]
Hello! This looks like the same issue as reported here: https://stackoverflow.com/questions/78474673/the-kernel-appears-to-have-died-error-in-jupyter-while-using-pyarrow.

The underlying problem is a crash which was reported as [GH-41016](https://github.com/apache/arrow/issues/41016) and a fix was included in the 16.0.0 release so a solution here is to upgrade. I'm going to close this but please feel free to re-open it if I'm mistaken.
