### ISSUE TITLE
[Packaging][deb] libarrow1600 shoud be libarrow1601 for 16.1.0

### ISSUE THREAD

**Issue by kou** [apache/arrow#41679]
### Describe the bug, including details regarding any error messages, version, and platform.

`XXX` in `libarrowXXX` should match to `XXX` in `libarrow.so.XXX`.

### Component(s)

Packaging

**Comment by raulcd** [comment]
This seems to happen only on minor releases `16.1.0` but not for patch releases. Is there a reason we update those on MINOR? Do we want to change the ABI? This is related to the discussion on conda here: https://github.com/conda-forge/arrow-cpp-feedstock/pull/1409#issuecomment-2116372762

**Comment by h-vetinari** [comment]
@kou, in https://github.com/conda-forge/arrow-cpp-feedstock/issues/1096 you asked to use a major-level pinning, indicating that the ABI (and thus the SOVERSION!) stays unchanged over the course of a given major.

In any case, the SOVERSION definitely shouldn't change for patch versions (unless you plan to allow ABI breaks there). The builds for 16.1.0 currently [produce](https://conda-metadata-app.streamlit.app/?q=conda-forge%2Flinux-64%2Flibarrow-16.1.0-hefa796f_0_cpu.conda):
```
lib/libarrow.so
lib/libarrow.so.1601
lib/libarrow.so.1601.0.0
```
You can have both the major-level ABI-stability _and_ the more granular detail if you do something like:
```
lib/libarrow.so
lib/libarrow.so.16
lib/libarrow.so.16.1.0
```
(ignoring for a second that you probably cannot go back from 1601 to 16; it could be `1700.<minor>.<patch>` for arrow 17 though)

**Comment by jorisvandenbossche** [comment]
@kou do you mean for 16.1.0 instead of 16.0.1? (the title of the issue says 16.0.1)

**Comment by vyasr** [comment]
This will be review for most people discussing here, but just wanted to summarize explicitly to make sure we're clear and all on the same page:

### Status quo
- `SOVERSION=${MAJOR}${MINOR}` (so version 16.1.0 produces libarrow.so.1601, while version 16.0.1 produces libarrow.so.1600)
- Patch versions are promised to be ABI-compatible (but this is not explicitly verified in any way)
- Minor versions are not promised to be ABI-compatible

### Conservative solution
- `SOVERSION=${MAJOR}${MINOR}${PATCH}` (so version 16.1.0 produces libarrow.so.160100, while version 16.0.1 produces libarrow.so.160001)
- Assumes a completely unstable ABI
- Might be the most strictly accurate claim at the moment
- Would be quite painful for consumers

### Desired state
- `SOVERSION=${MAJOR}` (so version 16.1.0 and version 16.0.1 produce libarrow.so.16)
- Both minor and patch versions are promised to be ABI-compatible
- This may not be possible for arrow right now.

### Summary
If minor or patch releases can break ABI, then the SOVERSION must reflect that so that libraries built against libarrow have the appropriate requirements baked into the executable (e.g. DT_NEEDED entries in ELF files). Downstream of the library, packaging metadata (in particular, conda metadata as is being discussed in https://github.com/conda-forge/arrow-cpp-feedstock/pull/1409) must account for this by setting runtime dependencies of dependents of libarrow to account for the right version of libarrow at runtime. Making a decision on https://github.com/apache/arrow/issues/41707 (i.e. clarifying the intended stability promises) is the first thing to be done, then we can work on updating packaging files.

**Comment by kou** [comment]
Oh, sorry. I was wrong. I've fixed the typo.

**Comment by jorisvandenbossche** [comment]
@vyasr  can you move that comment to https://github.com/apache/arrow/issues/41707? My understanding is that this issue is specifically about deb packages

**Comment by vyasr** [comment]
Yup, moved to https://github.com/apache/arrow/issues/41707#issuecomment-2121476149. Thanks for the ping.

**Comment by jorisvandenbossche** [comment]
@vyasr thanks!

**Comment by kou** [comment]
@h-vetinari Sorry... I was wrong... We should have used a minor-level pinning.

**Comment by kou** [comment]
It seems that we have a logic for this: https://github.com/apache/arrow/blob/1c9e393b73195840960dfb9eca8c0dc390be751a/dev/release/post-11-bump-versions.sh#L70-L105

But it seems that we don't run `post-11-bump-versions.sh` for minor release.
@raulcd Could you tell us what `post-*.sh` are used (or what `post-*.sh` are not used) for minor release?

We may need to do this in `01-prepare.sh`.

**Comment by raulcd** [comment]
I do run all `post-*.sh` scripts after a minor release but this is done after the release. We do set the final released version number on `01-prepare.sh` so if we want to do any changes I do think it should be there. This is the commit that was created when setting the version for `16.1.0` on `01-prepare.sh`:
https://github.com/apache/arrow/commit/7dd1d34074af176d9e861a360e135ae57b21cf96

The `post-11-bump-versions.sh` sets the new snapshot versions and prepares `main` for the next `major` version number.

**Comment by kou** [comment]
Issue resolved by pull request 41859
https://github.com/apache/arrow/pull/41859
