### ISSUE TITLE
[R] RStudio crash

### ISSUE THREAD

**Issue by jsicherman** [apache/arrow#43241]
### Describe the bug, including details regarding any error messages, version, and platform.

I have some code which reads a parquet file, does a bit of processing, and returns the result in a loop, and it leads to sporadic crashes of my RStudio instance. The R code looks something like this...

```
foo <- lapply(1:1000, function(i) {
    read_parquet(
        file.path('data', i, 'bar.parquet')],
        as_data_frame = F
    ) %>%
    select(A, B, C, D) %>%
    mutate(E = D + 1) %>%
    left_join(tibble.frame(A = 1:3, F = 6:8), by = 'A') %>%
    group_by(A, B) %>%
    summarise(
        G = n()
    ) %>% collect %>% as.data.table
}) %>% rbindlist
```

It will eventually crash, seemingly at random, either early or late in the loop. The following is logged under `systemctl status rstudio.service -l`

```
ERROR The previous R session terminated abnormally; LOGGED FROM: rstudio::core::Error {anonymous}::rInit(const rstudio::r::session::RInitInfo&) src/cpp/session/SessionMain.cpp:725
```

```
R version 4.2.1 (2022-06-23)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Amazon Linux 2

> package.version('arrow')
[1] "9.0.0"

> RStudio.Version()
$mode
[1] "server"

$edition
[1] "Professional"

$version
[1] ‘2023.3.0.386.1’

$long_version
[1] "2023.03.0+386.pro1"

$release_name
[1] "Cherry Blossom"
```

### Component(s)

R

**Comment by jonkeane** [comment]
A few questions for you: Do you get the same behavior when you're outside of RStudio? Have you tried tracking memory usage while this is running? Have you tried isolating the components of your pipeline to see if any particular of those is the culprit (e.g. not doing the `left_join`, using a different parquet file, using `compute()` instead of `collect()`, removing the `data.table` transformation? Having a more targeted + minimal example would help diagnose this. Finally, can you chase the underlying parquet files that are causing the issue? I know in many cases folks can't but having a set of data that replicate is super powerful

**Comment by jsicherman** [comment]
Thanks for the quick response!

Running the script outside of RStudio (but using the same R binary) runs to completion consistently (ran 5 full passes through with no crashes, where inside RStudio I would crash every 4-7 loop iterations).

I actually seem to get the same crash in RStudio if I do nothing but `arrow::read_parquet(..., as_data_frame = F)` interactively for my files, whether in a loop or not. I will try to generate a minimal example parquet file to share here, but I suspect this is more likely something to do with my RStudio install

**Comment by jonkeane** [comment]
> I will try to generate a minimal example parquet file to share here, but I suspect this is more likely something to do with my RStudio install

Yeah, agreed that does sound like something about how you've setup RStudio. I'm going to close this since it so far seems that this isn't an Arrow issue, but if you get more information please feel free to reopen it or make a new issue!
