### ISSUE TITLE
[R] How to pass Arrow objects like Table between C++ and R?

### ISSUE THREAD

**Issue by ajinkya-k** [apache/arrow#43675]
### Describe the usage question you have. Please include as many useful details as  possible.

I was curious how I can pass arrow objects from `R` to `C++` (kind of like `R` vectors via `Rcpp::NumericVector`). Here's an example of what I am looking for:

Say I have a function `sample_post` in `R` that takes in an `arrow` table and some parameters:
```
# R code
sample_post <- function(arrow_tbl, some_vec, params) {
    # do some clean up
    post_object <- .some_rcpp_fn(arrow_tbl, some_vec, params)

    # do some processing on the post object
   return(post_object)
}
```

For a little more concreteness, let's say `some_fn_cpp` is doing `group_by` summaries in each iteration of a loop. 
In `some_fn_rcpp` what should be the type for the first argument that corresponds to `arrow_tbl`? 

NOTE: I would prefer using `Rcpp` but not tied to it. I am okay using something else. 

### Component(s)

R

**Comment by assignUser** [comment]
Do you want to operate on the arrow table with libarrow or some custom C++ code (potentially using other  libraries)?

**Comment by ajinkya-k** [comment]
I want to use custom C++ code that will need other libraries

**Comment by assignUser** [comment]
Sorry for the late reply, I am not sure that's possible with cpp11 (which the arrow uses)  but that's not my speciality.  I found this related issue: https://github.com/apache/arrow/issues/36274

**Comment by ajinkya-k** [comment]
So is this an inherent limitation of cpp11?

**Comment by assignUser** [comment]
I don't really know, sorry. Maybe @jonkeane  or @paleolimbot can chime in?

**Comment by amoeba** [comment]
The examples given in https://github.com/apache/arrow/issues/36274 should be stable because they use the [Arrow C Data Interface](https://arrow.apache.org/docs/format/CDataInterface.html), with the help of the [`nanoarrow`](https://arrow.apache.org/nanoarrow/latest/index.html) package, to pass the `arrow::Table` between C++ and R. My interpretation of @paleolimbot 's comment was that it's specifically passing pointers to `arrow::Table`s that's not considered stable. But going through the C Data Interface is stable and is even the Arrow project's recommended way of doing this kind of thing.

**Comment by ajinkya-k** [comment]
Thanks! I will give it a try

**Comment by amoeba** [comment]
Hi @ajinkya-k, I'm going to close this for now but please feel free to re-open and/or comment here. I'm curious if you were able to get something to work.
