### ISSUE TITLE
[C++] Patch Snappy config to avoid disabling RTTI

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#43688]
### Describe the enhancement requested

Snappy's `CMakeLists.txt` unconditionally disables RTTI. This is incompatible with some other options, such as activating UBSAN for a fuzzing build:
https://github.com/google/snappy/issues/189

We should probably patch Snappy's `CMakeLists.txt`  in our bundled build of Snappy.

### Component(s)

C++, Continuous Integration

**Comment by pitrou** [comment]
@kou Does this sound reasonable to you?

**Comment by kou** [comment]
I don't want to require `patch` as much as possible because it's difficult that preparing `patch` on some environments as you noticed: https://github.com/apache/arrow/pull/43689#discussion_r1716945455

How about using `CMAKE_CXX_FLAGS_<CONFIG>` to override `-fno-rtti` instead of using `patch`?

```diff
diff --git a/cpp/cmake_modules/ThirdpartyToolchain.cmake b/cpp/cmake_modules/ThirdpartyToolchain.cmake
index 495aa70483..263f9d91ea 100644
--- a/cpp/cmake_modules/ThirdpartyToolchain.cmake
+++ b/cpp/cmake_modules/ThirdpartyToolchain.cmake
@@ -1365,6 +1365,13 @@ macro(build_snappy)
     endforeach()
   endif()
 
+  foreach(CONFIG DEBUG MINSIZEREL RELEASE RELWITHDEBINFO)
+    list(APPEND
+         SNAPPY_CMAKE_ARGS
+         "-DCMAKE_CXX_FLAGS_${UPPERCASE_BUILD_TYPE}=${EP_CXX_FLAGS_${CONFIG}} -frtti"
+    )
+  endforeach()
+
   if(APPLE AND CMAKE_HOST_SYSTEM_VERSION VERSION_LESS 20)
     # On macOS 10.13 we need to explicitly add <functional> to avoid a missing include error
     # This can be removed once CRAN no longer checks on macOS 10.13
```

Or how about using patched Snappy in system? For example, Debian's Snappy enables RTTI ( https://sources.debian.org/patches/snappy/1.2.1-1/add_option_to_enable_rtti.patch/ ) and Conda's Snappy enables RTTI ( https://github.com/conda-forge/snappy-feedstock/pull/32 ).

**Comment by pitrou** [comment]
> How about using `CMAKE_CXX_FLAGS_<CONFIG>` to override `-fno-rtti` instead of using `patch`?

I can try this.

**Comment by pitrou** [comment]
However, your patch forces RTTI on everyone, which may not be better either.

**Comment by kou** [comment]
Everyone? The specified `-frtti` is only used by Snappy.

**Comment by pitrou** [comment]
Hmm, that's true. But I have no idea whether some configurations may not like RTTI being enabled. @felipecrv Do you have any insight on this?

**Comment by pitrou** [comment]
I posted https://github.com/apache/arrow/pull/43706 for your approach.

**Comment by kou** [comment]
Issue resolved by pull request 43706
https://github.com/apache/arrow/pull/43706
