### ISSUE TITLE
arrow R package read_parquet() support, reading individual columns from parquet file

### ISSUE THREAD

**Issue by mskyttner** [apache/arrow#4456]
I tried using the `arrow` R package for reading a parquet file with the released version of the package, following the instructions at "apache/arrow/r" and wonder if support for doing this may not be there yet?

Details of my attempts, with (hopefully) a reproducible build can be found here:

https://github.com/r-lib/vroom/issues/117#issuecomment-498225399

I wanted to read a single column from a parquet file which is about 4 GB on disk. Is this planned to be supported in the "read_parquet" function?

**Comment by nealrichardson** [comment]
Hi @mskyttner, thanks for the report. Regarding the build trouble you experienced, it turns out that in the 0.13 release (unofficial and still not on CRAN), Parquet support was not enabled by default. If you were to install the development version of the package (which also requires building the latest C++ library from source), it is enabled. 

As for the interface of `read_parquet()` and the ability only to load into memory the rows and columns you want, that is exactly the plan. Indeed, `pyarrow`, which uses the same C++ library, supports some of this already. I don't know that we have open JIRAs explicitly for this yet, but I'll point you at them when I find/make them so you can follow along.

**Comment by wesm** [comment]
> I wanted to read a single column from a parquet file which is about 4 GB on disk. Is this planned to be supported in the "read_parquet" function?

Definitely yes. In Python we have a `columns` option to indicate which columns you want to read, which can be a single columns, so the same should be done in R.

I created https://issues.apache.org/jira/browse/ARROW-5492
