### ISSUE TITLE
[Docs][Website] https://arrow.apache.org/docs/16.0/ doesn't exist

### ISSUE THREAD

**Issue by kou** [apache/arrow#44568]
### Describe the bug, including details regarding any error messages, version, and platform.

But our version list includes it:

https://github.com/apache/arrow/blob/2df7b23af717f505c16fedbef6e4223ac163ac5a/docs/source/_static/versions.json#L23-L27

Should we remove the entry or create https://arrow.apache.org/docs/16.0/ ?

### Component(s)

Documentation, Website

**Comment by amoeba** [comment]
Thanks for catching this. I think we should create it. Even though it's probably of minimal practical value, it's best that every release have a match docset. I notice we don't have a built copy at https://apache.jfrog.io/ui/native/arrow/docs/ any longer. Is it better to create it by hand or use one of the CI tasks we already use to create it?

**Comment by kou** [comment]
OK. I've restored https://apache.jfrog.io/ui/native/arrow/docs/16.0.0/ .
(I removed it because of our Artifactory space quota...)

**Comment by amoeba** [comment]
Nice. I suppose it's fine to remove it and even more recent versions like 16.1.0 once we're done here since the arrow-site repo has near-1:1 copies of the content. Let me know if you'd like me to create a PR for this. I think it should just require downloading the artifact and applying our version banner changes in post-10-docs.sh manually, right?

**Comment by kou** [comment]
Right. Could you work on this?

**Comment by amoeba** [comment]
I put up a PR for this if you want to take a look @kou https://github.com/apache/arrow-site/pull/555

**Comment by kou** [comment]
Done by https://github.com/apache/arrow-site/pull/555 .
