### ISSUE TITLE
[C#] Consider replacing LINQ expression when accessing columns by name

### ISSUE THREAD

**Issue by georgevanburgh** [apache/arrow#44575]
### Describe the enhancement requested

We've recently been doing some profiling of code that uses the C# Arrow library, and which frequently accesses columns by name in a tight loop - and found the following LINQ expression makes a significant contribution to execution time.

https://github.com/apache/arrow/blob/2df7b23af717f505c16fedbef6e4223ac163ac5a/csharp/src/Apache.Arrow/Schema.cs#L81-L86

Obviously there are workarounds for this, such as creating our own cached mapping of column names to ordinals - but it would be nice if the built-in method was a little more efficient. In addition to the use of linq, we're also iterating through `_fieldsList` twice (once to find a match, and then another to find the index of the match).

We've also noticed that usage of `StringComparer.CurrentCulture` causes an allocation every time this method is called (assuming a value for `comparer` is not provided). I'm assuming the choice to use a culture-aware comparison by default is intentional?

### Component(s)

C#

**Comment by CurtHagenlocher** [comment]
The use of `StringComparer.CurrentCulture` is definitely a head-scratcher. It apparently dates back to the very first checkin of the file. It's especially surprising because the very same checkin used `StringComparer.OrdinalIgnoreCase` to build the dictionary. While I ordinarily argue against making breaking changes, I think it might be justified this time.

I would expect the allocation to be a result of the closure that needs to be created to pass to `First`.

**Comment by CurtHagenlocher** [comment]
Issue resolved by pull request 44576
https://github.com/apache/arrow/pull/44576
