### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xalteropsx** [apache/arrow#44920]
AttributeError: module 'pyarrow' has no attribute 'serialize'  
keep change ur thing and dont let user know what was that 

what kind of library is this cannot even use more then 1 dimeions numpy array 

also intentionally removing serialize ?

**Comment by raulcd** [comment]
Thanks for your report. The serialization functionality was deprecated at version 2.0.0, it was marked on the docs as depreated and was removed 10 versions later at pyarrrow 12.0.0. Some more context here:

https://github.com/apache/arrow/issues/29705

**Comment by adamreeve** [comment]
Arrow is generally designed for columnar data rather than multi-dimensional arrays. But if you  have a 2d numpy array, you could convert it to an Arrow FixedSizeListArray. See https://stackoverflow.com/a/68010468

If you want to serialize data for inter-process communication, the Arrow IPC format can be used: https://arrow.apache.org/docs/python/ipc.html
