### ISSUE TITLE
[R] Support for AWS Linux images?

### ISSUE THREAD

**Issue by bneigher** [apache/arrow#6611]
Hey guys,

I'm running into issues getting a docker image loaded with arrow for use in my custom lambda R runtime. 

I've isolated the problem down to the following which I believe should be an easy change:

https://github.com/apache/arrow/blob/590a168554b6aab3f0c5b2bf3fc44e2b4fcfb27a/r/tools/linuxlibs.R#L40-L60

In the case of my amazon base image (in my case)
`Linux c37c1a2c08c9 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux` (The docker image is` lambci/lambda:build-provided`)

the os is returning `amzn-2018` which is 404ing :
```
In download.file(binary_url, libfile, quiet = quietly) :
  cannot open URL 'https://dl.bintray.com/ursalabs/arrow-r/libarrow/bin/amzn-2018/arrow-0.16.0.2.zip': HTTP status was '404 Not Found'
```

Since we can see here the following OSs have the C++ libs built
http://dl.bintray.com/ursalabs/arrow-r/libarrow/bin/
```
centos-7/
centos-8/
debian-10/
debian-9/
ubuntu-16.04/
ubuntu-18.04/
```

I'm essentially stuck in an endless arrow::install_arrow() loop as the installation fails each time.

When I call write_parquet I see an error implying missing C++ deps

```
Error in Table__from_dots(dots, schema) :
  Cannot call Table__from_dots(). Please use arrow::install_arrow() to install required runtime libraries.
```

related https://github.com/apache/arrow/issues/6448

Any guidance on how to work around this?  It ideally it be handled in `download_binary`, or allow the ability to pass in my OS name with an env var?

**Comment by nealrichardson** [comment]
You're close in where you're looking. Just below the code you linked to is: https://github.com/apache/arrow/blob/590a168554b6aab3f0c5b2bf3fc44e2b4fcfb27a/r/tools/linuxlibs.R#L62-L67

From googling around to see where Amazon Linux is derived from, you may have luck setting `LIBARROW_BINARY=centos-7`. See https://arrow.apache.org/docs/r/articles/install.html#using-prebuilt-binaries (but note that the env var name has changed since the docs were last published). Unfortunately, `lambci/lambda:build-provided` does not seem to have R installed, so I can't confirm that centos-7 works. 

That said, installation should not fail without finding a binary to download--it should be able to build from source. If it can't, please (1) check whether installing from our nightly build repo works, as there have been some improvements since the CRAN release, and if that still fails (2) report a Jira issue. If you can provide a Docker image that has R installed, we can easily plug it into our continuous integration setup.
