### ISSUE TITLE
Not found the package for centos-7.6.1810

### ISSUE THREAD

**Issue by yewero** [apache/arrow#6613]
When I type the command `arrow::install_arrow()` in R (3.6.1), I will find an error:
```
[skipped some text]
/ram/tmp/Rtmpk7fhep/R.INSTALL461c9411a0367/arrow
Warning message:
In download.file(binary_url, libfile, quiet = quietly) :
  cannot open URL 'https://dl.bintray.com/ursalabs/arrow-r/libarrow/bin/centos-7.6.1810/arrow-0.16.0.2.zip': HTTP status was '404 Not Found'
PKG_CFLAGS=-I/ram/tmp/Rtmpk7fhep/R.INSTALL461c9411a0367/arrow/libarrow/arrow-0.16.0.2/include  -DARROW_R_WITH_ARROW
PKG_LIBS=-L/ram/tmp/Rtmpk7fhep/R.INSTALL461c9411a0367/arrow/libarrow/arrow-0.16.0.2/lib -larrow_dataset -lparquet -larrow -lthrift -lsnappy -lz -lzstd -llz4 -lbrotlidec-static -lbrotlienc-static -lbrotlicommon-static -lboost_filesystem -lboost_regex -lboost_system -ljemalloc_pic
```
But finally the installtion was successful.

**Comment by nealrichardson** [comment]
Thanks. Note that that's a warning message, not an error. Installation would have been faster if the OS detection script had returned `centos-7` instead of `centos-7.6.1810` and a prebuilt library were downloaded, but as you observed, the source build still worked. You could also set the env var `LIBARROW_BINARY=centos-7` to skip OS detection and just use that one. See https://arrow.apache.org/docs/r/articles/install.html#using-prebuilt-binaries (note that the env var name has changed since the docs were published).

If you can provide a docker image that reproduces this, please create a Jira issue and I'm happy to try to improve the OS detection.
