### ISSUE TITLE
Make available Windows binaries arrow package for R 3.5.3

### ISSUE THREAD

**Issue by palamito** [apache/arrow#8078]
Would it be possible to make available the arrow package for R 3.5.3 (Windows binaries) ? 

Right now, the only R version that can install the arrow package (1.0.0) is > 4.0. However, I cannot upgrade to R 4.0 and I can only install arrow version 0.17 which is still compatible with R 3.5.3.

Is there a way to get the current arrow R package also available for R 3.5.3 ?

Thanks

**Comment by nealrichardson** [comment]
CRAN publishes binaries for current release (4.0) and oldrel (3.6); we don't have control over that. We do the same for the nightly builds we host on bintray. Due to resource limitations on our bintray account, we cannot publish packages for more versions, but you're free to fork/copy [those build scripts](https://github.com/ursa-labs/arrow-r-nightly/blob/master/.github/workflows/build-binary-packages.yml#L25) and build for 3.5.

**Comment by palamito** [comment]
Thank you so much @nealrichardson for your very helpful and quick answer. 

I have never built a package to adapt it to a previous R version. Could you give me some more hints on how to do it ?

Thanks

**Comment by palamito** [comment]
I eventually managed to get version 1.0.1 to work on R 3.5.3.

To do so, I built the source package on a Windows machine with R 3.5.3 and Rtools 35. From the Command line, type `R CMD INSTALL --build pkg` (where `pkg' is either the name of a source tarball (in the usual `.tar.gz' format) or the location of the directory of the package source to be built).

Once built, zip the package files and it should work.

[arrow_1.0.1_for_3.5.3.zip](https://github.com/apache/arrow/files/5146452/arrow_1.0.1_for_3.5.3.zip)
