### ISSUE TITLE
How to filter parquet column with None using Python?

### ISSUE THREAD

**Issue by deamontg** [apache/arrow#9160]
I'm trying to read a parquet file using pyarrow read_table(), and I would like to filter columns using None. I've tried something like the following:

```
import pyarrow as pa
import pyarrow.parquet as pq
table = pa.Table.from_arrays([[None, None, 'a', 'b', 'a', 'c']], names=['column'])
pq.write_table(table, 'data.parquet')

# Attempt No. 1
table = pq.read_table('data.parquet', filters=[[('column', '=', None)]])

# Attempt No. 2
table = pq.read_table('data.parquet', filters=[[('column', '=', pa.scalar(None))]])

# Attempt No. 3
table = pq.read_table('data.parquet', filters=[[('column', '=', pa.scalar(None, type=pa.string()))]])
```

This example does not work for either of the three attempt methods. In all cases, the read-in table contains no records. How can I properly filter a column for None values when reading a table?

**Comment by jorisvandenbossche** [comment]
The problem is that a null is not equal to itself, so you can't filter nulls with an `==` equality check. 

For the new dataset API, we are working on more powerful filter expressions, and you can already achieve this:

```
In [21]: import pyarrow.dataset as ds

In [22]: pq.read_table('data.parquet', filters=~ds.field("column").is_valid()).to_pandas()
Out[22]: 
  column
0   None
1   None
``` 

We should probably also add a `is_null()` method to make this case a bit more straightforward. 


---

General note: we prefer the user mailing list for such questions, see https://arrow.apache.org/community/

**Comment by deamontg** [comment]
Doing it this way works! Thanks for your help.

**Comment by rooneyp** [comment]
FWIW I got it working using 'not in' operator
`filters=[('deletionTime', 'not in', [None])]`

this was done via pandas, but I think it just passes the filters down to pyarrow
`pd.read_parquet(pq_path, engine='pyarrow',  columns=cols, storage_options=None,                                     use_nullable_dtypes=True, filters=filters)
`
