### ISSUE TITLE
[Rust] Arrow/Parquet/Datafusion interop not possible?

### ISSUE THREAD

**Issue by Anonyfox** [apache/arrow#9420]
Hello, I have a just played with the new 3.0 crates of the arrow family, and keep hitting a wall for hours now. 

1. I started with arrow itself, and built a large StructArray with my data. This was the easy part. 

2. To cache this bigStructArray, I'd like to cache it as parquet file to disk. Seems like I can not use the parquet crate to achieve this, and the arrow crate has nothing useful, either. (CSV/JSON is not an option, this would en in a custom binary format again)

3. Now the most disappointing part: It is absolutely unclear for me how I would query the StructArray (like: give me all records where column_X = Y, and so on) there a compute kernels in the docs but how to use it is completely unclear for me. Then I saw the datafusion crate which looks exactly like what I want, but... again no hint how to use my StructArray from memory. 

I had the impression that the point of arrow, as a portable memory structure, is exactly this. And these crates do use arrow internally... Did I get something totally wrong? May someone give me a few hints what I'm missing (save/load/query)? It would be sad to go back to my large rust Vec<Item> blobs and manually iter()/filter() stuff. 

Thanks in Advance!

**Comment by nevi-me** [comment]
Hi @Anonyfox, thanks for reaching out to the project. I can understand your frustration at hitting walls. What you're trying to do isn't as trivial as it should be, mainly because we don't yet have a lot of comprehensive guides on how the various crates in the ecosystem interop.

@elferherrera has started https://elferherrera.github.io/arrow_guide/reading_parquet.html, and perhaps a guide that could help unblock you, could live there.

Do you mind sharing the schema of your StructArray? It sounds like you should be creating a RecordBatch from the StructArray, where it'll be easier to save it to Parquet (or the Arrow IPC format, which would address the CSV/JSON concern).

Based on the schema that you share, we can then look at how to help out.

Thanks

**Comment by Anonyfox** [comment]
Maybe I just took some wrong directions, therefore I'll outline what I want to achieve with some snippets. So, this resembles my basic struct: 

```
pub struct Book {
    /// NOT unique, but known to be ascii with fixed length of 10
    pub code: String,
    pub authors: u8,
    pub reviewers: u8,
    pub title: String,
    pub keywords: Vec<String>,
    pub price: f32,
    pub is_english: bool,
   // ... more fields of mostly Strings
}

And I have a few millions of them, as `Vec<Book>`. Now to illustrate the use case a bit more, I have a Library like this: 

```
pub struct Library {
    // will be updated when purchasing/... happens
    local_books: Vec<Book>,
    // will be updated periodically from a remote source
    external_books: Vec<Book>,
}
```

In my application there exists a lazy static `RwLock<Library>`, which receives many read queries per second (_"how many books written by 3 authors have you?"_) where I have to lookup in `local_books` and if nothing is found there perform the same lookup in `external_books`, returning the final result. 

Works okayish, but consumes quite a bit of RAM and I have to build "queries" manually using chains of `iter()`/`filter()`. 

My thought now was that I can leverage Arrow and it's friends to make this thing more efficient, at least not slower, and have dynamic SQL-ish queries for easier development. 

Now after playing around even more, especially with datafusion, I got a working state of this (leveraging RecordBatches as you hinted): 

```
pub struct Library {
    local_books: MemTable,
    external_books: MemTable,
}
```

where the table schema looks like this for both MemTables: 

```
vec![
        Field::new("code", DataType::Utf8, false), // fixed size binary seems to not work yet in datafusion
        Field::new("authors", DataType::Int8, false), // u8 -> i8 cast is safe in my case
        Field::new("reviewers", DataType::Int8, false), // u8 -> i8 cast is safe in my case
        Field::new("title", DataType::Utf8, false),
        Field::new("keywords", DataType::Utf8, true), // joined the Vec<String> with `',`', couldn't get ListTable to work
        // ...
]
```

Now the hard wall I faced: actually querying the table! I tried something like this: 

```
impl Library {
    pub async fn count(&self) -> Result<usize> {
        let mut ctx = ExecutionContext::new();
        ctx.register_table("local_books", Box::new(self.local)); // doesn't work, attempting move
        let sql = "SELECT COUNT(*) FROM local_books";
        let results = ctx.sql(&sql)?.collect().await?;
        // ... returning the count
        todo!()
    } 
}
```

- the `ExecutionContext` needs to be mutable, so I must generate a new one for each call (or: must do once I have dynamically parameterized calls)
- `register_table()` only accepts `dyn TableProvider`, not a reference or an `Arc` or anything else that would not need deep cloning
- my tables are quite large, so I really want to reuse them once generated, and they might be replaced (outer RwLock) while the application is running
- caching things on disk is trivial with serde for `Vec<Book>` but requires much disk space, and while _writing_ is allowed to take a few seconds without issue, _reading_ the dump must be really fast
- I found literally zero hints how to serialize/deserialize the MemTable from/to parquet in the docs/examples

**Comment by abreis** [comment]
The insight here is that cloning a `MemTable` is actually cheap. `MemTable`s hold `RecordBatch`es, which themselves are built from `ArrayRef`s (i.e., `Arc<dyn Array>`).

This seems to be an anti-pattern though, so much so that `MemTable` doesn't implement `Clone`. You'd probably want to store `RecordBatch`es in your `Library` instead, and build `MemTable`s from them whenever you want to add them to the context (`RecordBatch`es are `Clone`).

This also means that adding record batches to the context is cheap, and that the context doesn't own those batches. If you want to refresh data in the context, however, you'll need to unregister the table and reregister it with the new data. If you don't do this, when you hold your batches behind an `RwLock` and replace them, the context will actually keep an `Arc` pointed to the old data and prevent it from being deallocated.

**Comment by chrystianrgs** [comment]
Hi, your sequence no true, is false

**Comment by emkornfield** [comment]
Seems like this issue is resolved.  Going to close it.
